module Etc
  def self?.confstr: (::Integer p1) -> ::String?

  def self?.endgrent: () -> void

  def self?.endpwent: () -> void

  def self?.getgrent: () -> ::Etc::Group?

  def self?.getgrgid: (?::Integer group_id) -> ::Etc::Group

  def self?.getgrnam: (::String name) -> ::Etc::Group

  def self?.getlogin: () -> ::String?

  def self?.getpwent: () -> ::Etc::Passwd?

  def self?.getpwnam: (::String name) -> ::Etc::Passwd

  def self?.getpwuid: (?::Integer uid) -> ::Etc::Passwd

  def self?.group: () { (::Etc::Group group) -> void } -> void
                 | () -> ::Etc::Group?

  def self?.nprocessors: () -> ::Integer

  def self?.passwd: () { (::Etc::Passwd passwd) -> void } -> void
                  | () -> ::Etc::Passwd?

  def self?.setgrent: () -> void

  def self?.setpwent: () -> void

  def self?.sysconf: (::Integer p1) -> ::Integer

  def self?.sysconfdir: () -> ::String

  def self?.systmpdir: () -> ::String

  def self?.uname: () -> { sysname: ::String, nodename: ::String, release: ::String, version: ::String, machine: ::String }

  private

  CS_PATH: Integer

  CS_POSIX_V6_ILP32_OFF32_CFLAGS: Integer

  CS_POSIX_V6_ILP32_OFF32_LDFLAGS: Integer

  CS_POSIX_V6_ILP32_OFF32_LIBS: Integer

  CS_POSIX_V6_ILP32_OFFBIG_CFLAGS: Integer

  CS_POSIX_V6_ILP32_OFFBIG_LDFLAGS: Integer

  CS_POSIX_V6_ILP32_OFFBIG_LIBS: Integer

  CS_POSIX_V6_LP64_OFF64_CFLAGS: Integer

  CS_POSIX_V6_LP64_OFF64_LDFLAGS: Integer

  CS_POSIX_V6_LP64_OFF64_LIBS: Integer

  CS_POSIX_V6_LPBIG_OFFBIG_CFLAGS: Integer

  CS_POSIX_V6_LPBIG_OFFBIG_LDFLAGS: Integer

  CS_POSIX_V6_LPBIG_OFFBIG_LIBS: Integer

  CS_POSIX_V6_WIDTH_RESTRICTED_ENVS: Integer

  PC_2_SYMLINKS: Integer

  PC_ALLOC_SIZE_MIN: Integer

  PC_ASYNC_IO: Integer

  PC_CHOWN_RESTRICTED: Integer

  PC_FILESIZEBITS: Integer

  PC_LINK_MAX: Integer

  PC_MAX_CANON: Integer

  PC_MAX_INPUT: Integer

  PC_NAME_MAX: Integer

  PC_NO_TRUNC: Integer

  PC_PATH_MAX: Integer

  PC_PIPE_BUF: Integer

  PC_PRIO_IO: Integer

  PC_REC_INCR_XFER_SIZE: Integer

  PC_REC_MAX_XFER_SIZE: Integer

  PC_REC_MIN_XFER_SIZE: Integer

  PC_REC_XFER_ALIGN: Integer

  PC_SYMLINK_MAX: Integer

  PC_SYNC_IO: Integer

  PC_VDISABLE: Integer

  SC_2_CHAR_TERM: Integer

  SC_2_C_BIND: Integer

  SC_2_C_DEV: Integer

  SC_2_FORT_DEV: Integer

  SC_2_FORT_RUN: Integer

  SC_2_LOCALEDEF: Integer

  SC_2_PBS: Integer

  SC_2_PBS_ACCOUNTING: Integer

  SC_2_PBS_CHECKPOINT: Integer

  SC_2_PBS_LOCATE: Integer

  SC_2_PBS_MESSAGE: Integer

  SC_2_PBS_TRACK: Integer

  SC_2_SW_DEV: Integer

  SC_2_UPE: Integer

  SC_2_VERSION: Integer

  SC_ADVISORY_INFO: Integer

  SC_AIO_LISTIO_MAX: Integer

  SC_AIO_MAX: Integer

  SC_AIO_PRIO_DELTA_MAX: Integer

  SC_ARG_MAX: Integer

  SC_ASYNCHRONOUS_IO: Integer

  SC_ATEXIT_MAX: Integer

  SC_BARRIERS: Integer

  SC_BC_BASE_MAX: Integer

  SC_BC_DIM_MAX: Integer

  SC_BC_SCALE_MAX: Integer

  SC_BC_STRING_MAX: Integer

  SC_CHILD_MAX: Integer

  SC_CLK_TCK: Integer

  SC_CLOCK_SELECTION: Integer

  SC_COLL_WEIGHTS_MAX: Integer

  SC_CPUTIME: Integer

  SC_DELAYTIMER_MAX: Integer

  SC_EXPR_NEST_MAX: Integer

  SC_FSYNC: Integer

  SC_GETGR_R_SIZE_MAX: Integer

  SC_GETPW_R_SIZE_MAX: Integer

  SC_HOST_NAME_MAX: Integer

  SC_IOV_MAX: Integer

  SC_IPV6: Integer

  SC_JOB_CONTROL: Integer

  SC_LINE_MAX: Integer

  SC_LOGIN_NAME_MAX: Integer

  SC_MAPPED_FILES: Integer

  SC_MEMLOCK: Integer

  SC_MEMLOCK_RANGE: Integer

  SC_MEMORY_PROTECTION: Integer

  SC_MESSAGE_PASSING: Integer

  SC_MONOTONIC_CLOCK: Integer

  SC_MQ_OPEN_MAX: Integer

  SC_MQ_PRIO_MAX: Integer

  SC_NGROUPS_MAX: Integer

  SC_NPROCESSORS_CONF: Integer

  SC_NPROCESSORS_ONLN: Integer

  SC_OPEN_MAX: Integer

  SC_PAGESIZE: Integer

  SC_PAGE_SIZE: Integer

  SC_PHYS_PAGES: Integer

  SC_PRIORITIZED_IO: Integer

  SC_PRIORITY_SCHEDULING: Integer

  SC_RAW_SOCKETS: Integer

  SC_READER_WRITER_LOCKS: Integer

  SC_REALTIME_SIGNALS: Integer

  SC_REGEXP: Integer

  SC_RE_DUP_MAX: Integer

  SC_RTSIG_MAX: Integer

  SC_SAVED_IDS: Integer

  SC_SEMAPHORES: Integer

  SC_SEM_NSEMS_MAX: Integer

  SC_SEM_VALUE_MAX: Integer

  SC_SHARED_MEMORY_OBJECTS: Integer

  SC_SHELL: Integer

  SC_SIGQUEUE_MAX: Integer

  SC_SPAWN: Integer

  SC_SPIN_LOCKS: Integer

  SC_SPORADIC_SERVER: Integer

  SC_SS_REPL_MAX: Integer

  SC_STREAM_MAX: Integer

  SC_SYMLOOP_MAX: Integer

  SC_SYNCHRONIZED_IO: Integer

  SC_THREADS: Integer

  SC_THREAD_ATTR_STACKADDR: Integer

  SC_THREAD_ATTR_STACKSIZE: Integer

  SC_THREAD_CPUTIME: Integer

  SC_THREAD_DESTRUCTOR_ITERATIONS: Integer

  SC_THREAD_KEYS_MAX: Integer

  SC_THREAD_PRIORITY_SCHEDULING: Integer

  SC_THREAD_PRIO_INHERIT: Integer

  SC_THREAD_PRIO_PROTECT: Integer

  SC_THREAD_PROCESS_SHARED: Integer

  SC_THREAD_SAFE_FUNCTIONS: Integer

  SC_THREAD_SPORADIC_SERVER: Integer

  SC_THREAD_STACK_MIN: Integer

  SC_THREAD_THREADS_MAX: Integer

  SC_TIMEOUTS: Integer

  SC_TIMERS: Integer

  SC_TIMER_MAX: Integer

  SC_TRACE: Integer

  SC_TRACE_EVENT_FILTER: Integer

  SC_TRACE_EVENT_NAME_MAX: Integer

  SC_TRACE_INHERIT: Integer

  SC_TRACE_LOG: Integer

  SC_TRACE_NAME_MAX: Integer

  SC_TRACE_SYS_MAX: Integer

  SC_TRACE_USER_EVENT_MAX: Integer

  SC_TTY_NAME_MAX: Integer

  SC_TYPED_MEMORY_OBJECTS: Integer

  SC_TZNAME_MAX: Integer

  SC_V6_ILP32_OFF32: Integer

  SC_V6_ILP32_OFFBIG: Integer

  SC_V6_LP64_OFF64: Integer

  SC_V6_LPBIG_OFFBIG: Integer

  SC_VERSION: Integer

  SC_XOPEN_CRYPT: Integer

  SC_XOPEN_ENH_I18N: Integer

  SC_XOPEN_REALTIME: Integer

  SC_XOPEN_REALTIME_THREADS: Integer

  SC_XOPEN_SHM: Integer

  SC_XOPEN_STREAMS: Integer

  SC_XOPEN_UNIX: Integer

  SC_XOPEN_VERSION: Integer

  VERSION: String

  class Group < Struct[untyped]
    extend Enumerable[untyped]

    def self.[]: (*untyped) -> untyped

    def self.each: () -> untyped

    def self.inspect: () -> untyped

    def self.keyword_init?: () -> untyped

    def self.members: () -> untyped

    def self.new: (*untyped) -> untyped

    def gid: () -> Integer

    def gid=: (Integer new_gid) -> void

    def mem: () -> Array[String]

    def mem=: (Array[String] new_mem) -> void

    def name: () -> String

    def name=: (String new_name) -> void

    def passwd: () -> String

    def passwd=: (String new_passwd) -> void
  end

  class Passwd < Struct[untyped]
    extend Enumerable[untyped]

    def self.[]: (*untyped) -> untyped

    def self.each: () -> untyped

    def self.inspect: () -> untyped

    def self.keyword_init?: () -> untyped

    def self.members: () -> untyped

    def self.new: (*untyped) -> untyped

    def change: () -> Integer

    def change=: (Integer new_change) -> void

    def dir: () -> String

    def dir=: (String new_dir) -> void

    def expire: () -> Integer

    def expire=: (Integer new_expire) -> void

    def gecos: () -> String

    def gecos=: (String new_gecos) -> void

    def gid: () -> Integer

    def gid=: (Integer new_gid) -> void

    def name: () -> String

    def name=: (String new_name) -> void

    def passwd: () -> String

    def passwd=: (String new_passwd) -> void

    def shell: () -> String

    def shell=: (String new_shell) -> void

    def uclass: () -> String

    def uclass=: (String new_uclass) -> void

    def uid: () -> Integer

    def uid=: (Integer new_uid) -> void
  end
end
