class Addrinfo
  def self.foreach: (String? nodename, String | Integer service, ?Integer? family, ?Symbol socktype, ?Symbol | Integer protocol, ?Integer flags, ?timeout: Numeric) { (Addrinfo) -> void } -> void
                  | (String? nodename, String | Integer service, ?Integer? family, ?Symbol socktype, ?Symbol | Integer protocol, ?Integer flags, ?timeout: Numeric) -> Enumerable[Addrinfo]

  def self.getaddrinfo: (String nodename, ?(String | Integer)? service, ?(Symbol | Integer)? family, ?Symbol | Integer protocol) -> Array[Addrinfo]
                      | (String? nodename, ?(String | Integer) service, ?(Symbol | Integer)? family, ?Symbol | Integer protocol) -> Array[Addrinfo]

  def self.ip: (String host) -> Addrinfo

  def self.tcp: (String host, String | Integer service) -> Addrinfo

  def self.udp: (String host, String | Integer service) -> Addrinfo

  def self.unix: (String path, ?Symbol socktype) -> Addrinfo

  def afamily: () -> Integer

  def bind: () -> Socket
          | () { (Socket) -> void } -> void

  def canonname: () -> String

  def connect: (?timeout: Numeric) { (Socket) -> void } -> void
             | (?timeout: Numeric) -> Socket

  def connect_from: (String host, Integer port, ?timeout: Numeric) { (Socket) -> void } -> void
                  | (String host, Integer port, ?timeout: Numeric) -> Socket
                  | (Addrinfo sockaddr, ?timeout: Numeric) { (Socket) -> void } -> void
                  | (Addrinfo sockaddr, ?timeout: Numeric) -> Socket

  def connect_to: (String host, Integer port, ?timeout: Numeric) { (Socket) -> void } -> void
                | (String host, Integer port, ?timeout: Numeric) -> Socket
                | (Addrinfo sockaddr, ?timeout: Numeric) { (Socket) -> void } -> void
                | (Addrinfo sockaddr, ?timeout: Numeric) -> Socket

  def family_addrinfo: (String host, Integer port) -> Addrinfo
                     | (String path) -> Addrinfo

  def getnameinfo: (?Integer flags) -> [ String, Integer ]

  def inspect: () -> String

  def inspect_sockaddr: () -> String

  def ip?: () -> bool

  def ip_address: () -> String

  def ip_port: () -> Integer

  def ip_unpack: () -> [ String, Integer ]

  def ipv4?: () -> bool

  def ipv4_loopback?: () -> bool

  def ipv4_multicast?: () -> bool

  def ipv4_private?: () -> bool

  def ipv6?: () -> bool

  def ipv6_linklocal?: () -> bool

  def ipv6_loopback?: () -> bool

  def ipv6_mc_global?: () -> bool

  def ipv6_mc_linklocal?: () -> bool

  def ipv6_mc_nodelocal?: () -> bool

  def ipv6_mc_orglocal?: () -> bool

  def ipv6_mc_sitelocal?: () -> bool

  def ipv6_multicast?: () -> bool

  def ipv6_sitelocal?: () -> bool

  def ipv6_to_ipv4: () -> Addrinfo?

  def ipv6_unique_local?: () -> bool

  def ipv6_unspecified?: () -> bool

  def ipv6_v4compat?: () -> bool

  def ipv6_v4mapped?: () -> bool

  def listen: (Integer backlog) -> void

  def marshal_dump: () -> String

  def marshal_load: (String) -> self

  def pfamily: () -> Integer

  def protocol: () -> Integer

  def socktype: () -> Integer

  def to_s: () -> String

  def to_sockaddr: () -> String

  def unix?: () -> bool

  def unix_path: () -> String

  private

  def initialize: (String sockaddr, ?Symbol family, ?(Symbol | Integer)? socktype, ?Integer? protocol) -> untyped
end
