class BasicSocket < IO
  def self.do_not_reverse_lookup: () -> bool

  def self.do_not_reverse_lookup=: (boolish) -> void

  def self.for_fd: (Integer fileno) -> BasicSocket

  def close_read: () -> void

  def close_write: () -> void

  def connect_address: () -> Addrinfo

  def do_not_reverse_lookup: () -> bool

  def do_not_reverse_lookup=: (boolish) -> void

  def getpeereid: () -> [ Integer, Integer ]

  def getpeername: () -> String

  def getsockname: () -> String

  def getsockopt: (Symbol | Integer, Symbol | Integer) -> (Integer | boolish | String)

  def local_address: () -> Addrinfo

  def recv: (Integer maxlen, ?Integer flags, ?String outbuf) -> String
          | (Integer maxlen, ?String outbuf) -> String

  def recv_nonblock: (Integer maxlen, ?Integer flags, ?String buf, ?exception: boolish) -> (String | :wait_readable)

  def recvmsg: (?Integer dlen, ?Integer flags, ?Integer clen, ?scm_rights: boolish) -> [ String, Addrinfo, Integer?, Array[Socket::AncillaryData] ]

  def recvmsg_nonblock: (?Integer dlen, ?Integer flags, ?Integer clen, ?exception: boolish, ?scm_rights: boolish) -> ([ String, Addrinfo, Integer?, Array[Socket::AncillaryData] ] | :wait_readable)

  def remote_address: () -> Addrinfo

  def send: (String msg, ?Integer flags, ?Addrinfo | String dest_sockaddr) -> void

  def sendmsg: (String mesg, ?Integer flags, ?Addrinfo | String dest_sockaddr, *Socket::AncillaryData controls) -> Integer

  def sendmsg_nonblock: (String mesg, ?Integer flags, ?Addrinfo | String dest_sockaddr, *Socket::AncillaryData controls, ?exception: boolish) -> (Integer | :wait_writable)

  def setsockopt: (*Symbol | Integer, boolish | Integer | String) -> void

  def shutdown: (interned | Integer flags) -> void

  private

  def __recv_nonblock: (untyped, untyped, untyped, untyped) -> untyped

  def __recvmsg: (untyped, untyped, untyped, untyped) -> untyped

  def __recvmsg_nonblock: (untyped, untyped, untyped, untyped, untyped) -> untyped

  def __sendmsg: (untyped, untyped, untyped, untyped) -> untyped

  def __sendmsg_nonblock: (untyped, untyped, untyped, untyped, untyped) -> untyped
end
