module Socket::Constants
  AF_ALG: Integer

  AF_APPLETALK: Integer

  AF_ATM: Integer

  AF_AX25: Integer

  AF_BLUETOOTH: Integer

  AF_CAN: Integer

  AF_CCITT: Integer

  AF_CHAOS: Integer

  AF_CNT: Integer

  AF_COIP: Integer

  AF_DATAKIT: Integer

  AF_DEC: Integer

  AF_DECnet: Integer

  AF_DLI: Integer

  AF_E164: Integer

  AF_ECMA: Integer

  AF_HYLINK: Integer

  AF_IB: Integer

  AF_IMPLINK: Integer

  AF_INET: Integer

  AF_INET6: Integer

  AF_IPX: Integer

  AF_ISDN: Integer

  AF_ISO: Integer

  AF_KCM: Integer

  AF_KEY: Integer

  AF_LAT: Integer

  AF_LINK: Integer

  AF_LLC: Integer

  AF_LOCAL: Integer

  AF_MAX: Integer

  AF_MPLS: Integer

  AF_NATM: Integer

  AF_NDRV: Integer

  AF_NETBIOS: Integer

  AF_NETGRAPH: Integer

  AF_NETLINK: Integer

  AF_NS: Integer

  AF_OSI: Integer

  AF_PACKET: Integer

  AF_PPP: Integer

  AF_PPPOX: Integer

  AF_PUP: Integer

  AF_RDS: Integer

  AF_ROUTE: Integer

  AF_SIP: Integer

  AF_SNA: Integer

  AF_SYSTEM: Integer

  AF_TIPC: Integer

  AF_UNIX: Integer

  AF_UNSPEC: Integer

  AF_VSOCK: Integer

  AF_XDP: Integer

  AI_ADDRCONFIG: Integer

  AI_ALL: Integer

  AI_CANONNAME: Integer

  AI_DEFAULT: Integer

  AI_MASK: Integer

  AI_NUMERICHOST: Integer

  AI_NUMERICSERV: Integer

  AI_PASSIVE: Integer

  AI_V4MAPPED: Integer

  AI_V4MAPPED_CFG: Integer

  EAI_ADDRFAMILY: Integer

  EAI_AGAIN: Integer

  EAI_BADFLAGS: Integer

  EAI_BADHINTS: Integer

  EAI_FAIL: Integer

  EAI_FAMILY: Integer

  EAI_MAX: Integer

  EAI_MEMORY: Integer

  EAI_NODATA: Integer

  EAI_NONAME: Integer

  EAI_OVERFLOW: Integer

  EAI_PROTOCOL: Integer

  EAI_SERVICE: Integer

  EAI_SOCKTYPE: Integer

  EAI_SYSTEM: Integer

  IFF_802_1Q_VLAN: Integer

  IFF_ALLMULTI: Integer

  IFF_ALTPHYS: Integer

  IFF_AUTOMEDIA: Integer

  IFF_BONDING: Integer

  IFF_BRIDGE_PORT: Integer

  IFF_BROADCAST: Integer

  IFF_CANTCHANGE: Integer

  IFF_CANTCONFIG: Integer

  IFF_DEBUG: Integer

  IFF_DISABLE_NETPOLL: Integer

  IFF_DONT_BRIDGE: Integer

  IFF_DORMANT: Integer

  IFF_DRV_OACTIVE: Integer

  IFF_DRV_RUNNING: Integer

  IFF_DYING: Integer

  IFF_DYNAMIC: Integer

  IFF_EBRIDGE: Integer

  IFF_ECHO: Integer

  IFF_ISATAP: Integer

  IFF_LINK0: Integer

  IFF_LINK1: Integer

  IFF_LINK2: Integer

  IFF_LIVE_ADDR_CHANGE: Integer

  IFF_LOOPBACK: Integer

  IFF_LOWER_UP: Integer

  IFF_MACVLAN_PORT: Integer

  IFF_MASTER: Integer

  IFF_MASTER_8023AD: Integer

  IFF_MASTER_ALB: Integer

  IFF_MASTER_ARPMON: Integer

  IFF_MONITOR: Integer

  IFF_MULTICAST: Integer

  IFF_NOARP: Integer

  IFF_NOTRAILERS: Integer

  IFF_OACTIVE: Integer

  IFF_OVS_DATAPATH: Integer

  IFF_POINTOPOINT: Integer

  IFF_PORTSEL: Integer

  IFF_PPROMISC: Integer

  IFF_PROMISC: Integer

  IFF_RENAMING: Integer

  IFF_ROUTE: Integer

  IFF_RUNNING: Integer

  IFF_SIMPLEX: Integer

  IFF_SLAVE: Integer

  IFF_SLAVE_INACTIVE: Integer

  IFF_SLAVE_NEEDARP: Integer

  IFF_SMART: Integer

  IFF_STATICARP: Integer

  IFF_SUPP_NOFCS: Integer

  IFF_TEAM_PORT: Integer

  IFF_TX_SKB_SHARING: Integer

  IFF_UNICAST_FLT: Integer

  IFF_UP: Integer

  IFF_VOLATILE: Integer

  IFF_WAN_HDLC: Integer

  IFF_XMIT_DST_RELEASE: Integer

  IFNAMSIZ: Integer

  IF_NAMESIZE: Integer

  INADDR_ALLHOSTS_GROUP: Integer

  INADDR_ANY: Integer

  INADDR_BROADCAST: Integer

  INADDR_LOOPBACK: Integer

  INADDR_MAX_LOCAL_GROUP: Integer

  INADDR_NONE: Integer

  INADDR_UNSPEC_GROUP: Integer

  INET6_ADDRSTRLEN: Integer

  INET_ADDRSTRLEN: Integer

  IPPORT_RESERVED: Integer

  IPPORT_USERRESERVED: Integer

  IPPROTO_AH: Integer

  IPPROTO_BIP: Integer

  IPPROTO_DSTOPTS: Integer

  IPPROTO_EGP: Integer

  IPPROTO_EON: Integer

  IPPROTO_ESP: Integer

  IPPROTO_FRAGMENT: Integer

  IPPROTO_GGP: Integer

  IPPROTO_HELLO: Integer

  IPPROTO_HOPOPTS: Integer

  IPPROTO_ICMP: Integer

  IPPROTO_ICMPV6: Integer

  IPPROTO_IDP: Integer

  IPPROTO_IGMP: Integer

  IPPROTO_IP: Integer

  IPPROTO_IPV6: Integer

  IPPROTO_MAX: Integer

  IPPROTO_ND: Integer

  IPPROTO_NONE: Integer

  IPPROTO_PUP: Integer

  IPPROTO_RAW: Integer

  IPPROTO_ROUTING: Integer

  IPPROTO_TCP: Integer

  IPPROTO_TP: Integer

  IPPROTO_UDP: Integer

  IPPROTO_XTP: Integer

  IPV6_CHECKSUM: Integer

  IPV6_DONTFRAG: Integer

  IPV6_DSTOPTS: Integer

  IPV6_HOPLIMIT: Integer

  IPV6_HOPOPTS: Integer

  IPV6_JOIN_GROUP: Integer

  IPV6_LEAVE_GROUP: Integer

  IPV6_MULTICAST_HOPS: Integer

  IPV6_MULTICAST_IF: Integer

  IPV6_MULTICAST_LOOP: Integer

  IPV6_NEXTHOP: Integer

  IPV6_PATHMTU: Integer

  IPV6_PKTINFO: Integer

  IPV6_RECVDSTOPTS: Integer

  IPV6_RECVHOPLIMIT: Integer

  IPV6_RECVHOPOPTS: Integer

  IPV6_RECVPATHMTU: Integer

  IPV6_RECVPKTINFO: Integer

  IPV6_RECVRTHDR: Integer

  IPV6_RECVTCLASS: Integer

  IPV6_RTHDR: Integer

  IPV6_RTHDRDSTOPTS: Integer

  IPV6_RTHDR_TYPE_0: Integer

  IPV6_TCLASS: Integer

  IPV6_UNICAST_HOPS: Integer

  IPV6_USE_MIN_MTU: Integer

  IPV6_V6ONLY: Integer

  IPX_TYPE: Integer

  IP_ADD_MEMBERSHIP: Integer

  IP_ADD_SOURCE_MEMBERSHIP: Integer

  IP_BLOCK_SOURCE: Integer

  IP_DEFAULT_MULTICAST_LOOP: Integer

  IP_DEFAULT_MULTICAST_TTL: Integer

  IP_DONTFRAG: Integer

  IP_DROP_MEMBERSHIP: Integer

  IP_DROP_SOURCE_MEMBERSHIP: Integer

  IP_FREEBIND: Integer

  IP_HDRINCL: Integer

  IP_IPSEC_POLICY: Integer

  IP_MAX_MEMBERSHIPS: Integer

  IP_MINTTL: Integer

  IP_MSFILTER: Integer

  IP_MTU: Integer

  IP_MTU_DISCOVER: Integer

  IP_MULTICAST_IF: Integer

  IP_MULTICAST_LOOP: Integer

  IP_MULTICAST_TTL: Integer

  IP_ONESBCAST: Integer

  IP_OPTIONS: Integer

  IP_PASSSEC: Integer

  IP_PKTINFO: Integer

  IP_PKTOPTIONS: Integer

  IP_PMTUDISC_DO: Integer

  IP_PMTUDISC_DONT: Integer

  IP_PMTUDISC_WANT: Integer

  IP_PORTRANGE: Integer

  IP_RECVDSTADDR: Integer

  IP_RECVERR: Integer

  IP_RECVIF: Integer

  IP_RECVOPTS: Integer

  IP_RECVRETOPTS: Integer

  IP_RECVSLLA: Integer

  IP_RECVTOS: Integer

  IP_RECVTTL: Integer

  IP_RETOPTS: Integer

  IP_ROUTER_ALERT: Integer

  IP_SENDSRCADDR: Integer

  IP_TOS: Integer

  IP_TRANSPARENT: Integer

  IP_TTL: Integer

  IP_UNBLOCK_SOURCE: Integer

  IP_XFRM_POLICY: Integer

  LOCAL_CONNWAIT: Integer

  LOCAL_CREDS: Integer

  LOCAL_PEERCRED: Integer

  MCAST_BLOCK_SOURCE: Integer

  MCAST_EXCLUDE: Integer

  MCAST_INCLUDE: Integer

  MCAST_JOIN_GROUP: Integer

  MCAST_JOIN_SOURCE_GROUP: Integer

  MCAST_LEAVE_GROUP: Integer

  MCAST_LEAVE_SOURCE_GROUP: Integer

  MCAST_MSFILTER: Integer

  MCAST_UNBLOCK_SOURCE: Integer

  MSG_COMPAT: Integer

  MSG_CONFIRM: Integer

  MSG_CTRUNC: Integer

  MSG_DONTROUTE: Integer

  MSG_DONTWAIT: Integer

  MSG_EOF: Integer

  MSG_EOR: Integer

  MSG_ERRQUEUE: Integer

  MSG_FASTOPEN: Integer

  MSG_FIN: Integer

  MSG_FLUSH: Integer

  MSG_HAVEMORE: Integer

  MSG_HOLD: Integer

  MSG_MORE: Integer

  MSG_NOSIGNAL: Integer

  MSG_OOB: Integer

  MSG_PEEK: Integer

  MSG_PROXY: Integer

  MSG_RCVMORE: Integer

  MSG_RST: Integer

  MSG_SEND: Integer

  MSG_SYN: Integer

  MSG_TRUNC: Integer

  MSG_WAITALL: Integer

  NI_DGRAM: Integer

  NI_MAXHOST: Integer

  NI_MAXSERV: Integer

  NI_NAMEREQD: Integer

  NI_NOFQDN: Integer

  NI_NUMERICHOST: Integer

  NI_NUMERICSERV: Integer

  PF_ALG: Integer

  PF_APPLETALK: Integer

  PF_ATM: Integer

  PF_AX25: Integer

  PF_BLUETOOTH: Integer

  PF_CAN: Integer

  PF_CCITT: Integer

  PF_CHAOS: Integer

  PF_CNT: Integer

  PF_COIP: Integer

  PF_DATAKIT: Integer

  PF_DEC: Integer

  PF_DECnet: Integer

  PF_DLI: Integer

  PF_ECMA: Integer

  PF_HYLINK: Integer

  PF_IB: Integer

  PF_IMPLINK: Integer

  PF_INET: Integer

  PF_INET6: Integer

  PF_IPX: Integer

  PF_ISDN: Integer

  PF_ISO: Integer

  PF_KCM: Integer

  PF_KEY: Integer

  PF_LAT: Integer

  PF_LINK: Integer

  PF_LLC: Integer

  PF_LOCAL: Integer

  PF_MAX: Integer

  PF_MPLS: Integer

  PF_NATM: Integer

  PF_NDRV: Integer

  PF_NETBIOS: Integer

  PF_NETGRAPH: Integer

  PF_NETLINK: Integer

  PF_NS: Integer

  PF_OSI: Integer

  PF_PACKET: Integer

  PF_PIP: Integer

  PF_PPP: Integer

  PF_PPPOX: Integer

  PF_PUP: Integer

  PF_RDS: Integer

  PF_ROUTE: Integer

  PF_RTIP: Integer

  PF_SIP: Integer

  PF_SNA: Integer

  PF_SYSTEM: Integer

  PF_TIPC: Integer

  PF_UNIX: Integer

  PF_UNSPEC: Integer

  PF_VSOCK: Integer

  PF_XDP: Integer

  PF_XTP: Integer

  SCM_BINTIME: Integer

  SCM_CREDENTIALS: Integer

  SCM_CREDS: Integer

  SCM_RIGHTS: Integer

  SCM_TIMESTAMP: Integer

  SCM_TIMESTAMPING: Integer

  SCM_TIMESTAMPNS: Integer

  SCM_UCRED: Integer

  SCM_WIFI_STATUS: Integer

  SHUT_RD: Integer

  SHUT_RDWR: Integer

  SHUT_WR: Integer

  SOCK_CLOEXEC: Integer

  SOCK_DGRAM: Integer

  SOCK_NONBLOCK: Integer

  SOCK_PACKET: Integer

  SOCK_RAW: Integer

  SOCK_RDM: Integer

  SOCK_SEQPACKET: Integer

  SOCK_STREAM: Integer

  SOL_ATALK: Integer

  SOL_AX25: Integer

  SOL_IP: Integer

  SOL_IPX: Integer

  SOL_SOCKET: Integer

  SOL_TCP: Integer

  SOL_UDP: Integer

  SOMAXCONN: Integer

  SOPRI_BACKGROUND: Integer

  SOPRI_INTERACTIVE: Integer

  SOPRI_NORMAL: Integer

  SO_ACCEPTCONN: Integer

  SO_ACCEPTFILTER: Integer

  SO_ALLZONES: Integer

  SO_ATTACH_FILTER: Integer

  SO_BINDTODEVICE: Integer

  SO_BINTIME: Integer

  SO_BPF_EXTENSIONS: Integer

  SO_BROADCAST: Integer

  SO_BUSY_POLL: Integer

  SO_DEBUG: Integer

  SO_DETACH_FILTER: Integer

  SO_DOMAIN: Integer

  SO_DONTROUTE: Integer

  SO_DONTTRUNC: Integer

  SO_ERROR: Integer

  SO_GET_FILTER: Integer

  SO_KEEPALIVE: Integer

  SO_LINGER: Integer

  SO_LOCK_FILTER: Integer

  SO_MAC_EXEMPT: Integer

  SO_MARK: Integer

  SO_MAX_PACING_RATE: Integer

  SO_NKE: Integer

  SO_NOFCS: Integer

  SO_NOSIGPIPE: Integer

  SO_NO_CHECK: Integer

  SO_NREAD: Integer

  SO_OOBINLINE: Integer

  SO_PASSCRED: Integer

  SO_PASSSEC: Integer

  SO_PEEK_OFF: Integer

  SO_PEERCRED: Integer

  SO_PEERNAME: Integer

  SO_PEERSEC: Integer

  SO_PRIORITY: Integer

  SO_PROTOCOL: Integer

  SO_RCVBUF: Integer

  SO_RCVBUFFORCE: Integer

  SO_RCVLOWAT: Integer

  SO_RCVTIMEO: Integer

  SO_RECVUCRED: Integer

  SO_REUSEADDR: Integer

  SO_REUSEPORT: Integer

  SO_RXQ_OVFL: Integer

  SO_SECURITY_AUTHENTICATION: Integer

  SO_SECURITY_ENCRYPTION_NETWORK: Integer

  SO_SECURITY_ENCRYPTION_TRANSPORT: Integer

  SO_SELECT_ERR_QUEUE: Integer

  SO_SNDBUF: Integer

  SO_SNDBUFFORCE: Integer

  SO_SNDLOWAT: Integer

  SO_SNDTIMEO: Integer

  SO_TIMESTAMP: Integer

  SO_TIMESTAMPING: Integer

  SO_TIMESTAMPNS: Integer

  SO_TYPE: Integer

  SO_USELOOPBACK: Integer

  SO_WANTMORE: Integer

  SO_WANTOOBFLAG: Integer

  SO_WIFI_STATUS: Integer

  TCP_CONGESTION: Integer

  TCP_COOKIE_TRANSACTIONS: Integer

  TCP_CORK: Integer

  TCP_DEFER_ACCEPT: Integer

  TCP_FASTOPEN: Integer

  TCP_INFO: Integer

  TCP_KEEPCNT: Integer

  TCP_KEEPIDLE: Integer

  TCP_KEEPINTVL: Integer

  TCP_LINGER2: Integer

  TCP_MAXSEG: Integer

  TCP_MD5SIG: Integer

  TCP_NODELAY: Integer

  TCP_NOOPT: Integer

  TCP_NOPUSH: Integer

  TCP_QUEUE_SEQ: Integer

  TCP_QUICKACK: Integer

  TCP_REPAIR: Integer

  TCP_REPAIR_OPTIONS: Integer

  TCP_REPAIR_QUEUE: Integer

  TCP_SYNCNT: Integer

  TCP_THIN_DUPACK: Integer

  TCP_THIN_LINEAR_TIMEOUTS: Integer

  TCP_TIMESTAMP: Integer

  TCP_USER_TIMEOUT: Integer

  TCP_WINDOW_CLAMP: Integer

  UDP_CORK: Integer
end
