class IPSocket < BasicSocket
  def self.getaddress: (String host) -> String

  def addr: (?boolish | :hostname | :numeric reverse_lookup) -> [ String, Integer, String, String ]

  def inspect: () -> String

  def peeraddr: (?boolish | :hostname | :numeric reverse_lookup) -> [ String, Integer, String, String ]

  def recvfrom: (Integer maxlen, ?Integer flags) -> [ String, [ String, Integer, String, String ] ]
end
