class Socket < BasicSocket
  def self.accept_loop: (*_ToIO sockets) { (Socket) -> void } -> void

  def self.getaddrinfo: (String peer, String | Integer | nil protocol, ?Integer | Symbol | nil family, ?Integer | Symbol | nil socktype, ?Integer | Symbol | nil protocol, ?Integer | nil flags) -> [ String, Integer, String, String, Integer, Integer, Integer ]
                      | (String? peer, String | Integer protocol, ?Integer | Symbol | nil family, ?Integer | Symbol | nil socktype, ?Integer | Symbol | nil protocol, ?Integer | nil flags) -> [ String, Integer, String, String, Integer, Integer, Integer ]

  def self.gethostbyaddr: (String ip) -> [ String, Array[String], Integer, String ]

  def self.gethostbyname: (String name) -> [ String, Array[String], Integer, String ]

  def self.gethostname: () -> String

  def self.getifaddrs: () -> Array[Socket::Ifaddr]

  def self.getnameinfo: ([ String, Integer, String ]) -> Array[String]
                      | ([ String, Integer, String, String ]) -> Array[String]
                      | (String sockaddr) -> Array[String]

  def self.getservbyname: (String service_proto) -> Integer
                        | (String service_proto, String layer4_proto) -> Integer

  def self.getservbyport: (Integer service_port) -> String
                        | (Integer service_port, String layer4_proto) -> String

  def self.ip_address_list: () -> Array[Addrinfo]

  def self.pack_sockaddr_in: (Integer port, String ip) -> String

  def self.pack_sockaddr_un: (String sockpath) -> String

  def self.pair: (Symbol sockdomain, Symbol socktype, Integer protocol) -> [ instance, instance ]

  def self.sockaddr_in: (Integer port, String ip) -> String

  def self.sockaddr_un: (String sockpath) -> String

  def self.socketpair: (Symbol sockdomain, Symbol socktype, Integer protocol) -> [ instance, instance ]

  def self.tcp: (String host, Integer port, ?String local_host, ?Integer local_port, ?resolv_timeout: Time::_Timeout, ?connect_timeout: Time::_Timeout) -> instance
              | (String host, Integer port, ?String local_host, ?Integer local_port, ?open_timeout: Time::_Timeout) -> instance
              | [T] (String host, Integer port, ?String local_host, ?Integer local_port, ?resolv_timeout: Time::_Timeout, ?connect_timeout: Time::_Timeout) { (instance) -> T } -> T
              | [T] (String host, Integer port, ?String local_host, ?Integer local_port, ?open_timeout: Time::_Timeout) { (instance) -> T } -> T

  def self.tcp_server_loop: (?String host, Integer port) { (instance, Addrinfo) -> void } -> void

  def self.tcp_server_sockets: (?String host, Integer port) -> Array[TCPServer]
                             | (?String host, Integer port) { (Array[TCPServer]) -> void } -> void

  def self.udp_server_loop: (?String host, Integer port) { (String, Socket::UDPSource) -> void } -> void

  def self.udp_server_loop_on: (UDPSocket sockets) { (String, Socket::UDPSource) -> void } -> void

  def self.udp_server_recv: (Array[UDPSocket] sockets) { (String, Socket::UDPSource) -> void } -> void

  def self.udp_server_sockets: (?String host, Integer port) { (UDPSocket) -> void } -> void

  def self.unix: (String path) -> UNIXSocket
               | (String path) { (UNIXSocket) -> void } -> void

  def self.unix_server_loop: (String path) { (UNIXSocket, Addrinfo) -> void } -> void

  def self.unix_server_socket: (String path) -> Socket
                             | (String path) { (Socket) -> void } -> void

  def self.unpack_sockaddr_in: (String | Addrinfo sockaddr) -> [ Integer, String ]

  def self.unpack_sockaddr_un: (String path) -> String

  def accept: () -> [ Socket, Addrinfo ]

  def accept_nonblock: (?exception: boolish) -> ([ Socket, Addrinfo ] | :wait_readable)

  def bind: (String | Addrinfo local_sockaddr) -> void

  def connect: (String | Addrinfo remote_sockaddr) -> Integer

  def connect_nonblock: (untyped addr, ?exception: untyped) -> (Integer | :wait_writable)

  def ipv6only!: () -> void

  def listen: (Integer backlog_len) -> void

  def recvfrom: (Integer maxlen, ?Integer flags) -> [ String, Addrinfo ]

  def recvfrom_nonblock: (Integer maxlen, ?Integer flags, ?untyped outbuf, ?exception: boolish) -> ([ String, Addrinfo ] | :wait_readable)

  def sysaccept: () -> [ Integer, Addrinfo ]

  private

  def __accept_nonblock: (untyped) -> untyped

  def __connect_nonblock: (untyped, untyped) -> untyped

  def __recvfrom_nonblock: (untyped, untyped, untyped, untyped) -> untyped

  def initialize: (Symbol | Integer domain, Symbol | Integer socktype, ?Integer protocol) -> untyped
end

Socket::AF_ALG: Integer

Socket::AF_APPLETALK: Integer

Socket::AF_ATM: Integer

Socket::AF_AX25: Integer

Socket::AF_BLUETOOTH: Integer

Socket::AF_CAN: Integer

Socket::AF_CCITT: Integer

Socket::AF_CHAOS: Integer

Socket::AF_CNT: Integer

Socket::AF_COIP: Integer

Socket::AF_DATAKIT: Integer

Socket::AF_DEC: Integer

Socket::AF_DECnet: Integer

Socket::AF_DLI: Integer

Socket::AF_E164: Integer

Socket::AF_ECMA: Integer

Socket::AF_HYLINK: Integer

Socket::AF_IB: Integer

Socket::AF_IMPLINK: Integer

Socket::AF_INET: Integer

Socket::AF_INET6: Integer

Socket::AF_IPX: Integer

Socket::AF_ISDN: Integer

Socket::AF_ISO: Integer

Socket::AF_KCM: Integer

Socket::AF_KEY: Integer

Socket::AF_LAT: Integer

Socket::AF_LINK: Integer

Socket::AF_LLC: Integer

Socket::AF_LOCAL: Integer

Socket::AF_MAX: Integer

Socket::AF_MPLS: Integer

Socket::AF_NATM: Integer

Socket::AF_NDRV: Integer

Socket::AF_NETBIOS: Integer

Socket::AF_NETGRAPH: Integer

Socket::AF_NETLINK: Integer

Socket::AF_NS: Integer

Socket::AF_OSI: Integer

Socket::AF_PACKET: Integer

Socket::AF_PPP: Integer

Socket::AF_PPPOX: Integer

Socket::AF_PUP: Integer

Socket::AF_RDS: Integer

Socket::AF_ROUTE: Integer

Socket::AF_SIP: Integer

Socket::AF_SNA: Integer
Socket::AF_SYSTEM: Integer

Socket::AF_TIPC: Integer

Socket::AF_UNIX: Integer

Socket::AF_UNSPEC: Integer

Socket::AF_VSOCK: Integer

Socket::AF_XDP: Integer

Socket::AI_ADDRCONFIG: Integer

Socket::AI_ALL: Integer

Socket::AI_CANONNAME: Integer

Socket::AI_DEFAULT: Integer

Socket::AI_MASK: Integer

Socket::AI_NUMERICHOST: Integer

Socket::AI_NUMERICSERV: Integer

Socket::AI_PASSIVE: Integer

Socket::AI_V4MAPPED: Integer

Socket::AI_V4MAPPED_CFG: Integer

Socket::EAI_ADDRFAMILY: Integer

Socket::EAI_AGAIN: Integer

Socket::EAI_BADFLAGS: Integer

Socket::EAI_BADHINTS: Integer

Socket::EAI_FAIL: Integer

Socket::EAI_FAMILY: Integer

Socket::EAI_MAX: Integer

Socket::EAI_MEMORY: Integer

Socket::EAI_NODATA: Integer

Socket::EAI_NONAME: Integer

Socket::EAI_OVERFLOW: Integer

Socket::EAI_PROTOCOL: Integer

Socket::EAI_SERVICE: Integer

Socket::EAI_SOCKTYPE: Integer

Socket::EAI_SYSTEM: Integer

Socket::IFF_802_1Q_VLAN: Integer

Socket::IFF_ALLMULTI: Integer

Socket::IFF_ALTPHYS: Integer

Socket::IFF_AUTOMEDIA: Integer

Socket::IFF_BONDING: Integer

Socket::IFF_BRIDGE_PORT: Integer

Socket::IFF_BROADCAST: Integer

Socket::IFF_CANTCHANGE: Integer

Socket::IFF_CANTCONFIG: Integer

Socket::IFF_DEBUG: Integer

Socket::IFF_DISABLE_NETPOLL: Integer

Socket::IFF_DONT_BRIDGE: Integer

Socket::IFF_DORMANT: Integer

Socket::IFF_DRV_OACTIVE: Integer

Socket::IFF_DRV_RUNNING: Integer

Socket::IFF_DYING: Integer

Socket::IFF_DYNAMIC: Integer

Socket::IFF_EBRIDGE: Integer

Socket::IFF_ECHO: Integer

Socket::IFF_ISATAP: Integer

Socket::IFF_LINK0: Integer

Socket::IFF_LINK1: Integer

Socket::IFF_LINK2: Integer

Socket::IFF_LIVE_ADDR_CHANGE: Integer

Socket::IFF_LOOPBACK: Integer

Socket::IFF_LOWER_UP: Integer

Socket::IFF_MACVLAN_PORT: Integer

Socket::IFF_MASTER: Integer

Socket::IFF_MASTER_8023AD: Integer

Socket::IFF_MASTER_ALB: Integer

Socket::IFF_MASTER_ARPMON: Integer

Socket::IFF_MONITOR: Integer

Socket::IFF_MULTICAST: Integer

Socket::IFF_NOARP: Integer

Socket::IFF_NOTRAILERS: Integer

Socket::IFF_OACTIVE: Integer

Socket::IFF_OVS_DATAPATH: Integer

Socket::IFF_POINTOPOINT: Integer

Socket::IFF_PORTSEL: Integer

Socket::IFF_PPROMISC: Integer

Socket::IFF_PROMISC: Integer

Socket::IFF_RENAMING: Integer

Socket::IFF_ROUTE: Integer

Socket::IFF_RUNNING: Integer

Socket::IFF_SIMPLEX: Integer

Socket::IFF_SLAVE: Integer

Socket::IFF_SLAVE_INACTIVE: Integer

Socket::IFF_SLAVE_NEEDARP: Integer

Socket::IFF_SMART: Integer

Socket::IFF_STATICARP: Integer

Socket::IFF_SUPP_NOFCS: Integer

Socket::IFF_TEAM_PORT: Integer

Socket::IFF_TX_SKB_SHARING: Integer

Socket::IFF_UNICAST_FLT: Integer

Socket::IFF_UP: Integer

Socket::IFF_VOLATILE: Integer

Socket::IFF_WAN_HDLC: Integer

Socket::IFF_XMIT_DST_RELEASE: Integer

Socket::IFNAMSIZ: Integer

Socket::IF_NAMESIZE: Integer

Socket::INADDR_ALLHOSTS_GROUP: Integer

Socket::INADDR_ANY: Integer

Socket::INADDR_BROADCAST: Integer

Socket::INADDR_LOOPBACK: Integer

Socket::INADDR_MAX_LOCAL_GROUP: Integer

Socket::INADDR_NONE: Integer

Socket::INADDR_UNSPEC_GROUP: Integer

Socket::INET6_ADDRSTRLEN: Integer

Socket::INET_ADDRSTRLEN: Integer

Socket::IPPORT_RESERVED: Integer

Socket::IPPORT_USERRESERVED: Integer

Socket::IPPROTO_AH: Integer
Socket::IPPROTO_BIP: Integer

Socket::IPPROTO_DSTOPTS: Integer

Socket::IPPROTO_EGP: Integer

Socket::IPPROTO_EON: Integer

Socket::IPPROTO_ESP: Integer

Socket::IPPROTO_FRAGMENT: Integer

Socket::IPPROTO_GGP: Integer

Socket::IPPROTO_HELLO: Integer

Socket::IPPROTO_HOPOPTS: Integer

Socket::IPPROTO_ICMP: Integer

Socket::IPPROTO_ICMPV6: Integer

Socket::IPPROTO_IDP: Integer

Socket::IPPROTO_IGMP: Integer

Socket::IPPROTO_IP: Integer

Socket::IPPROTO_IPV6: Integer

Socket::IPPROTO_MAX: Integer

Socket::IPPROTO_ND: Integer

Socket::IPPROTO_NONE: Integer

Socket::IPPROTO_PUP: Integer

Socket::IPPROTO_RAW: Integer

Socket::IPPROTO_ROUTING: Integer

Socket::IPPROTO_TCP: Integer

Socket::IPPROTO_TP: Integer

Socket::IPPROTO_UDP: Integer

Socket::IPPROTO_XTP: Integer

Socket::IPV6_CHECKSUM: Integer

Socket::IPV6_DONTFRAG: Integer

Socket::IPV6_DSTOPTS: Integer

Socket::IPV6_HOPLIMIT: Integer

Socket::IPV6_HOPOPTS: Integer

Socket::IPV6_JOIN_GROUP: Integer

Socket::IPV6_LEAVE_GROUP: Integer

Socket::IPV6_MULTICAST_HOPS: Integer

Socket::IPV6_MULTICAST_IF: Integer

Socket::IPV6_MULTICAST_LOOP: Integer

Socket::IPV6_NEXTHOP: Integer

Socket::IPV6_PATHMTU: Integer

Socket::IPV6_PKTINFO: Integer

Socket::IPV6_RECVDSTOPTS: Integer

Socket::IPV6_RECVHOPLIMIT: Integer

Socket::IPV6_RECVHOPOPTS: Integer

Socket::IPV6_RECVPATHMTU: Integer

Socket::IPV6_RECVPKTINFO: Integer

Socket::IPV6_RECVRTHDR: Integer

Socket::IPV6_RECVTCLASS: Integer

Socket::IPV6_RTHDR: Integer

Socket::IPV6_RTHDRDSTOPTS: Integer

Socket::IPV6_RTHDR_TYPE_0: Integer

Socket::IPV6_TCLASS: Integer

Socket::IPV6_UNICAST_HOPS: Integer

Socket::IPV6_USE_MIN_MTU: Integer

Socket::IPV6_V6ONLY: Integer
Socket::IPX_TYPE: Integer

Socket::IP_ADD_MEMBERSHIP: Integer

Socket::IP_ADD_SOURCE_MEMBERSHIP: Integer

Socket::IP_BLOCK_SOURCE: Integer

Socket::IP_DEFAULT_MULTICAST_LOOP: Integer

Socket::IP_DEFAULT_MULTICAST_TTL: Integer

Socket::IP_DONTFRAG: Integer

Socket::IP_DROP_MEMBERSHIP: Integer

Socket::IP_DROP_SOURCE_MEMBERSHIP: Integer

Socket::IP_FREEBIND: Integer

Socket::IP_HDRINCL: Integer

Socket::IP_IPSEC_POLICY: Integer

Socket::IP_MAX_MEMBERSHIPS: Integer

Socket::IP_MINTTL: Integer

Socket::IP_MSFILTER: Integer

Socket::IP_MTU: Integer

Socket::IP_MTU_DISCOVER: Integer

Socket::IP_MULTICAST_IF: Integer

Socket::IP_MULTICAST_LOOP: Integer

Socket::IP_MULTICAST_TTL: Integer

Socket::IP_ONESBCAST: Integer

Socket::IP_OPTIONS: Integer

Socket::IP_PASSSEC: Integer

Socket::IP_PKTINFO: Integer

Socket::IP_PKTOPTIONS: Integer

Socket::IP_PMTUDISC_DO: Integer

Socket::IP_PMTUDISC_DONT: Integer

Socket::IP_PMTUDISC_WANT: Integer

Socket::IP_PORTRANGE: Integer

Socket::IP_RECVDSTADDR: Integer

Socket::IP_RECVERR: Integer

Socket::IP_RECVIF: Integer

Socket::IP_RECVOPTS: Integer

Socket::IP_RECVRETOPTS: Integer

Socket::IP_RECVSLLA: Integer

Socket::IP_RECVTOS: Integer

Socket::IP_RECVTTL: Integer

Socket::IP_RETOPTS: Integer

Socket::IP_ROUTER_ALERT: Integer

Socket::IP_SENDSRCADDR: Integer

Socket::IP_TOS: Integer

Socket::IP_TRANSPARENT: Integer

Socket::IP_TTL: Integer

Socket::IP_UNBLOCK_SOURCE: Integer
Socket::IP_XFRM_POLICY: Integer

Socket::LOCAL_CONNWAIT: Integer

Socket::LOCAL_CREDS: Integer

Socket::LOCAL_PEERCRED: Integer

Socket::MCAST_BLOCK_SOURCE: Integer

Socket::MCAST_EXCLUDE: Integer

Socket::MCAST_INCLUDE: Integer

Socket::MCAST_JOIN_GROUP: Integer

Socket::MCAST_JOIN_SOURCE_GROUP: Integer

Socket::MCAST_LEAVE_GROUP: Integer

Socket::MCAST_LEAVE_SOURCE_GROUP: Integer

Socket::MCAST_MSFILTER: Integer

Socket::MCAST_UNBLOCK_SOURCE: Integer

Socket::MSG_COMPAT: Integer

Socket::MSG_CONFIRM: Integer

Socket::MSG_CTRUNC: Integer

Socket::MSG_DONTROUTE: Integer

Socket::MSG_DONTWAIT: Integer

Socket::MSG_EOF: Integer

Socket::MSG_EOR: Integer

Socket::MSG_ERRQUEUE: Integer

Socket::MSG_FASTOPEN: Integer
Socket::MSG_FIN: Integer

Socket::MSG_FLUSH: Integer

Socket::MSG_HAVEMORE: Integer

Socket::MSG_HOLD: Integer

Socket::MSG_MORE: Integer

Socket::MSG_NOSIGNAL: Integer

Socket::MSG_OOB: Integer

Socket::MSG_PEEK: Integer

Socket::MSG_PROXY: Integer

Socket::MSG_RCVMORE: Integer
Socket::MSG_RST: Integer

Socket::MSG_SEND: Integer
Socket::MSG_SYN: Integer

Socket::MSG_TRUNC: Integer

Socket::MSG_WAITALL: Integer

Socket::NI_DGRAM: Integer

Socket::NI_MAXHOST: Integer

Socket::NI_MAXSERV: Integer

Socket::NI_NAMEREQD: Integer

Socket::NI_NOFQDN: Integer

Socket::NI_NUMERICHOST: Integer

Socket::NI_NUMERICSERV: Integer

Socket::PF_ALG: Integer

Socket::PF_APPLETALK: Integer

Socket::PF_ATM: Integer

Socket::PF_AX25: Integer

Socket::PF_BLUETOOTH: Integer

Socket::PF_CAN: Integer

Socket::PF_CCITT: Integer

Socket::PF_CHAOS: Integer

Socket::PF_CNT: Integer

Socket::PF_COIP: Integer

Socket::PF_DATAKIT: Integer

Socket::PF_DEC: Integer

Socket::PF_DECnet: Integer

Socket::PF_DLI: Integer

Socket::PF_ECMA: Integer

Socket::PF_HYLINK: Integer

Socket::PF_IB: Integer

Socket::PF_IMPLINK: Integer

Socket::PF_INET: Integer

Socket::PF_INET6: Integer

Socket::PF_IPX: Integer

Socket::PF_ISDN: Integer

Socket::PF_ISO: Integer

Socket::PF_KCM: Integer

Socket::PF_KEY: Integer

Socket::PF_LAT: Integer

Socket::PF_LINK: Integer

Socket::PF_LLC: Integer

Socket::PF_LOCAL: Integer

Socket::PF_MAX: Integer

Socket::PF_MPLS: Integer

Socket::PF_NATM: Integer

Socket::PF_NDRV: Integer

Socket::PF_NETBIOS: Integer

Socket::PF_NETGRAPH: Integer

Socket::PF_NETLINK: Integer

Socket::PF_NS: Integer

Socket::PF_OSI: Integer

Socket::PF_PACKET: Integer
Socket::PF_PIP: Integer

Socket::PF_PPP: Integer

Socket::PF_PPPOX: Integer

Socket::PF_PUP: Integer

Socket::PF_RDS: Integer

Socket::PF_ROUTE: Integer
Socket::PF_RTIP: Integer

Socket::PF_SIP: Integer

Socket::PF_SNA: Integer
Socket::PF_SYSTEM: Integer

Socket::PF_TIPC: Integer

Socket::PF_UNIX: Integer

Socket::PF_UNSPEC: Integer

Socket::PF_VSOCK: Integer

Socket::PF_XDP: Integer

Socket::PF_XTP: Integer

Socket::SCM_BINTIME: Integer

Socket::SCM_CREDENTIALS: Integer

Socket::SCM_CREDS: Integer

Socket::SCM_RIGHTS: Integer

Socket::SCM_TIMESTAMP: Integer

Socket::SCM_TIMESTAMPING: Integer

Socket::SCM_TIMESTAMPNS: Integer

Socket::SCM_UCRED: Integer

Socket::SCM_WIFI_STATUS: Integer

Socket::SHUT_RD: Integer

Socket::SHUT_RDWR: Integer

Socket::SHUT_WR: Integer

Socket::SOCK_CLOEXEC: Integer

Socket::SOCK_DGRAM: Integer

Socket::SOCK_NONBLOCK: Integer

Socket::SOCK_PACKET: Integer

Socket::SOCK_RAW: Integer

Socket::SOCK_RDM: Integer

Socket::SOCK_SEQPACKET: Integer

Socket::SOCK_STREAM: Integer

Socket::SOL_ATALK: Integer

Socket::SOL_AX25: Integer

Socket::SOL_IP: Integer

Socket::SOL_IPX: Integer

Socket::SOL_SOCKET: Integer

Socket::SOL_TCP: Integer

Socket::SOL_UDP: Integer

Socket::SOMAXCONN: Integer

Socket::SOPRI_BACKGROUND: Integer

Socket::SOPRI_INTERACTIVE: Integer

Socket::SOPRI_NORMAL: Integer

Socket::SO_ACCEPTCONN: Integer

Socket::SO_ACCEPTFILTER: Integer

Socket::SO_ALLZONES: Integer

Socket::SO_ATTACH_FILTER: Integer

Socket::SO_BINDTODEVICE: Integer

Socket::SO_BINTIME: Integer

Socket::SO_BPF_EXTENSIONS: Integer

Socket::SO_BROADCAST: Integer

Socket::SO_BUSY_POLL: Integer

Socket::SO_DEBUG: Integer

Socket::SO_DETACH_FILTER: Integer

Socket::SO_DOMAIN: Integer

Socket::SO_DONTROUTE: Integer

Socket::SO_DONTTRUNC: Integer

Socket::SO_ERROR: Integer

Socket::SO_GET_FILTER: Integer

Socket::SO_INCOMING_CPU: Integer

Socket::SO_INCOMING_NAPI_ID: Integer

Socket::SO_KEEPALIVE: Integer

Socket::SO_LINGER: Integer

Socket::SO_LOCK_FILTER: Integer

Socket::SO_MAC_EXEMPT: Integer

Socket::SO_MARK: Integer

Socket::SO_MAX_PACING_RATE: Integer

Socket::SO_NKE: Integer

Socket::SO_NOFCS: Integer

Socket::SO_NOSIGPIPE: Integer

Socket::SO_NO_CHECK: Integer

Socket::SO_NREAD: Integer

Socket::SO_OOBINLINE: Integer

Socket::SO_PASSCRED: Integer

Socket::SO_PASSSEC: Integer

Socket::SO_PEEK_OFF: Integer

Socket::SO_PEERCRED: Integer

Socket::SO_PEERNAME: Integer

Socket::SO_PEERSEC: Integer

Socket::SO_PRIORITY: Integer

Socket::SO_PROTOCOL: Integer

Socket::SO_RCVBUF: Integer

Socket::SO_RCVBUFFORCE: Integer

Socket::SO_RCVLOWAT: Integer

Socket::SO_RCVTIMEO: Integer

Socket::SO_RECVUCRED: Integer

Socket::SO_REUSEADDR: Integer

Socket::SO_REUSEPORT: Integer

Socket::SO_RTABLE: Integer

Socket::SO_RXQ_OVFL: Integer
Socket::SO_SECURITY_AUTHENTICATION: Integer
Socket::SO_SECURITY_ENCRYPTION_NETWORK: Integer
Socket::SO_SECURITY_ENCRYPTION_TRANSPORT: Integer

Socket::SO_SELECT_ERR_QUEUE: Integer

Socket::SO_SETFIB: Integer

Socket::SO_SNDBUF: Integer

Socket::SO_SNDBUFFORCE: Integer

Socket::SO_SNDLOWAT: Integer

Socket::SO_SNDTIMEO: Integer

Socket::SO_TIMESTAMP: Integer

Socket::SO_TIMESTAMPING: Integer

Socket::SO_TIMESTAMPNS: Integer

Socket::SO_TYPE: Integer

Socket::SO_USELOOPBACK: Integer

Socket::SO_USER_COOKIE: Integer

Socket::SO_WANTMORE: Integer

Socket::SO_WANTOOBFLAG: Integer

Socket::SO_WIFI_STATUS: Integer

Socket::TCP_CONNECTION_INFO: Integer

Socket::TCP_CONGESTION: Integer

Socket::TCP_COOKIE_TRANSACTIONS: Integer

Socket::TCP_CORK: Integer

Socket::TCP_DEFER_ACCEPT: Integer

Socket::TCP_FASTOPEN: Integer

Socket::TCP_INFO: Integer

Socket::TCP_KEEPALIVE: Integer

Socket::TCP_KEEPCNT: Integer

Socket::TCP_KEEPIDLE: Integer

Socket::TCP_KEEPINTVL: Integer

Socket::TCP_LINGER2: Integer

Socket::TCP_MAXSEG: Integer

Socket::TCP_MD5SIG: Integer

Socket::TCP_NODELAY: Integer

Socket::TCP_NOOPT: Integer

Socket::TCP_NOPUSH: Integer

Socket::TCP_QUEUE_SEQ: Integer

Socket::TCP_QUICKACK: Integer

Socket::TCP_REPAIR: Integer

Socket::TCP_REPAIR_OPTIONS: Integer

Socket::TCP_REPAIR_QUEUE: Integer

Socket::TCP_SYNCNT: Integer

Socket::TCP_THIN_DUPACK: Integer

Socket::TCP_THIN_LINEAR_TIMEOUTS: Integer

Socket::TCP_TIMESTAMP: Integer

Socket::TCP_USER_TIMEOUT: Integer

Socket::TCP_WINDOW_CLAMP: Integer

Socket::UDP_CORK: Integer

class Socket::Ifaddr
  def addr: () -> Addrinfo?

  def broadaddr: () -> Addrinfo?

  def dstaddr: () -> Addrinfo?

  def flags: () -> Integer

  def ifindex: () -> Integer

  def inspect: () -> String

  def name: () -> String

  def netmask: () -> Addrinfo?
end

class Socket::UDPSource
  def inspect: () -> String

  def local_address: () -> Addrinfo

  def remote_address: () -> Addrinfo

  def reply: (String msg) -> void

  private

  def initialize: (Addrinfo remote_address, Addrinfo local_address) { (String) -> void } -> void
end

class Socket::AncillaryData
  def self.int: (Symbol, Symbol, Symbol, Symbol) -> instance

  def self.ip_pktinfo: (Addrinfo addr, Integer ifindex, ?Addrinfo spec_dst) -> instance

  def self.ipv6_pktinfo: (Addrinfo addr, Integer ifindex) -> instance

  def self.unix_rights: (IO fd) -> instance

  def cmsg_is?: (Integer level, Integer ancillary_type) -> bool

  def data: () -> String

  def family: () -> Integer

  def inspect: () -> String

  def int: () -> Integer

  def ip_pktinfo: () -> [ Addrinfo, Integer, Addrinfo ]

  def ipv6_pktinfo: () -> [ Addrinfo, Integer ]

  def ipv6_pktinfo_addr: () -> Addrinfo

  def ipv6_pktinfo_ifindex: () -> Integer

  def level: () -> Integer

  def timestamp: () -> Time

  def type: () -> Integer

  def unix_rights: () -> Array[IO]?

  private

  def initialize: (interned | Integer family, interned | Integer cmsg_level, interned | Integer cmsg_data, String cmsg_data) -> untyped
end
