class TCPServer < TCPSocket
  def accept: () -> TCPSocket

  def accept_nonblock: (?exception: boolish) -> (TCPSocket | :wait_readable)

  def listen: (Integer backlog) -> void

  def sysaccept: () -> Integer

  private

  def __accept_nonblock: (untyped) -> untyped

  def initialize: (?String host, Integer port) -> untyped
end
