class UDPSocket < IPSocket
  def bind: (String host, Integer port) -> void

  def connect: (String host, Integer port) -> void

  def recvfrom_nonblock: (Integer len, ?Integer flag, ?String outbuf, ?exception: boolish) -> [ String, [ String, Integer, String, String ] ]

  def send: (String msg, ?Integer flags, ?String host, ?Integer port) -> Integer

  private

  def __recvfrom_nonblock: (untyped, untyped, untyped, untyped) -> untyped

  def initialize: (?Integer family) -> untyped
end
