class UNIXSocket < BasicSocket
  def self.pair: (?Symbol socktype, ?Integer protocol) -> [ instance, instance ]

  def self.socketpair: (?Symbol socktype, ?Integer protocol) -> [ instance, instance ]

  def addr: () -> [ String, String ]

  def path: () -> String

  def peeraddr: () -> [ String, String ]

  def recv_io: () -> IO
             | (singleton(Integer)?) -> Integer
             | [T] (IO::_ForFd[T], ?untyped mode) -> T

  def recvfrom: (Integer maxlen, ?Integer flags, ?String outbuf) -> [ String, [ String, String ] ]

  def send_io: (IO | Integer) -> void

  private

  def initialize: (String path) -> untyped
end
