class UNIXServer < UNIXSocket
  def accept: () -> UNIXSocket

  def accept_nonblock: (?exception: boolish) -> (UNIXSocket | :wait_readable)

  def listen: (Integer backlog) -> void

  def sysaccept: () -> Integer

  private

  def __accept_nonblock: (untyped) -> untyped

  def initialize: (untyped) -> untyped
end
