class StringIO
  def initialize: (?String string, ?String? mode) -> void

  def self.open: [U] (?String string, ?String? mode) { (StringIO arg) -> U } -> U

  def <<: (untyped arg0) -> self

  def binmode: () -> self

  def close: () -> nil

  def close_read: () -> nil

  def close_write: () -> nil

  def closed?: () -> bool

  def closed_read?: () -> bool

  def closed_write?: () -> bool

  def each: (?String sep, ?Integer limit, ?chomp: boolish) { (String) -> untyped } -> self
          | (?String sep, ?Integer limit, ?chomp: boolish) -> ::Enumerator[String, self]

  def each_byte: () { (Integer arg0) -> untyped } -> self
               | () -> ::Enumerator[Integer, self]

  def each_char: () { (String arg0) -> untyped } -> self
               | () -> ::Enumerator[String, self]

  def each_codepoint: () { (Integer arg0) -> untyped } -> self
                    | () -> ::Enumerator[Integer, self]

  def eof: () -> bool

  def fcntl: (Integer integer_cmd, String | Integer arg) -> Integer

  def fileno: () -> nil

  def flush: () -> self

  def fsync: () -> Integer?

  def getbyte: () -> Integer?

  def getc: () -> String?

  def gets: (?String sep, ?Integer limit, ?chomp: boolish) -> String?

  def internal_encoding: () -> Encoding

  def external_encoding: () -> Encoding

  def isatty: () -> bool

  def lineno: () -> Integer

  def lineno=: (Integer arg0) -> Integer

  def pid: () -> nil

  def pos: () -> Integer

  def pos=: (Integer arg0) -> Integer

  def print: (*untyped arg0) -> nil

  def printf: (String format_string, *untyped arg0) -> nil

  def putc: (Numeric | String arg0) -> untyped

  def puts: (*untyped arg0) -> nil

  def read: (?int? length, ?string outbuf) -> String?

  def read_nonblock: (int len, ?string buf) -> String

  def readbyte: () -> Integer

  def readchar: () -> String

  def readline: (?String sep, ?Integer limit, ?chomp: boolish) -> String

  def readlines: (?String sep, ?Integer limit, ?chomp: boolish) -> ::Array[String]

  def readpartial: (int maxlen, ?string outbuf) -> String

  def reopen: (StringIO other) -> self
            | (String other, ?String mode_str) -> self

  def rewind: () -> Integer

  def seek: (Integer amount, ?Integer whence) -> Integer

  def set_encoding: (?String | Encoding ext_or_ext_int_enc) -> self
                  | (?String | Encoding ext_or_ext_int_enc, ?String | Encoding int_enc) -> self

  def string: () -> String

  def string=: (String str) -> String

  def size: () -> Integer

  def sync: () -> bool

  def sync=: (boolish) -> bool

  def sysread: (Integer maxlen, String outbuf) -> String

  def syswrite: (String arg0) -> Integer

  def tell: () -> Integer

  def truncate: (Integer) -> 0

  def tty?: () -> bool

  def ungetbyte: (String | Integer arg0) -> nil

  def ungetc: (String arg0) -> nil

  def write: (*_ToS) -> Integer

  def bytes: () { (Integer arg0) -> untyped } -> self
           | () -> ::Enumerator[Integer, self]

  def chars: () { (String arg0) -> untyped } -> self
           | () -> ::Enumerator[String, self]

  def codepoints: () { (Integer arg0) -> untyped } -> self
                | () -> ::Enumerator[Integer, self]

  def each_line: (?String sep, ?Integer limit, ?chomp: boolish) { (String) -> untyped } -> self
               | (?String sep, ?Integer limit, ?chomp: boolish) -> ::Enumerator[String, self]

  def eof?: () -> bool

  def lines: (?String sep, ?Integer limit) { (String arg0) -> untyped } -> self
           | (?String sep, ?Integer limit) -> ::Enumerator[String, self]
end
