%a{annotate:rdoc:skip}
module ObjectSpace
  class WeakKeyMap[Key, Value]
    def []: (Key) -> Value?

    def []=: (Key, Value?) -> Value?

    def clear: () -> self

    def delete: (Key) -> Value?
              | [T] (Key) { (Key) -> T } -> (Value | T)

    def getkey: (untyped) -> Key?

    def inspect: () -> String

    def key?: (Key) -> bool
  end
end
