class IPAddr
  include Comparable

  def self.new_ntoh: (String addr) -> IPAddr

  def self.ntop: (String addr) -> String

  def initialize: (?String addr, ?untyped family) -> void

  def &: (untyped other) -> IPAddr

  def <<: (Integer num) -> IPAddr

  def <=>: (untyped other) -> Integer?

  def ==: (untyped other) -> bool

  alias === include?

  def >>: (Integer num) -> IPAddr

  def eql?: (untyped other) -> bool

  attr_reader family: Integer

  def hash: () -> Integer

  def hton: () -> String

  def include?: (untyped other) -> bool

  def inspect: () -> String

  def ip6_arpa: () -> String

  def ip6_int: () -> String

  def ipv4?: () -> bool

  def ipv4_compat: () -> IPAddr

  def ipv4_compat?: () -> bool

  def ipv4_mapped: () -> IPAddr

  def ipv4_mapped?: () -> bool

  def ipv6?: () -> bool

  def link_local?: () -> bool

  def loopback?: () -> bool

  def mask: (String | Integer prefixlen) -> IPAddr

  def native: () -> IPAddr

  def netmask: () -> String

  def prefix: () -> Integer

  def prefix=: (Integer prefix) -> self

  def private?: () -> bool

  def reverse: () -> String

  def succ: () -> IPAddr

  def to_i: () -> Integer

  def to_range: () -> Range[IPAddr]

  def to_s: () -> String

  def to_string: () -> String

  def |: (untyped other) -> IPAddr

  def ~: () -> IPAddr
end

class IPAddr::Error < ArgumentError
end

class IPAddr::InvalidAddressError < IPAddr::Error
end

class IPAddr::AddressFamilyError < IPAddr::Error
end

class IPAddr::InvalidPrefixError < IPAddr::InvalidAddressError
end

IPAddr::IN4MASK: Integer

IPAddr::IN6FORMAT: String

IPAddr::IN6MASK: Integer

IPAddr::RE_IPV4ADDRLIKE: Regexp

IPAddr::RE_IPV6ADDRLIKE_COMPRESSED: Regexp

IPAddr::RE_IPV6ADDRLIKE_FULL: Regexp
