%a{annotate:rdoc:skip}
module URI
  class File < Generic
    DEFAULT_PORT: Integer?

    COMPONENT: Array[Symbol]

    def self.build: (Array[String] args) -> URI::File
                  | ({ host: String?, path: String? }) -> URI::File

    def set_host: (String? v) -> String

    def set_port: (Integer v) -> nil

    def check_userinfo: (String user) -> nil

    def check_user: (String user) -> nil

    def check_password: (String user) -> nil

    def set_userinfo: (String v) -> nil

    def set_user: (String v) -> nil

    def set_password: (String v) -> nil
  end
end
