module URI
  class Generic
    include URI

    DEFAULT_PORT: nil | Integer

    def self.default_port: () -> (nil | Integer)

    def default_port: () -> (nil | Integer)

    COMPONENT: Array[Symbol]

    def self.component: () -> Array[Symbol]

    USE_REGISTRY: bool

    def self.use_registry: () -> bool

    def self.build2: (Array[nil | String | Integer]) -> URI::Generic
                   | ({ scheme: String?, userinfo: String?, host: String?, port: Integer?, registry: String?, path: String?, opaque: String?, query: String?, fragment: String? }) -> instance

    def self.build: (Array[nil | String | Integer]) -> URI::Generic
                  | ({ scheme: String?, userinfo: String?, host: String?, port: Integer?, registry: String?, path: String?, opaque: String?, query: String?, fragment: String? }) -> instance

    def initialize: (String? scheme, String? userinfo, String? host, (String | Integer)? port, nil registry, String? path, String? opaque, String? query, String? fragment, ?untyped parser, ?boolish arg_check) -> void

    attr_reader scheme: String?

    attr_reader host: String?

    attr_reader port: Integer?

    def registry: () -> nil

    attr_reader path: String?

    attr_reader query: String?

    attr_reader opaque: String?

    attr_reader fragment: String?

    def parser: () -> untyped

    def replace!: (URI::Generic oth) -> URI::Generic

    def component: () -> Array[Symbol]

    def check_scheme: (String? v) -> true

    def set_scheme: (String? v) -> String?

    def scheme=: (String? v) -> String?

    def check_userinfo: (String user, ?String? password) -> true

    def check_user: (String v) -> (String | true)

    def check_password: (String? v, ?String user) -> (String? | true)

    def userinfo=: (String? userinfo) -> String?

    def user=: (String? user) -> String?

    def password=: (String? password) -> String?

    def set_userinfo: (String? user, ?String? password) -> [ String?, String? ]

    def set_user: (String? v) -> String?

    def set_password: (String? v) -> String?

    def split_userinfo: (String ui) -> Array[String | nil]

    def escape_userpass: (String v) -> String

    def userinfo: () -> String?

    def user: () -> String?

    def password: () -> String?

    def check_host: (String? v) -> true?

    def set_host: (String? v) -> String?

    def host=: (String? v) -> String?

    def hostname: () -> String?

    def hostname=: (String? v) -> String?

    def check_port: ((String | Integer)? v) -> true?

    def set_port: ((String | Integer)? v) -> (String | Integer)?

    def port=: ((String | Integer)? v) -> (String | Integer)?

    def check_registry: (String v) -> nil

    def set_registry: (String v) -> nil

    def registry=: (String v) -> nil

    def check_path: (String? v) -> true

    def set_path: (String? v) -> String?

    def path=: (String? v) -> String?

    def query=: (String? v) -> String?

    def check_opaque: (String? v) -> true?

    def set_opaque: (String? v) -> String?

    def opaque=: (String? v) -> String?

    def fragment=: (String? v) -> String?

    def hierarchical?: () -> bool

    def absolute?: () -> bool

    def relative?: () -> bool

    def split_path: (String path) -> Array[String]

    def merge_path: (String base, String rel) -> String

    def merge!: (URI::Generic | string oth) -> String

    def merge: (URI::Generic | string oth) -> URI::Generic

    alias + merge

    def route_from_path: (String src, String dst) -> String

    def route_from0: (String oth) -> Array[URI::Generic]

    def route_from: (String oth) -> URI::Generic

    def route_to: (String oth) -> URI::Generic

    def normalize: () -> untyped

    def normalize!: () -> untyped

    def to_s: () -> String

    def ==: (URI::Generic oth) -> bool

    def hash: () -> Integer

    def eql?: (URI::Generic oth) -> bool

    def component_ary: () -> Array[nil | String | Integer]

    def select: (*Symbol components) -> Array[nil | String | Integer]

    def inspect: () -> String

    def coerce: (URI::Generic | String oth) -> Array[URI::Generic]

    def find_proxy: (?String env) -> (nil | URI::Generic)

    def self.use_proxy?: (String hostname, String addr, Integer port, String no_proxy) -> bool
  end
end
