%a{annotate:rdoc:skip}
module URI
  class HTTP < Generic
    DEFAULT_PORT: Integer

    COMPONENT: Array[Symbol]

    def self.build: (Array[String | Integer] args) -> instance
                  | ({ userinfo: String?, host: String?, port: Integer?, path: String?, query: String?, fragment: String? }) -> instance

    def authority: () -> String

    def origin: () -> String

    def request_uri: () -> String
  end
end
