%a{annotate:rdoc:skip}
module URI
  class LDAP < Generic
    DEFAULT_PORT: Integer

    COMPONENT: Array[Symbol]

    SCOPE: Array[String]

    def self.build: (Array[nil | String | Integer] args) -> URI::LDAP
                  | ({ host: String?, port: Integer?, dn: String?, attributes: String?, scope: String?, filter: String?, extensions: String? }) -> URI::LDAP

    def initialize: (String schema, String? userinfo, String host, Integer? port, String? registry, String? path, String? opaque, String query, String? fragment) -> void

    def parse_dn: () -> nil

    def parse_query: () -> nil

    def build_path_query: () -> String

    def dn: () -> String

    def set_dn: (String val) -> String

    def dn=: (String val) -> String

    def attributes: () -> String

    def set_attributes: (String val) -> String

    def attributes=: (String val) -> String

    def scope: () -> String

    def set_scope: (String val) -> String

    def scope=: (String val) -> String

    def filter: () -> String

    def set_filter: (String val) -> String

    def filter=: (String val) -> String

    def extensions: () -> untyped

    def set_extensions: (String val) -> String

    def extensions=: (String val) -> String

    def hierarchical?: () -> ::FalseClass
  end
end
