%a{annotate:rdoc:skip}
module URI
  class MailTo < Generic
    EMAIL_REGEXP: Regexp

    def self.build: (Array[String]) -> instance
                  | ([String, Array[Array[String]]]) -> instance
                  | (Hash[Symbol, String | Array[Array[String]]]) -> instance

    def headers: () -> Array[[String, String]]

    def headers=: (String) -> String

    def to: () -> String

    def to=: (String) -> String

    def to_mailtext: () -> String

    def to_rfc822text: () -> String
  end
end
