%a{annotate:rdoc:skip}
module URI
  module RFC2396_REGEXP
  end

  class RFC2396_Parser
    include RFC2396_REGEXP

    attr_reader pattern: Hash[Symbol, String]

    attr_reader regexp: Hash[Symbol, Regexp]

    def initialize: (?Hash[Symbol, String] opts) -> void

    def escape: (String str, ?Regexp unsafe) -> String

    def extract: (String str, ?Array[String] schemes) -> Array[String]
               | (String str, ?Array[String] schemes) { (String) -> untyped } -> nil

    def join: (*String uris) -> URI::Generic

    def make_regexp: (?Array[String] schemes) -> Regexp

    def parse: (String uri) -> URI::Generic

    def split: (String uri) -> [ String?, String?, String?, String?, String?, String?, String?, String?, String? ]

    def unescape: (String str, ?Regexp escaped) -> String
  end
end
