module DidYouMean
  NameErrorCheckers: Object

  VERSION: String

  class ClassNameChecker
    class ClassName < ::String
    end
  end

  module Correctable
    SKIP_TO_S_FOR_SUPER_LOOKUP: true

    def corrections: () -> Array[String]
  end

  class Formatter
    def self.message_for: (Array[String] corrections) -> String
  end

  module JaroWinkler
    WEIGHT: Float

    THRESHOLD: Float

    def self?.distance: (String, String) -> Integer
  end

  module Jaro
    def self?.distance: (String, String) -> Integer
  end

  class KeyErrorChecker
    def initialize: (KeyError[_ToS, Hash[_ToS, untyped]]) -> void

    def corrections: () -> Array[String]
  end

  module Levenshtein
    def self?.distance: (String, String) -> Integer?
  end

  class MethodNameChecker
    NAMES_TO_EXCLUDE: Hash[untyped, Array[Symbol]]

    RB_RESERVED_WORDS: Array[Symbol]

    def initialize: (NoMethodError[untyped] exception) -> void

    def corrections: () -> Array[Symbol]
  end

  class NullChecker
    def initialize: (*untyped) -> void

    def corrections: () -> Array[untyped]
  end

  class PatternKeyNameChecker
    def initialize: (untyped) -> void

    def corrections: () -> Array[String]
  end

  class RequirePathChecker
    INITIAL_LOAD_PATH: Array[String]
    ENV_SPECIFIC_EXT: String

    def self.requireables: () -> Array[String]

    def initialize: (untyped exception) -> void

    def corrections: () -> Array[String]
  end

  class SpellChecker
    def initialize: (dictionary: Array[interned]) -> void

    def correct: (interned input) -> Array[String]
  end

  class TreeSpellChecker
    def initialize: (dictionary: Array[String], ?separator: String, ?augment: bool?) -> void

    def correct: (String input) -> Array[String]
  end

  class VariableNameChecker
    NAMES_TO_EXCLUDE: Hash[String, Array[Symbol]]

    RB_RESERVED_WORDS: Array[Symbol]

    def initialize: (NameError[untyped]) -> void

    def corrections: () -> Array[Symbol]
  end
end

%a{annotate:rdoc:skip}
class NameError[T]
  prepend DidYouMean::Correctable
end

%a{annotate:rdoc:skip}
class KeyError[K, R]
  prepend DidYouMean::Correctable
end

%a{annotate:rdoc:skip}
class LoadError
  prepend DidYouMean::Correctable
end
