%a{annotate:rdoc:skip}
module Gem
  class Requirement
    type operator = "=" | "!=" | ">" | "<" | ">=" | "<=" | "~>"

    class BadRequirementError < ArgumentError
    end

    DefaultPrereleaseRequirement: [ operator, Gem::Version ]

    DefaultRequirement: [ operator, Gem::Version ]

    PATTERN: Regexp

    def self.create: (*String | Gem::Version | Gem::Requirement | nil inputs) -> instance

    def self.default: () -> instance

    def self.default_prerelease: () -> instance

    def self.parse: (String | Gem::Version obj) -> [ operator, Gem::Version ]

    def initialize: (*String | Gem::Version requirements) -> void

    def concat: (Array[String | Gem::Version] new) -> void

    def exact?: () -> bool

    def none?: () -> bool

    def prerelease?: () -> bool

    def satisfied_by?: (Gem::Version version) -> bool

    alias === satisfied_by?

    alias =~ satisfied_by?

    def specific?: () -> bool
  end
end
