module Gem
  interface _HashLike[K, V]
    def each_pair: () { ([ K, V ]) -> untyped } -> self
  end

  DEFAULT_HOST: String

  GEM_DEP_FILES: Array[String]

  KERNEL_WARN_IGNORES_INTERNAL_ENTRIES: bool

  LOADED_SPECS_MUTEX: Thread::Mutex

  MARSHAL_SPEC_DIR: String

  READ_BINARY_ERRORS: Array[Class]

  REPOSITORY_DEFAULT_GEM_SUBDIRECTORIES: Array[String]

  REPOSITORY_SUBDIRECTORIES: Array[String]

  RUBYGEMS_DIR: String

  UNTAINT: Proc

  VERSION: String

  WIN_PATTERNS: Array[Regexp]

  WRITE_BINARY_ERRORS: Array[Class]

  def self.activated_gem_paths: () -> Integer

  def self.add_to_load_path: (*String paths) -> Array[String]

  def self.bin_path: (String name, String exec_name, ?Array[Requirement] requirements) -> String

  def self.binary_mode: () -> String

  def self.bindir: (?String install_dir) -> String

  def self.cache_home: () -> String

  def self.clear_default_specs: () -> void

  def self.clear_paths: () -> void

  def self.config_file: () -> String

  def self.config_home: () -> String

  def self.configuration: () -> ConfigFile

  def self.configuration=: (ConfigFile config) -> ConfigFile

  def self.data_home: () -> String

  def self.default_bindir: () -> String

  def self.default_cert_path: () -> String

  def self.default_dir: () -> String

  def self.default_exec_format: () -> String

  def self.default_ext_dir_for: (String base_dir) -> String?

  def self.default_key_path: () -> String

  def self.default_path: () -> Array[String]

  def self.default_rubygems_dirs: () -> Array[String]?

  def self.default_sources: () -> Array[String]

  def self.default_spec_cache_dir: () -> String

  def self.default_specifications_dir: () -> String

  def self.deflate: (String data) -> String

  def self.dir: () -> String

  def self.disable_system_update_message: () -> String?

  def self.disable_system_update_message=: (String?) -> String?

  def self.done_installing: () { (DependencyInstaller, Array[Specification]) -> untyped } -> Array[Proc]

  def self.done_installing_hooks: () -> Array[Proc?]

  def self.ensure_default_gem_subdirectories: (?String dir, ?Integer | String mode) -> Array[String]

  def self.ensure_gem_subdirectories: (?String dir, ?Integer | String mode) -> Array[String]

  def self.env_requirement: (String gem_name) -> Requirement

  def self.find_config_file: () -> String

  def self.find_files: (String glob, ?boolish check_load_path) -> Array[String]

  def self.find_latest_files: (String glob, ?boolish check_load_path) -> Array[String]

  def self.find_unresolved_default_spec: (String path) -> Specification?

  def self.finish_resolve: (?RequestSet request_set) -> void

  def self.gemdeps: () -> RequestSet::GemDependencyAPI?

  def self.host: () -> String

  def self.host=: (String host) -> String

  def self.install: (String name, ?Gem::Requirement version, *DependencyInstaller::options options) -> Array[Specification]

  def self.java_platform?: () -> bool

  def self.latest_rubygems_version: () -> Version

  def self.latest_spec_for: (String name) -> Specification?

  def self.latest_version_for: (String name) -> Version?

  def self.load_env_plugins: () -> Array[String]

  def self.load_path_insert_index: () -> Integer

  def self.load_plugins: () -> Array[String]

  def self.load_yaml: () -> bool?

  def self.loaded_specs: () -> Hash[String, BasicSpecification]

  def self.location_of_caller: (?Integer depth) -> [ String, Integer ]

  def self.marshal_version: () -> String

  def self.needs: () { (RequestSet) -> void } -> void

  def self.operating_system_defaults: () -> Hash[String, String]

  def self.path: () -> Array[String]

  def self.path_separator: () -> String

  def self.paths: () -> PathSupport

  def self.paths=: (_HashLike[String, String?] env) -> Array[String]

  def self.platform_defaults: () -> Hash[String, String]

  def self.platforms: () -> Array[String | Platform]

  def self.platforms=: (Array[String | Platform] platforms) -> Array[String | Platform]

  def self.plugin_suffix_pattern: () -> String

  def self.plugin_suffix_regexp: () -> Regexp

  def self.plugindir: (?String install_dir) -> String

  def self.post_build: () { (Installer) -> untyped } -> Array[Proc]

  def self.post_build_hooks: () -> Array[Proc]

  def self.post_install: () { (Installer) -> untyped } -> Array[Proc]

  def self.post_install_hooks: () -> Array[Proc]

  def self.post_reset: () { () -> untyped } -> Array[Proc]

  def self.post_reset_hooks: () -> Array[Proc?]

  def self.post_uninstall: () { (Uninstaller) -> untyped } -> Array[Proc]

  def self.post_uninstall_hooks: () -> Array[Proc?]

  def self.pre_install: () { (Installer) -> untyped } -> Array[Proc]

  def self.pre_install_hooks: () -> Array[Proc?]

  def self.pre_reset: () { () -> untyped } -> Array[Proc]

  def self.pre_reset_hooks: () -> Array[Proc?]

  def self.pre_uninstall: () { (Uninstaller) -> untyped } -> Array[Proc]

  def self.pre_uninstall_hooks: () -> Array[Proc?]

  def self.prefix: () -> String?

  def self.read_binary: (String path) -> String

  def self.refresh: () -> Array[Proc]

  def self.register_default_spec: (Specification spec) -> Array[String]

  def self.ruby: () -> String

  def self.ruby_api_version: () -> String

  def self.ruby_engine: () -> String

  def self.ruby_version: () -> Version

  def self.rubygems_version: () -> Version

  def self.source_date_epoch: () -> Time

  def self.source_date_epoch_string: () -> String

  def self.sources: () -> SourceList

  def self.sources=: (SourceList? new_sources) -> SourceList?

  def self.spec_cache_dir: () -> String

  def self.suffix_pattern: () -> String

  def self.suffix_regexp: () -> Regexp

  def self.suffixes: () -> Array[String]

  def self.time: [T] (String msg, ?Integer width, ?boolish display) { () -> T } -> T

  def self.try_activate: (String path) -> bool

  def self.ui: () -> StreamUI

  def self.use_gemdeps: (?String path) -> void

  def self.use_paths: (String home, *String paths) -> Hash[String, String]

  def self.user_dir: () -> String

  def self.user_home: () -> String

  def self.win_platform?: () -> bool

  def self.write_binary: (String path, String data) -> Integer
end
