%a{annotate:rdoc:skip}
module Gem
  class Version
    include Comparable

    def self.correct?: (_ToS version) -> bool

    def self.create: (_ToS | Version input) -> instance
                   | (nil input) -> nil

    def initialize: (_ToS version) -> void

    def <=>: (untyped other) -> Integer?

    def approximate_recommendation: () -> String

    def bump: () -> self

    def canonical_segments: () -> Array[Integer | String]

    def eql?: (untyped other) -> bool

    def marshal_dump: () -> Array[String]

    def marshal_load: (Array[String] array) -> void

    def prerelease?: () -> bool

    def release: () -> self

    def version: () -> String

    alias to_s version
  end
end
