class CGI
  include Escape

  extend Escape

  module Escape
    def escape: (string str) -> String

    def escapeElement: (string string, *String | Array[String] elements) -> String

    def escapeHTML: (string str) -> String

    def escapeURIComponent: (string) -> String

    alias escape_element escapeElement

    alias escape_html escapeHTML

    alias escape_uri_component escapeURIComponent

    alias h escapeHTML

    def unescape: (string str, ?encoding encoding) -> String

    def unescapeElement: (string string, *String | Array[String] elements) -> String

    def unescapeHTML: (string str) -> String

    def unescapeURIComponent: (string) -> String

    alias unescape_element unescapeElement

    alias unescape_html unescapeHTML

    alias unescape_uri_component unescapeURIComponent
  end
end
