#!/usr/bin/env python3
"""
Find entry points across different project types.
Usage: python find-entry-points.py --directory ./src
"""

import os
import sys
import argparse
from pathlib import Path
from typing import List, Dict

# Common entry point patterns by project type
ENTRY_POINT_PATTERNS = {
    'node': ['index.js', 'index.ts', 'main.js', 'main.ts', 'server.js', 'server.ts', 'app.js', 'app.ts'],
    'python': ['__main__.py', 'main.py', 'app.py', 'cli.py', 'run.py'],
    'go': ['main.go', 'cmd/main.go'],
    'rust': ['main.rs', 'lib.rs'],
    'java': ['Main.java', 'Application.java'],
    'web': ['index.html', 'App.tsx', 'App.jsx'],
}

def find_entry_points(directory: Path) -> Dict[str, List[Path]]:
    """Find all potential entry points in the directory."""
    found_entries = {}

    for project_type, patterns in ENTRY_POINT_PATTERNS.items():
        found = []
        for pattern in patterns:
            # Search recursively
            matches = list(directory.rglob(pattern))
            found.extend(matches)

        if found:
            found_entries[project_type] = found

    return found_entries

def detect_build_scripts(directory: Path) -> List[Path]:
    """Find build and run scripts."""
    build_files = []

    # Check package.json scripts
    package_json = directory / 'package.json'
    if package_json.exists():
        build_files.append(package_json)

    # Check for Makefile
    makefile = directory / 'Makefile'
    if makefile.exists():
        build_files.append(makefile)

    # Check for build scripts
    for build_script in ['build.sh', 'run.sh', 'start.sh']:
        script = directory / build_script
        if script.exists():
            build_files.append(script)

    return build_files

def main():
    parser = argparse.ArgumentParser(description='Find entry points in a project')
    parser.add_argument('--directory', default='.', help='Directory to search')
    args = parser.parse_args()

    directory = Path(args.directory).resolve()

    if not directory.exists():
        print(f"Error: Directory '{directory}' does not exist", file=sys.stderr)
        sys.exit(1)

    print(f"# Entry Point Analysis")
    print(f"Project: {directory.name}")
    print(f"Path: {directory}")
    print()

    # Find entry points
    entry_points = find_entry_points(directory)

    if entry_points:
        print("## Entry Points Found")
        print()
        for project_type, files in entry_points.items():
            print(f"### {project_type.upper()}")
            for file in files:
                rel_path = file.relative_to(directory)
                print(f"- `{rel_path}`")
            print()
    else:
        print("## No Entry Points Found")
        print("Common entry point patterns not detected.")
        print()

    # Find build scripts
    build_scripts = detect_build_scripts(directory)
    if build_scripts:
        print("## Build/Run Scripts")
        print()
        for script in build_scripts:
            rel_path = script.relative_to(directory)
            print(f"- `{rel_path}`")
        print()

    print("---")
    print("Generated by research-agent/investigating-codebases")

if __name__ == '__main__':
    main()
