#!/usr/bin/env bash
# Map directory structure with key files highlighted
# Usage: bash map-structure.sh /path/to/project

set -euo pipefail

PROJECT_DIR="${1:-.}"

echo "# Project Structure Analysis"
echo "Project: $(basename "$PROJECT_DIR")"
echo "Path: $(realpath "$PROJECT_DIR")"
echo ""

# Check if tree command is available
if command -v tree &> /dev/null; then
    echo "## Directory Tree (3 levels deep)"
    tree -L 3 -d "$PROJECT_DIR" 2>/dev/null || echo "Error reading directory structure"
else
    echo "## Directory Structure (tree command not available)"
    find "$PROJECT_DIR" -maxdepth 3 -type d 2>/dev/null | head -50
fi

echo ""
echo "## Key Files Detected"

# Look for common entry points and configuration files
echo ""
echo "### Entry Points:"
find "$PROJECT_DIR" -maxdepth 2 -type f \( \
    -name "index.js" -o \
    -name "index.ts" -o \
    -name "main.py" -o \
    -name "main.go" -o \
    -name "app.py" -o \
    -name "server.js" -o \
    -name "server.ts" \
\) 2>/dev/null | sed "s|^$PROJECT_DIR/|- |"

echo ""
echo "### Configuration Files:"
find "$PROJECT_DIR" -maxdepth 2 -type f \( \
    -name "package.json" -o \
    -name "tsconfig.json" -o \
    -name "Cargo.toml" -o \
    -name "setup.py" -o \
    -name "requirements.txt" -o \
    -name "go.mod" \
\) 2>/dev/null | sed "s|^$PROJECT_DIR/|- |"

echo ""
echo "### Build/Deploy Files:"
find "$PROJECT_DIR" -maxdepth 2 -type f \( \
    -name "Dockerfile" -o \
    -name "docker-compose.yml" -o \
    -name "Makefile" -o \
    -name "webpack.config.js" -o \
    -name "vite.config.ts" \
\) 2>/dev/null | sed "s|^$PROJECT_DIR/|- |"

echo ""
echo "## File Count by Type"
echo "TypeScript: $(find "$PROJECT_DIR" -type f -name "*.ts" 2>/dev/null | wc -l)"
echo "JavaScript: $(find "$PROJECT_DIR" -type f -name "*.js" 2>/dev/null | wc -l)"
echo "Python:     $(find "$PROJECT_DIR" -type f -name "*.py" 2>/dev/null | wc -l)"
echo "Go:         $(find "$PROJECT_DIR" -type f -name "*.go" 2>/dev/null | wc -l)"
echo "Rust:       $(find "$PROJECT_DIR" -type f -name "*.rs" 2>/dev/null | wc -l)"

echo ""
echo "---"
echo "Generated by research-agent/investigating-codebases"
