module Minitest::Spec::DSL
  @children: untyped

  @specs: untyped

  def register_spec_type: (*untyped args) ?{ (?) -> untyped } -> untyped

  def spec_type: (untyped desc, *untyped additional) -> untyped

  def describe_stack: () -> untyped

  def children: () -> untyped

  def nuke_test_methods!: () -> untyped

  def before: (?untyped? _type) { (?) -> untyped } -> untyped

  def after: (?untyped? _type) { (?) -> untyped } -> untyped

  def it: (?::String desc) ?{ (?) -> untyped } -> untyped

  def let: (untyped name) { (?) -> untyped } -> untyped

  def subject: () { (?) -> untyped } -> untyped

  def create: (untyped name, untyped desc) -> untyped

  def name: () -> untyped

  def to_s: () -> untyped

  alias specify it

  def self.extended: (untyped obj) -> untyped

  attr_reader desc: untyped

  TYPES: Array[Array[Regexp | singleton(Minitest::BenchSpec)] | Array[Regexp | singleton(Minitest::Spec)]]
end
