module BigMath
  def self?.E: (Numeric prec) -> BigDecimal

  def self?.PI: (Numeric prec) -> BigDecimal

  def self?.acos: (BigDecimal, Numeric) -> BigDecimal

  def self?.acosh: (BigDecimal, Numeric) -> BigDecimal

  def self?.asin: (BigDecimal, Numeric) -> BigDecimal

  def self?.asinh: (BigDecimal, Numeric) -> BigDecimal

  def self?.atan: (BigDecimal x, Numeric prec) -> BigDecimal

  def self?.atan2: (BigDecimal, BigDecimal, Numeric) -> BigDecimal

  def self?.atanh: (BigDecimal, Numeric) -> BigDecimal

  def self?.cbrt: (BigDecimal, Numeric) -> BigDecimal

  def self?.cos: (BigDecimal x, Numeric prec) -> BigDecimal

  def self?.cosh: (BigDecimal, Numeric) -> BigDecimal

  def self?.erf: (BigDecimal, Numeric) -> BigDecimal

  def self?.erfc: (BigDecimal, Numeric) -> BigDecimal

  def self?.exp: (BigDecimal, Numeric prec) -> BigDecimal

  def self?.frexp: (BigDecimal) -> [ BigDecimal, Integer ]

  def self?.gamma: (BigDecimal, Numeric) -> BigDecimal

  def self?.hypot: (BigDecimal, BigDecimal, Numeric) -> BigDecimal

  def self?.ldexp: (BigDecimal, Integer) -> BigDecimal

  def self?.lgamma: (BigDecimal, Numeric) -> [BigDecimal, Integer]

  def self?.log: (BigDecimal, Numeric prec) -> BigDecimal

  def self?.log2: (BigDecimal, Numeric) -> BigDecimal

  def self?.sin: (BigDecimal x, Numeric prec) -> BigDecimal

  def self?.sinh: (BigDecimal, Numeric) -> BigDecimal

  def self?.sqrt: (BigDecimal x, Numeric prec) -> BigDecimal

  def self?.tanh: (BigDecimal, Numeric) -> BigDecimal
end
