module RBS
  module Unnamed
    %a{annotate:rdoc:copy:ARGF}
    class ARGFClass
      include Enumerable[String]

      %a{annotate:rdoc:copy:ARGF#argv}
      def argv: () -> ::Array[String]

      %a{annotate:rdoc:copy:ARGF#binmode}
      def binmode: () -> self

      %a{annotate:rdoc:copy:ARGF#binmode?}
      def binmode?: () -> bool

      %a{annotate:rdoc:copy:ARGF#close}
      def close: () -> self

      %a{annotate:rdoc:copy:ARGF#closed?}
      def closed?: () -> bool

      %a{annotate:rdoc:copy:ARGF#each}
      def each: (?String sep, ?Integer limit) { (String line) -> untyped } -> self
              | (?String sep, ?Integer limit) -> ::Enumerator[String, self]

      %a{annotate:rdoc:copy:ARGF#each_byte}
      def each_byte: () { (Integer byte) -> untyped } -> self
                   | () -> ::Enumerator[Integer, self]

      %a{annotate:rdoc:copy:ARGF#each_char}
      def each_char: () { (String char) -> untyped } -> self
                   | () -> ::Enumerator[String, self]

      %a{annotate:rdoc:copy:ARGF#each_codepoint}
      def each_codepoint: () { (Integer codepoint) -> untyped } -> self
                        | () -> ::Enumerator[Integer, self]

      %a{annotate:rdoc:copy:ARGF#each_line}
      def each_line: (?String sep, ?Integer limit) { (String line) -> untyped } -> self
                   | (?String sep, ?Integer limit) -> ::Enumerator[String, self]

      %a{annotate:rdoc:copy:ARGF#eof}
      def eof: () -> bool

      %a{annotate:rdoc:copy:ARGF#eof?}
      def eof?: () -> bool

      %a{annotate:rdoc:copy:ARGF#external_encoding}
      def external_encoding: () -> Encoding

      %a{annotate:rdoc:copy:ARGF#file}
      def file: () -> (IO | File)

      %a{annotate:rdoc:copy:ARGF#filename}
      def filename: () -> String

      %a{annotate:rdoc:copy:ARGF#fileno}
      def fileno: () -> Integer

      %a{annotate:rdoc:copy:ARGF#getbyte}
      def getbyte: () -> Integer?

      %a{annotate:rdoc:copy:ARGF#getc}
      def getc: () -> String?

      %a{annotate:rdoc:copy:ARGF#gets}
      def gets: (?String sep, ?Integer limit, ?chomp: boolish) -> String?

      %a{annotate:rdoc:copy:ARGF#inplace_mode}
      def inplace_mode: () -> String?

      %a{annotate:rdoc:copy:ARGF#inplace_mode=}
      def inplace_mode=: (String) -> self

      alias inspect to_s

      %a{annotate:rdoc:copy:ARGF#internal_encoding}
      def internal_encoding: () -> Encoding

      %a{annotate:rdoc:copy:ARGF#lineno}
      def lineno: () -> Integer

      %a{annotate:rdoc:copy:ARGF#lineno=}
      def lineno=: (Integer) -> untyped

      %a{annotate:rdoc:copy:ARGF#path}
      def path: () -> String

      %a{annotate:rdoc:copy:ARGF#pos}
      def pos: () -> Integer

      %a{annotate:rdoc:copy:ARGF#pos=}
      def pos=: (Integer) -> Integer

      %a{annotate:rdoc:copy:ARGF#print}
      def print: (*untyped args) -> nil

      %a{annotate:rdoc:copy:ARGF#printf}
      def printf: (String format_string, *untyped args) -> nil

      %a{annotate:rdoc:copy:ARGF#putc}
      def putc: (Numeric | String obj) -> untyped

      %a{annotate:rdoc:copy:ARGF#puts}
      def puts: (*untyped obj) -> nil

      %a{annotate:rdoc:copy:ARGF#read}
      def read: (?int? length, ?string outbuf) -> String?

      %a{annotate:rdoc:copy:ARGF#read_nonblock}
      def read_nonblock: (int maxlen, ?string buf, **untyped options) -> String

      %a{annotate:rdoc:copy:ARGF#readbyte}
      def readbyte: () -> Integer

      %a{annotate:rdoc:copy:ARGF#readchar}
      def readchar: () -> String

      %a{annotate:rdoc:copy:ARGF#readline}
      def readline: (?String sep, ?Integer limit, ?chomp: boolish) -> String

      %a{annotate:rdoc:copy:ARGF#readlines}
      def readlines: (?String sep, ?Integer limit, ?chomp: boolish) -> ::Array[String]

      %a{annotate:rdoc:copy:ARGF#readpartial}
      def readpartial: (int maxlen, ?string outbuf) -> String

      %a{annotate:rdoc:copy:ARGF#rewind}
      def rewind: () -> Integer

      %a{annotate:rdoc:copy:ARGF#seek}
      def seek: (Integer amount, ?Integer whence) -> Integer

      %a{annotate:rdoc:copy:ARGF#set_encoding}
      def set_encoding: (String | Encoding ext_or_ext_int_enc, ?String | Encoding int_enc) -> self

      %a{annotate:rdoc:copy:ARGF#skip}
      def skip: () -> self

      %a{annotate:rdoc:copy:ARGF#tell}
      def tell: () -> Integer

      %a{annotate:rdoc:copy:ARGF#to_a}
      def to_a: (?String sep, ?Integer limit) -> ::Array[String]

      %a{annotate:rdoc:copy:ARGF#to_i}
      def to_i: () -> Integer

      %a{annotate:rdoc:copy:ARGF#to_io}
      def to_io: () -> IO

      %a{annotate:rdoc:copy:ARGF#to_s}
      def to_s: () -> String

      %a{annotate:rdoc:copy:ARGF#to_write_io}
      def to_write_io: () -> IO

      %a{annotate:rdoc:copy:ARGF#write}
      def write: (_ToS string) -> Integer

      private

      %a{annotate:rdoc:copy:ARGF#initialize}
      def initialize: (*String argv) -> void

      %a{annotate:rdoc:copy:ARGF#initialize_copy}
      def initialize_copy: (self orig) -> self
    end
  end
end
