module RBS
  module Unnamed
    %a{annotate:rdoc:copy:Random::Base}
    class Random_Base
      include Random_Formatter
      extend Random_Formatter

      %a{annotate:rdoc:copy:Random.new}
      def initialize: (?Integer seed) -> void

      %a{annotate:rdoc:copy:Random#rand}
      def rand: (?0) -> Float
              | (Integer | ::Range[Integer] max) -> Integer
              | (Float | ::Range[Float] max) -> Float

      %a{annotate:rdoc:copy:Random#bytes}
      def bytes: (Integer size) -> String

      %a{annotate:rdoc:copy:Random#seed}
      def seed: () -> Integer
    end

    %a{annotate:rdoc:copy:Random::Formatter}
    module Random_Formatter
      %a{annotate:rdoc:copy:Random::Formatter#rand}
      def rand: (?0) -> Float
              | (Float? n) -> Float
              | (Integer n) -> Integer
              | (Numeric n) -> Numeric
              | (::Range[Float] n) -> Float
              | (::Range[Integer] n) -> Integer
              | (::Range[Numeric] n) -> Numeric

      %a{annotate:rdoc:copy:Random::Formatter#random_number}
      def random_number: () -> Float
                       | (?Float? n) -> Float
                       | (?Integer? n) -> Integer
                       | (?Numeric? n) -> Numeric
                       | (?::Range[Float]? n) -> Float
                       | (?::Range[Integer]? n) -> Integer
                       | (?::Range[Numeric]? n) -> Numeric
    end
  end
end
