module NKF
  def self.guess: (String str) -> Encoding

  def self.nkf: (String opt, String str) -> String
end

NKF::ASCII: Encoding

NKF::AUTO: nil

NKF::BINARY: Encoding

NKF::EUC: Encoding

NKF::JIS: Encoding

NKF::NKF_RELEASE_DATE: String

NKF::NKF_VERSION: String

NKF::NOCONV: nil

NKF::SJIS: Encoding

NKF::UNKNOWN: nil

NKF::UTF16: Encoding

NKF::UTF32: Encoding

NKF::UTF8: Encoding

NKF::VERSION: String
