%a{annotate:rdoc:skip}
module Psych
  class DBM < ::DBM
    VERSION: ::String

    def []: (String key) -> untyped

    def []=: (String key, untyped val) -> untyped

    def fetch: (String keystr, ?untyped? ifnone) { (untyped) -> untyped } -> untyped

    def index: (String keystr) -> untyped

    def key: (String keystr) -> String

    def values_at: (*untyped keys) -> Array[untyped]

    def delete: (String key) -> untyped

    def delete_if: () { (untyped, untyped) -> untyped } -> untyped

    def reject: () { (untyped, untyped) -> untyped } -> Hash[untyped, untyped]

    def each_pair: () { (untyped, untyped) -> untyped } -> untyped

    def each_value: () { (untyped) -> untyped } -> untyped

    def values: () -> untyped

    def has_value?: (untyped val) -> (::TrueClass | ::FalseClass)

    def invert: () -> Hash[untyped, untyped]

    def replace: (Hash[untyped, untyped] | DBM hsh) -> Psych::DBM

    def shift: () -> (Array[untyped] | untyped)

    def select: (*untyped keys) { (untyped, untyped) -> untyped } -> Array[untyped]

    def store: (String key, untyped val) -> untyped

    def update: (Hash[untyped, untyped]) -> Psych::DBM

    def to_a: () -> Array[untyped]

    def to_hash: () -> Hash[untyped, untyped]
  end
end
