class DateTime < Date
  def initialize: (?Integer year, ?Integer month, ?Integer mday, ?Integer hour, ?Integer minute, ?Integer second, ?Integer offset, ?Integer start) -> void

  def self._strptime: (String str, ?String format) -> Hash[Symbol, Integer | String]

  def self.civil: (?Integer year, ?Integer month, ?Integer mday, ?Integer hour, ?Integer minute, ?Integer second, ?Integer offset, ?Integer start) -> DateTime

  def self.commercial: (?Integer cwyear, ?Integer cweek, ?Integer cwday, ?Integer hour, ?Integer minute, ?Integer second, ?Integer offset, ?Integer start) -> DateTime

  def self.httpdate: (String str, ?Integer start) -> DateTime

  def self.iso8601: (String str, ?Integer start) -> DateTime

  def self.jd: (?Integer jd, ?Integer hour, ?Integer minute, ?Integer second, ?Integer offset, ?Integer start) -> DateTime

  def self.jisx0301: (String str, ?Integer start) -> DateTime

  def self.now: (?Integer start) -> DateTime

  def self.ordinal: (?Integer year, ?Integer yday, ?Integer hour, ?Integer minute, ?Integer second, ?Integer offset, ?Integer start) -> DateTime

  def self.parse: (String str, ?boolish complete, ?Integer start) -> DateTime

  def self.rfc2822: (String str, ?Integer start) -> DateTime

  def self.rfc3339: (String str, ?Integer start) -> DateTime

  def self.rfc822: (String str, ?Integer start) -> DateTime

  def self.strptime: (String str, ?String format, ?Integer start) -> DateTime

  def self.xmlschema: (String str, ?Integer start) -> DateTime

  def deconstruct_keys: (Array[Symbol]?) -> Hash[Symbol, untyped]

  def hour: () -> Integer

  def iso8601: (?Integer n) -> String

  def jisx0301: (?Integer n) -> String

  def min: () -> Integer

  def minute: () -> Integer

  def new_offset: (?String offset) -> DateTime

  def offset: () -> Rational

  def rfc3339: (?Integer n) -> String

  def sec: () -> Integer

  def sec_fraction: () -> Rational

  def second: () -> Integer

  def second_fraction: () -> Rational

  def strftime: (?String format) -> String

  def to_date: () -> Date

  def to_datetime: () -> DateTime

  def to_s: () -> String

  def to_time: () -> Time

  def xmlschema: (?Integer n) -> String

  def zone: () -> String
end
