class Date
  def initialize: (?Integer year, ?Integer month, ?Integer mday, ?Integer start) -> void

  include Comparable

  def self._httpdate: (String str) -> Hash[Symbol, Integer]

  def self._iso8601: (String str) -> Hash[Symbol, Integer]

  def self._jisx0301: (String str) -> Hash[Symbol, Integer]

  def self._parse: (String str, ?boolish complete) -> Hash[Symbol, Integer]

  def self._rfc2822: (String str) -> Hash[Symbol, Integer | String]

  def self._rfc3339: (String str) -> Hash[Symbol, Integer | String]

  def self._rfc822: (String str) -> Hash[Symbol, Integer | String]

  def self._strptime: (String str, ?String format) -> Hash[Symbol, Integer]

  def self._xmlschema: (String str) -> Hash[Symbol, Integer]

  def self.civil: (?Integer year, ?Integer month, ?Integer mday, ?Integer start) -> Date

  def self.commercial: (?Integer cwyear, ?Integer cweek, ?Integer cwday, ?Integer start) -> Date

  def self.gregorian_leap?: (Integer year) -> bool

  def self.httpdate: (String str, ?Integer start) -> Date

  def self.iso8601: (String str, ?Integer start) -> Date

  def self.jd: (Integer jd, ?Integer start) -> Date

  def self.jisx0301: (String str, ?Integer start) -> Date

  def self.julian_leap?: (Integer year) -> bool

  def self.leap?: (Integer year) -> bool

  def self.ordinal: (?Integer year, ?Integer yday, ?Integer start) -> Date

  def self.parse: (?String str, ?boolish complete, ?Integer start) -> Date

  def self.rfc2822: (String str, ?Integer start) -> Date

  def self.rfc3339: (String str, ?Integer start) -> Date

  def self.rfc822: (String str, ?Integer start) -> Date

  def self.strptime: (String str, ?String format, ?Integer start) -> Date

  def self.today: (?Integer start) -> Date

  def self.valid_civil?: (Integer year, Integer month, Integer mday, ?Integer start) -> bool

  def self.valid_commercial?: (Integer cwyear, Integer cweek, Integer cwday, ?Integer start) -> bool

  def self.valid_date?: (Integer year, Integer month, Integer mday, ?Integer start) -> bool

  def self.valid_jd?: (Integer jd, ?Integer start) -> bool

  def self.valid_ordinal?: (Integer year, Integer yday, ?Integer start) -> bool

  def self.xmlschema: (String str, ?Integer start) -> Date

  def +: (Numeric & _ToR other) -> Date

  def -: (Numeric & _ToR other) -> Date
       | (Date other) -> Rational

  def <<: (Integer month) -> Date

  def <=>: (untyped other) -> Integer?

  def ===: (Date other) -> bool

  def >>: (Integer month) -> Date

  def ajd: () -> Rational

  def amjd: () -> Rational

  def asctime: () -> String

  def ctime: () -> String

  def cwday: () -> Integer

  def cweek: () -> Integer

  def cwyear: () -> Integer

  def day: () -> Integer

  def deconstruct_keys: (Array[Symbol]?) -> Hash[Symbol, Integer]

  def downto: (Date min) { (Date) -> untyped } -> Date
            | (Date min) -> Enumerator[Date, Date]

  def england: () -> Date

  def friday?: () -> bool

  def gregorian: () -> Date

  def gregorian?: () -> bool

  def httpdate: () -> String

  def inspect: () -> String

  def iso8601: () -> String

  def italy: () -> Date

  def jd: () -> Integer

  def jisx0301: () -> String

  def julian: () -> Date

  def julian?: () -> bool

  def ld: () -> Integer

  def leap?: () -> bool

  def mday: () -> Integer

  def mjd: () -> Integer

  def mon: () -> Integer

  def monday?: () -> bool

  def month: () -> Integer

  def new_start: (?Integer start) -> Date

  def next: () -> Date

  def next_day: (?Integer day) -> Date

  def next_month: (?Integer month) -> Date

  def next_year: (?Integer year) -> Date

  def prev_day: (?Integer day) -> Date

  def prev_month: (?Integer month) -> Date

  def prev_year: (?Integer year) -> Date

  def rfc2822: () -> String

  def rfc3339: () -> String

  def rfc822: () -> String

  def saturday?: () -> bool

  def start: () -> Float

  def step: (Date limit, ?Integer step) { (Date) -> untyped } -> Date
          | (Date limit, ?Integer step) -> ::Enumerator[Date, Date]

  def strftime: (?String format) -> String

  def succ: () -> Date

  def sunday?: () -> bool

  def thursday?: () -> bool

  def to_date: () -> Date

  def to_datetime: () -> DateTime

  def to_s: () -> String

  def to_time: () -> Time

  def tuesday?: () -> bool

  def upto: (Date max) { (Date) -> untyped } -> Date
          | (Date max) -> ::Enumerator[Date, Date]

  def wday: () -> Integer

  def wednesday?: () -> bool

  def xmlschema: () -> String

  def yday: () -> Integer

  def year: () -> Integer
end

Date::ABBR_DAYNAMES: Array[String]

Date::ABBR_MONTHNAMES: Array[String?]

Date::DAYNAMES: Array[String]

Date::ENGLAND: Integer

Date::GREGORIAN: Integer

Date::ITALY: Integer

Date::JULIAN: Integer

Date::MONTHNAMES: Array[String?]
