class DBM
  include Enumerable[[ String, String ]]

  def self.open: (String filename, ?Integer mode, ?Integer flags) -> DBM
               | [T] (String filename, ?Integer mode, ?Integer flags) { (DBM) -> T } -> T

  def []: (String) -> String?

  def []=: (String, String) -> String

  def clear: () -> self

  def close: () -> void

  def closed?: () -> bool

  def delete: (String) -> void

  def delete_if: () { (String) -> boolish } -> self

  def each: () { ([ String, String ]) -> void } -> self
          | () -> Enumerator[[ String, String ], self]

  def each_key: () { (String) -> void } -> self
              | () -> Enumerator[String, self]

  def each_pair: () { ([ String, String ]) -> void } -> self
               | () -> Enumerator[[ String, String ], self]

  def each_value: () { (String) -> void } -> self
                | () -> Enumerator[String, self]

  def empty?: () -> bool

  def fetch: (String key, ?String ifnone) -> String

  def has_key?: (String) -> bool

  def has_value?: () -> bool

  def include?: (String) -> bool

  def invert: () -> Hash[String, String]

  def key: (String) -> String?

  def key?: (String) -> bool

  def keys: () -> Array[String]

  def length: () -> Integer

  def member?: (String) -> bool

  def reject: () { (String, String) -> boolish } -> Hash[String, String]

  def reject!: () { (String, String) -> boolish } -> self

  def replace: (_ReplaceSource) -> ::DBM

  interface _ReplaceSource
    def each_pair: () { ([ String, String ]) -> void } -> void
  end

  def select: () { ([ String, String ]) -> boolish } -> Array[[ String, String ]]

  def shift: () -> [ String, String ]?

  def size: () -> Integer

  def store: (String, String) -> String

  def to_a: () -> Array[[ String, String ]]

  def to_hash: () -> Hash[String, String]

  def update: (_UpdateSource) -> ::DBM

  interface _UpdateSource
    def each_pair: () { ([ String, String ]) -> void } -> void
  end

  def value?: (String) -> bool

  def values: () -> Array[String]

  def values_at: (*String) -> Array[String]

  private

  def initialize: (String filename, ?Integer mode, ?Integer flags) -> void
end

DBM::NEWDB: Integer

DBM::READER: Integer

DBM::VERSION: String

DBM::WRCREAT: Integer

DBM::WRITER: Integer
