module Observable
  def add_observer: (untyped observer, ?Symbol func) -> void

  def changed: (?bool state) -> void

  def changed?: () -> bool

  def count_observers: () -> Integer

  def delete_observer: (untyped observer) -> void

  def delete_observers: () -> void

  def notify_observers: (*untyped arg) -> void

  VERSION: String
end
