module Digest
  def self.bubblebabble: (string) -> String

  def self.const_missing: (Symbol name) -> singleton(::Digest::Base)

  def self.hexencode: (string) -> String

  private

  def bubblebabble: (string) -> String

  def hexencode: (string) -> String
end

Digest::REQUIRE_MUTEX: Thread::Mutex

module Digest::Instance
  def <<: (string) -> self

  def ==: (instance | string) -> bool

  def base64digest: (?string? str) -> String

  def base64digest!: () -> String

  def block_length: () -> Integer

  def bubblebabble: () -> String

  def digest: (?string) -> String

  def digest!: () -> String

  def digest_length: () -> Integer

  def file: (string name) -> instance

  def hexdigest: (?string) -> String

  def hexdigest!: () -> String

  def inspect: () -> String

  def length: () -> Integer

  def new: () -> instance

  def reset: () -> self

  def size: () -> Integer

  def to_s: () -> String

  def update: (string) -> self

  private

  def finish: () -> self
end

class Digest::Class
  include ::Digest::Instance

  def self.base64digest: (string str) -> String

  def self.bubblebabble: (string) -> String

  def self.digest: (string) -> String

  def self.file: (string name) -> instance

  def self.hexdigest: (string) -> String

  private

  def initialize: () -> void
end

class Digest::Base < Digest::Class
  def <<: (string) -> self

  def block_length: () -> Integer

  def digest_length: () -> Integer

  def reset: () -> self

  %a{annotate:rdoc:skip}
  alias update <<

  private

  def finish: () -> String

  def initialize_copy: (self) -> self
end

class Digest::SHA1 < Digest::Base
end

class Digest::SHA2 < Digest::Class
  def initialize: (?(256 | 384 | 512) bitlen) -> void

  def reset: () -> self

  def update: (String) -> self

  private def finish: () -> String

  alias << update

  def block_length: () -> Integer

  def digest_length: () -> Integer

  def initialize_copy: (untyped) -> untyped
end

class Digest::MD5 < Digest::Base
end

class Digest::RMD160 < Digest::Base
end

class Digest::SHA256 < Digest::Base
end

class Digest::SHA384 < Digest::Base
end

class Digest::SHA512 < Digest::Base
end

%a{annotate:rdoc:skip}
class Object
  def Digest: (interned name) -> singleton(::Digest::Base)
end
