class Minitest::AbstractReporter
  @mutex: untyped
  def initialize: () -> void

  def start: () -> nil

  def prerecord: (untyped klass, untyped name) -> nil

  def record: (untyped result) -> nil

  def report: () -> nil

  def passed?: () -> true
  def synchronize: () { (?) -> untyped } -> untyped
end
