module Minitest::Assertions
  self.@diff: untyped

  @skip: untyped

  def self.inspect: () -> "UNDEFINED"

  def self.diff: () -> untyped

  def self.diff=: (untyped o) -> untyped

  def diff: (untyped exp, untyped act) -> (::String | untyped)

  def things_to_diff: (untyped exp, untyped act) -> untyped

  def mu_pp: (untyped obj) -> untyped

  def mu_pp_for_diff: (untyped obj) -> untyped

  def assert: (untyped test, ?untyped? msg) -> true

  def _synchronize: () { () -> untyped } -> untyped

  def assert_empty: (untyped obj, ?untyped? msg) -> untyped

  def _where: () -> untyped

  def assert_equal: (untyped exp, untyped act, ?untyped? msg) -> untyped

  def assert_in_delta: (untyped exp, untyped act, ?::Float delta, ?untyped? msg) -> untyped

  def assert_in_epsilon: (untyped exp, untyped act, ?::Float epsilon, ?untyped? msg) -> untyped

  def assert_includes: (untyped collection, untyped obj, ?untyped? msg) -> untyped

  def assert_instance_of: (untyped cls, untyped obj, ?untyped? msg) -> untyped

  def assert_kind_of: (untyped cls, untyped obj, ?untyped? msg) -> untyped

  def assert_match: (untyped matcher, untyped obj, ?untyped? msg) -> untyped

  def assert_nil: (untyped obj, ?untyped? msg) -> untyped

  def assert_operator: (untyped o1, untyped op, ?untyped o2, ?untyped? msg) -> untyped

  def assert_output: (?untyped? stdout, ?untyped? stderr) ?{ () -> untyped } -> untyped

  def assert_path_exists: (untyped path, ?untyped? msg) -> untyped

  def assert_pattern: () ?{ () -> untyped } -> untyped

  def assert_predicate: (untyped o1, untyped op, ?untyped? msg) -> untyped

  def assert_raises: (*untyped exp) ?{ () -> untyped } -> untyped

  def assert_respond_to: (untyped obj, untyped meth, ?untyped? msg, ?include_all: bool) -> untyped

  def assert_same: (untyped exp, untyped act, ?untyped? msg) -> untyped

  def assert_send: (untyped send_ary, ?untyped? m) -> untyped

  def assert_silent: () { () -> untyped } -> untyped

  def assert_throws: (untyped sym, ?untyped? msg) { () -> untyped } -> untyped

  def capture_io: () { () -> untyped } -> untyped

  def capture_subprocess_io: () { () -> untyped } -> untyped

  def exception_details: (untyped e, untyped msg) -> untyped

  def fail_after: (untyped y, untyped m, untyped d, untyped msg) -> (untyped | nil)

  def flunk: (?untyped? msg) -> untyped

  def message: (?untyped? msg, ?untyped? ending) { (?) -> untyped } -> untyped

  def pass: (?untyped? _msg) -> untyped

  def refute: (untyped test, ?untyped? msg) -> untyped

  def refute_empty: (untyped obj, ?untyped? msg) -> untyped

  def refute_equal: (untyped exp, untyped act, ?untyped? msg) -> untyped

  def refute_in_delta: (untyped exp, untyped act, ?::Float delta, ?untyped? msg) -> untyped

  def refute_in_epsilon: (untyped a, untyped b, ?::Float epsilon, ?untyped? msg) -> untyped

  def refute_includes: (untyped collection, untyped obj, ?untyped? msg) -> untyped

  def refute_instance_of: (untyped cls, untyped obj, ?untyped? msg) -> untyped

  def refute_kind_of: (untyped cls, untyped obj, ?untyped? msg) -> untyped

  def refute_match: (untyped matcher, untyped obj, ?untyped? msg) -> untyped

  def refute_nil: (untyped obj, ?untyped? msg) -> untyped

  def refute_pattern: () ?{ () -> untyped } -> untyped

  def refute_operator: (untyped o1, untyped op, ?untyped o2, ?untyped? msg) -> untyped

  def refute_path_exists: (untyped path, ?untyped? msg) -> untyped

  def refute_predicate: (untyped o1, untyped op, ?untyped? msg) -> untyped

  def refute_respond_to: (untyped obj, untyped meth, ?untyped? msg, ?include_all: bool) -> untyped

  def refute_same: (untyped exp, untyped act, ?untyped? msg) -> untyped

  def skip: (?untyped? msg, ?untyped? _ignored) -> untyped

  def skip_until: (untyped y, untyped m, untyped d, untyped msg) -> untyped

  def skipped?: () -> untyped

  def assert_mock: (untyped mock) -> untyped

  E: String

  UNDEFINED: Object
end
