class Minitest::BenchSpec < ::Minitest::Benchmark
  def self.bench: (untyped name) { (?) -> untyped } -> untyped

  def self.bench_range: () ?{ (?) -> untyped } -> untyped

  def self.bench_performance_linear: (untyped name, ?::Float threshold) { (?) -> untyped } -> untyped

  def self.bench_performance_constant: (untyped name, ?::Float threshold) { (?) -> untyped } -> untyped

  def self.bench_performance_exponential: (untyped name, ?::Float threshold) { (?) -> untyped } -> untyped

  def self.bench_performance_logarithmic: (untyped name, ?::Float threshold) { (?) -> untyped } -> untyped

  def self.bench_performance_power: (untyped name, ?::Float threshold) { (?) -> untyped } -> untyped
  extend Minitest::Spec::DSL
  include Minitest::Spec::DSL::InstanceMethods
end
