module Minitest::Guard
  def jruby?: (?untyped platform) -> untyped

  def maglev?: (?untyped platform) -> untyped

  def mri?: (?untyped platform) -> untyped

  def osx?: (?untyped platform) -> untyped

  def rubinius?: (?untyped platform) -> untyped

  def windows?: (?untyped platform) -> untyped
end
