class Minitest::Mock
  @@KW_WARNED: untyped
  @delegator: untyped
  @expected_calls: untyped
  @actual_calls: untyped
  alias __respond_to? respond_to?
  def initialize: (?untyped? delegator) -> void

  def expect: (untyped name, untyped retval, ?untyped args, **untyped kwargs) ?{ (?) -> untyped } -> self
  def __call: (untyped name, untyped data) -> untyped

  def verify: () -> true
  def method_missing: (untyped sym, *untyped args, **untyped kwargs) { (?) -> untyped } -> untyped
  def respond_to?: (untyped sym, ?bool include_private) -> (true | untyped)
end
