class Minitest::PrideIO
  self.@pride: untyped
  @io: untyped
  @colors: untyped
  @size: untyped
  @index: untyped

  def self.pride!: () -> untyped

  def self.pride?: () -> untyped
  def initialize: (untyped io) -> void

  def print: (untyped o) -> untyped
  def puts: (*untyped o) -> untyped

  def pride: (untyped string) -> ::String
  def method_missing: (untyped msg, *untyped args) -> untyped

  attr_reader io: untyped

  ESC: String

  NND: String
end
