module Minitest::Reportable
  def passed?: () -> untyped

  def location: () -> ::String

  def class_name: () -> untyped

  def result_code: () -> untyped

  def skipped?: () -> untyped

  def error?: () -> untyped

  BASE_DIR: String
end
