class Minitest::Runnable
  @@runnables: untyped
  @@marshal_dump_warned: untyped
  self.@_info_handler: untyped
  @NAME: untyped
  @metadata: untyped
  def time_it: () { () -> untyped } -> untyped

  def name: () -> untyped

  def name=: (untyped o) -> untyped

  def self.methods_matching: (untyped re) -> untyped
  def self.reset: () -> untyped

  def self.run: (untyped reporter, ?::Hash[untyped, untyped] options) -> (nil | untyped)

  def self.run_one_method: (untyped klass, untyped method_name, untyped reporter) -> untyped

  def self.test_order: () -> :random
  def self.with_info_handler: (untyped reporter) { (?) -> untyped } -> untyped
  def self.on_signal: (untyped name, untyped action) { () -> untyped } -> untyped

  def self.runnable_methods: () -> untyped

  def self.runnables: () -> untyped
  def marshal_dump: () -> ::Array[untyped]
  def marshal_load: (untyped ary) -> untyped
  def failure: () -> untyped
  def initialize: (untyped name) -> void

  def metadata: () -> untyped

  def metadata?: () -> untyped

  def run: () -> untyped

  def passed?: () -> untyped

  def result_code: () -> untyped

  def skipped?: () -> untyped
  def self.inherited: (untyped klass) -> untyped

  attr_accessor assertions: untyped

  attr_accessor failures: untyped

  attr_accessor time: untyped

  attr_writer metadata: untyped
  SIGNALS: Hash[String, Integer]
end
