class Minitest::StatisticsReporter < ::Minitest::Reporter
  def initialize: (?untyped io, ?::Hash[untyped, untyped] options) -> void
  def passed?: () -> untyped
  def start: () -> untyped
  def record: (untyped result) -> untyped

  def report: () -> untyped

  attr_accessor assertions: untyped

  attr_accessor count: untyped

  attr_accessor results: untyped

  attr_accessor start_time: untyped

  attr_accessor total_time: untyped

  attr_accessor failures: untyped

  attr_accessor errors: untyped

  attr_accessor warnings: untyped

  attr_accessor skips: untyped
end
