class Minitest::SummaryReporter < ::Minitest::StatisticsReporter
  def start: () -> untyped
  def report: () -> untyped
  def statistics: () -> untyped
  def aggregated_results: (untyped io) -> untyped
  def to_s: () -> untyped
  def summary: () -> untyped
  attr_accessor sync: untyped
  attr_accessor old_sync: untyped
end
