class Minitest::Test < ::Minitest::Runnable
  def class_name: () -> untyped

  def self.i_suck_and_my_tests_are_order_dependent!: () -> untyped

  def self.make_my_diffs_pretty!: () -> untyped

  def self.parallelize_me!: () -> untyped

  def self.runnable_methods: () -> untyped

  def run: () -> untyped
  def capture_exceptions: () { () -> untyped } -> untyped
  def sanitize_exception: (untyped e) -> untyped
  def neuter_exception: (untyped e) -> untyped
  def new_exception: (untyped klass, untyped msg, untyped bt, ?bool kill) -> untyped
  attr_accessor self.io_lock: untyped
  include Minitest::Assertions
  include Minitest::Reportable
  include Minitest::Test::LifecycleHooks
  include Minitest::Guard
  extend Minitest::Guard
  PASSTHROUGH_EXCEPTIONS: Array[singleton(NoMemoryError) | singleton(SignalException) | singleton(SystemExit)]
  SETUP_METHODS: Array[String]
  TEARDOWN_METHODS: Array[String]
end
