class Tempfile < File
  def self.create: (?String | [ String, String ] basename, ?String? tmpdir, ?mode: Integer, ?anonymous: bool, **untyped) -> File
                 | [A] (?String | [ String, String ] basename, ?String? tmpdir, ?mode: Integer, ?anonymous: bool, **untyped) { (File) -> A } -> A

  def self.open: (*untyped args, **untyped) -> Tempfile
               | [A] (*untyped args, **untyped) { (Tempfile) -> A } -> A

  def close: (?boolish unlink_now) -> void

  def close!: () -> void

  alias delete unlink

  def inspect: () -> String

  alias length size

  def open: () -> File

  def path: () -> String?

  def size: () -> Integer

  def unlink: () -> void

  class Remover
    def call: (*untyped args) -> void

    private

    def initialize: (::Tempfile tmpfile) -> void
  end

  def self.new: (?String | [ String, String ] basename, ?String? tmpdir, ?mode: Integer, **untyped) -> instance
              | [A] (?String | [ String, String ] basename, ?String? tmpdir, ?mode: Integer, **untyped) { (instance) -> A } -> A
end
