class Enumerator::ArithmeticSequence < Enumerator[Numeric]
  def begin: () -> Numeric?

  def end: () -> Numeric?

  def each: () ?{ (Numeric) -> void } -> self

  def exclude_end?: () -> bool

  def last: () -> Numeric?
          | (Integer n) -> Array[Numeric]

  def size: () -> (Integer | Float)

  def step: () -> Numeric
end
