%a{annotate:rdoc:skip}
class Enumerator[unchecked out Elem, out Return = void]
  class Product[unchecked out Elem] < Enumerator[Array[Elem], Product[Elem]]
    def initialize: (*_EachEntry[Elem]) -> void

    def each: () { (Array[Elem]) -> void } -> self

    def inspect: () -> String

    def rewind: () -> self

    def size: () -> (Integer | Float | nil)

    private

    def initialize_copy: (Product[Elem]) -> void
  end
end
