class StringScanner
  def self.must_C_version: () -> self

  def <<: (String) -> self

  def []: (Integer) -> String?

  def beginning_of_line?: () -> bool

  alias bol? beginning_of_line?

  def captures: () -> Array[String]?

  def charpos: () -> Integer

  def check: (Regexp) -> String?

  def check_until: (Regexp) -> String

  def clear: () -> void

  alias concat <<

  def empty?: () -> bool

  def eos?: () -> bool

  def exist?: (Regexp) -> Integer?

  def fixed_anchor?: () -> bool

  def get_byte: () -> String?

  def getbyte: () -> String?

  def getch: () -> String?

  def inspect: () -> String

  def match?: (Regexp) -> Integer?

  def matched: () -> String?

  def matched?: () -> bool

  def matched_size: () -> Integer?

  def peek: (Integer) -> String

  def peep: (Integer) -> String

  def pointer: () -> Integer

  def pointer=: (Integer) -> Integer

  def pos: () -> Integer

  def pos=: (Integer) -> Integer

  def post_match: () -> String

  def pre_match: () -> String

  def reset: () -> void

  def rest: () -> String

  def rest?: () -> bool

  def rest_size: () -> Integer

  def restsize: () -> Integer

  def scan: (Regexp) -> String?

  def scan_full: (Regexp pattern, bool advance_pointer_p, bool return_string_p) -> untyped

  def scan_until: (Regexp) -> String?

  def search_full: (Regexp pattern, bool advance_pointer_p, bool return_string_p) -> untyped

  def size: () -> Integer

  def skip: (Regexp) -> Integer?

  def skip_until: (Regexp) -> Integer?

  def string: () -> String

  def string=: (String) -> String

  def terminate: () -> void

  def unscan: () -> void

  def values_at: (*Integer) -> Array[String]?

  private

  def initialize: (String, ?bool dup, ?fixed_anchor: bool) -> untyped

  def initialize_copy: (StringScanner) -> void
end

StringScanner::Id: String

StringScanner::Version: String
