%a{annotate:rdoc:source:from=ext/objspace}
module ObjectSpace
  def self?.allocation_class_path: (untyped) -> String

  def self?.allocation_generation: (untyped) -> (Integer | nil)

  def self?.allocation_method_id: (untyped) -> Symbol

  def self?.allocation_sourcefile: (untyped) -> String

  def self?.allocation_sourceline: (untyped) -> Integer

  def self?.count_imemo_objects: (?Hash[Symbol, Integer] result_hash) -> Hash[Symbol, Integer]

  def self?.count_objects_size: (?Hash[Symbol, Integer] result_hash) -> Hash[Symbol, Integer]

  def self?.count_symbols: (?Hash[Symbol, Integer] result_hash) -> Hash[Symbol, Integer]

  def self?.count_tdata_objects: (?Hash[untyped, Integer] result_hash) -> Hash[untyped, Integer]

  def self?.dump: (untyped obj, ?output: Symbol) -> (String | File | nil)

  def self?.dump_all: (?since: Integer | nil, ?full: boolish, ?output: Symbol) -> (String | File | nil)

  def self?.internal_class_of: (untyped) -> Class

  def self?.internal_super_of: (untyped) -> untyped

  def self?.memsize_of: (untyped) -> Integer

  def self?.memsize_of_all: (?Class) -> Integer

  def self?.reachable_objects_from: (untyped) -> (Array[untyped] | nil)

  def self?.reachable_objects_from_root: () -> Hash[String, untyped]

  def self.trace_object_allocations: () { (untyped) -> untyped } -> untyped

  def self?.trace_object_allocations_clear: () -> void

  def self?.trace_object_allocations_debug_start: () -> void

  def self?.trace_object_allocations_start: () -> void

  def self?.trace_object_allocations_stop: () -> void
end
