module Find
  def self?.find: (*String | _ToPath paths, ?ignore_error: boolish) -> Enumerator[String, nil]
                | (*String | _ToPath paths, ?ignore_error: boolish) { (String) -> void } -> nil

  def self?.prune: () -> void
end
