module Kconv
  ASCII: Encoding

  AUTO: nil

  BINARY: Encoding

  EUC: Encoding

  JIS: Encoding

  NOCONV: nil

  SJIS: Encoding

  UNKNOWN: nil

  UTF16: Encoding

  UTF32: Encoding

  UTF8: Encoding

  def self.guess: (String str) -> Encoding

  def self.iseuc: (String str) -> bool

  def self.isjis: (String str) -> bool

  def self.issjis: (String str) -> bool

  def self.isutf8: (String str) -> bool

  def self.kconv: (String str, Encoding? out_code, ?Encoding? in_code) -> String

  def self.toeuc: (String str) -> String

  def self.tojis: (String str) -> String

  def self.tolocale: (String str) -> String

  def self.tosjis: (String str) -> String

  def self.toutf16: (String str) -> String

  def self.toutf32: (String str) -> String

  def self.toutf8: (String str) -> String
end
