class Delegator < BasicObject
  def self.const_missing: (Symbol n) -> untyped

  def self.delegating_block: (Symbol mid) -> Proc

  def self.public_api: () -> untyped

  def !: () -> untyped

  def !=: (untyped obj) -> bool

  def ==: (untyped obj) -> bool

  def __getobj__: () -> untyped

  def __setobj__: (untyped obj) -> untyped

  def eql?: (untyped obj) -> bool

  def freeze: () -> self

  def marshal_dump: () -> untyped

  def marshal_load: (untyped data) -> void

  def method_missing: (Symbol m, *untyped args, **untyped) { (*untyped, **untyped) -> untyped } -> untyped

  def methods: (?boolish all) -> Array[Symbol]

  def protected_methods: (?boolish all) -> Array[Symbol]

  def public_methods: (?untyped all) -> Array[Symbol]

  private

  def initialize: (untyped obj) -> void

  def initialize_clone: (self obj, ?freeze: bool?) -> self

  def initialize_dup: (self obj) -> self

  def respond_to_missing?: (Symbol m, bool include_private) -> bool

  def target_respond_to?: (untyped target, Symbol m, bool include_private) -> bool

  VERSION: String
end
