module Coverage
  def self.line_stub: (String) -> Array[Integer?]

  def self.peek_result: () -> Hash[String, untyped]

  def self.result: (?stop: boolish, ?clear: boolish) -> Hash[String, untyped]

  def self.running?: () -> bool

  def self.setup: (?lines: bool, ?branches: bool, ?methods: bool, ?eval: bool) -> nil
                | (oneshot_lines: bool, ?branches: bool, ?methods: bool, ?eval: bool) -> nil
                | (:all) -> nil

  alias self.start self.setup

  def self.state: () -> (:idle | :suspended | :running)

  def self.resume: () -> nil

  def self.supported?: (Symbol) -> bool

  def self.suspend: () -> nil
end
