class ERB
  def self.version: () -> String

  def initialize: (String, ?eoutvar: String, ?trim_mode: Integer | String | NilClass) -> untyped

  def src: () -> String

  def encoding: () -> Encoding

  def filename: () -> (String | NilClass)

  def filename=: (String | NilClass) -> untyped

  def lineno: () -> Integer

  def lineno=: (Integer) -> untyped

  def location=: (Array[String | Integer]) -> untyped

  def run: (?Binding) -> untyped

  def result: (?Binding) -> String

  def result_with_hash: (Hash[untyped, untyped]) -> String

  def def_method: (Module, String, ?String) -> untyped

  def def_module: (?String) -> Module

  def def_class: (?Class, ?String) -> Class

  module Util
    def self?.html_escape: (String str) -> String

    alias h html_escape

    alias self.h self.html_escape

    def self?.url_encode: (String) -> String

    alias u url_encode

    alias self.u self.url_encode
  end

  module DefMethod
    def self.def_erb_method: (String methodname, (String | ERB) erb_or_fname) -> untyped
  end

  module Escape
    def self?.html_escape: (String) -> String
  end
end
