class Minitest::Parallel::Executor
  @size: untyped
  @queue: untyped
  @pool: untyped

  def initialize: (untyped size) -> void

  def start: () -> untyped

  def <<: (untyped work) -> untyped

  def shutdown: () -> untyped

  attr_reader size: untyped
end
