%a{annotate:rdoc:skip}
class Time
  interface _TimeLike
    def year: () -> Integer

    def mon: () -> Integer

    def day: () -> Integer
  end

  def self.zone_offset: (String zone, ?Integer year) -> Integer

  def self.parse: (String date, ?_TimeLike now) ?{ (Integer) -> Integer } -> Time

  def self.strptime: (String date, String format, ?_TimeLike now) ?{ (Integer) -> Integer } -> Time

  def self.rfc2822: (String date) -> Time

  alias self.rfc822 self.rfc2822

  def self.httpdate: (String date) -> Time

  def self.xmlschema: (String date) -> Time

  alias self.iso8601 self.xmlschema

  def rfc2822: () -> String

  alias rfc822 rfc2822

  def httpdate: () -> String
end
