interface _ToJson
  def to_json: (?JSON::State? state) -> String
end

class JSON::JSONError < StandardError
end

class JSON::GeneratorError < JSON::JSONError
end

class JSON::ParserError < JSON::JSONError
end

class JSON::NestingError < JSON::ParserError
end

class JSON::State
end

module JSON::Ext
end

module JSON::Ext::Generator
end

class JSON::Ext::Generator::State
end

class JSON::Ext::Parser
end

module JSON::Pure
end

module JSON::Pure::Generator
end

class JSON::Pure::Generator::State
end

class JSON::Pure::Parser
end

module JSON
  type options = Hash[Symbol, untyped]

  type generator = singleton(::JSON::Ext::Generator) | singleton(::JSON::Pure::Generator)

  type parser = singleton(::JSON::Ext::Parser) | singleton(::JSON::Pure::Parser)

  type state = singleton(JSON::Ext::Generator::State) | singleton(JSON::Pure::Generator::State)

  interface _WritableIO
    def to_io: () -> _Write
  end

  interface _Write
    def write: (String json) -> void

    def flush: () -> void
  end

  interface _ReadableIO
    def to_io: () -> _Read
  end

  interface _Read
    def read: () -> string
  end

  def self.[]: (untyped object, ?options opts) -> untyped

  def self.create_id: () -> _ToS

  def self.create_id=: (_ToS create_id) -> _ToS

  def self?.dump: (_ToJson obj, ?Integer limit) -> String
                | (_ToJson obj, _WritableIO anIO) -> _Write
                | (_ToJson obj, _Write anIO, ?Integer limit) -> _Write

  %a{deprecated}
  def self.dump_default_options: () -> options

  %a{deprecated}
  def self.dump_default_options=: (options) -> options

  %a{deprecated}
  def self?.fast_generate: (_ToJson obj, ?options opts) -> String

  def self?.generate: (_ToJson obj, ?options opts) -> String

  def self.generator: () -> generator

  def self.generator=: (generator generator) -> void

  def self?.load: (string | _ReadableIO | _Read source, ?options options) -> untyped
                | [T] (string | _ReadableIO | _Read source, ^(?) -> T, ?options options) -> T

  def self?.load_file: (string path, ?options opts) -> untyped

  def self?.load_file!: (string path, ?options opts) -> untyped

  %a{deprecated}
  def self.load_default_options: () -> options

  %a{deprecated}
  def self.load_default_options=: (options) -> options

  def self?.parse: (string source, ?options opts) -> untyped

  def self?.parse!: (string source, ?options opts) -> untyped

  def self.parser: () -> parser

  def self.parser=: (parser parser) -> void

  def self?.pretty_generate: (_ToJson obj, ?options opts) -> untyped

  def self.state: () -> state

  def self.state=: (state) -> state
end

JSON::FAST_STATE_PROTOTYPE: JSON::state

JSON::Infinity: Float

JSON::JSON_LOADED: bool

JSON::MinusInfinity: Float

JSON::NaN: Float

JSON::PRETTY_STATE_PROTOTYPE: JSON::state

JSON::SAFE_STATE_PROTOTYPE: JSON::state

JSON::VERSION: String

JSON::VERSION_ARRAY: Array[Integer]

JSON::VERSION_BUILD: Integer

JSON::VERSION_MAJOR: Integer

JSON::VERSION_MINOR: Integer

%a{annotate:rdoc:skip}
module Kernel
  private

  %a{deprecated}
  def j: (*_ToJson) -> nil

  %a{deprecated}
  def jj: (*_ToJson) -> nil

  def JSON: (string source, ?JSON::options opts) -> untyped
          | (_ToJson obj, ?JSON::options opts) -> String
end

%a{annotate:rdoc:skip}
class Object
  def to_json: (?JSON::State? state) -> String
end

%a{annotate:rdoc:skip}
class NilClass
  def to_json: (?JSON::State? state) -> String
end

%a{annotate:rdoc:skip}
class TrueClass
  def to_json: (?JSON::State? state) -> String
end

%a{annotate:rdoc:skip}
class FalseClass
  def to_json: (?JSON::State? state) -> String
end

%a{annotate:rdoc:skip}
class String
  def to_json: (?JSON::State? state) -> String
end

%a{annotate:rdoc:skip}
class Integer
  def to_json: (?JSON::State? state) -> String
end

%a{annotate:rdoc:skip}
class Float
  def to_json: (?JSON::State? state) -> String
end

%a{annotate:rdoc:skip}
class Hash[unchecked out K, unchecked out V]
  def to_json: (?JSON::State? state) -> String
end

%a{annotate:rdoc:skip}
class Array[unchecked out Elem]
  def to_json: (?JSON::State? state) -> String
end

%a{annotate:rdoc:skip}
class BigDecimal
  def self.json_create: (Hash[String, String] object) -> instance

  def as_json: (*untyped) -> Hash[String, String]

  def to_json: (?JSON::State? state) -> String
end

%a{annotate:rdoc:skip}
class Complex
  def self.json_create: (Hash[String, String | Numeric] object) -> instance

  def as_json: (*untyped) -> Hash[String, String | Numeric]

  def to_json: (?JSON::State? state) -> String
end

%a{annotate:rdoc:skip}
class Date
  def self.json_create: (Hash[String, String | Integer | Float] object) -> instance

  def as_json: (*untyped) -> Hash[String, String | Integer | Float]

  def to_json: (?JSON::State? state) -> String
end

%a{annotate:rdoc:skip}
class DateTime
  def self.json_create: (Hash[String, String | Integer | Float] object) -> instance

  def as_json: (*untyped) -> Hash[String, String | Integer | Float]

  def to_json: (?JSON::State? state) -> String
end

%a{annotate:rdoc:skip}
class Exception
  def self.json_create: (Hash[String, String | Array[String] | nil] object) -> instance

  def as_json: (*untyped) -> Hash[String, String | Array[String] | nil]

  def to_json: (?JSON::State? state) -> String
end

%a{annotate:rdoc:skip}
class OpenStruct
  def self.json_create: (Hash[String, String | Hash[Symbol, untyped]] object) -> instance

  def as_json: (*untyped) -> Hash[String, String | Hash[Symbol, untyped]]

  def to_json: (?JSON::State? state) -> String
end

%a{annotate:rdoc:skip}
class Range[out Elem]
  def self.json_create: [A] (Hash[String, String | [ A, A, bool ]] object) -> Range[A]

  def as_json: (*untyped) -> Hash[String, String | [ Elem, Elem, bool ]]

  def to_json: (?JSON::State? state) -> String
end

%a{annotate:rdoc:skip}
class Rational
  def self.json_create: (Hash[String, String | Integer] object) -> instance

  def as_json: (*untyped) -> Hash[String, String | Integer]

  def to_json: (?JSON::State? state) -> String
end

%a{annotate:rdoc:skip}
class Regexp
  def self.json_create: (Hash[String, String | Integer] object) -> instance

  def as_json: (*untyped) -> Hash[String, String | Integer]

  def to_json: (?JSON::State? state) -> String
end

%a{annotate:rdoc:skip}
class Set[unchecked out A]
  def self.json_create: [A] (Hash[String, String | Array[A]] object) -> Set[A]

  def as_json: (*untyped) -> Hash[String, String | Array[A]]

  def to_json: (?JSON::State? state) -> String
end

%a{annotate:rdoc:skip}
class Struct[Elem]
  def self.json_create: [Elem] (Hash[String, String | Array[Elem]] object) -> Struct[Elem]

  def as_json: (*untyped) -> Hash[String, String | Array[Elem]]

  def to_json: (?JSON::State? state) -> String
end

%a{annotate:rdoc:skip}
class Symbol
  def self.json_create: (Hash[String, String] object) -> instance

  def as_json: (*untyped) -> Hash[String, String]

  def to_json: (?JSON::State? state) -> String
end

%a{annotate:rdoc:skip}
class Time
  def self.json_create: (Hash[String, String | Integer] object) -> instance

  def as_json: (*untyped) -> Hash[String, String | Integer]

  def to_json: (?JSON::State? state) -> String
end
