class CSV < Object
  include Enumerable[untyped]
  extend Forwardable

  def self.foreach: (String | IO path, ?String mode, headers: true | :first_row | Array[untyped] | String, **untyped options) { (::CSV::Row arg0) -> void } -> void
                  | (String | IO path, ?String mode, headers: true | :first_row | Array[untyped] | String, **untyped options) -> Enumerator[::CSV::Row, void]
                  | (String | IO path, ?String mode, **untyped options) { (::Array[String?] arg0) -> void } -> void
                  | (String | IO path, ?String mode, **untyped options) -> Enumerator[::Array[String?], void]

  def initialize: (?String | IO | StringIO io, ?::Hash[Symbol, untyped] options) -> void

  def self.parse: (String str, ?::Hash[Symbol, untyped] options) ?{ (::Array[String?] arg0) -> void } -> ::Array[::Array[String?]]?

  def self.parse_line: (String str, ?::Hash[Symbol, untyped] options) -> ::Array[String?]?

  def read: () -> ::Array[::Array[String?]]

  def readline: () -> ::Array[String?]?

  def self.read: (String | IO path, headers: true | :first_row | Array[untyped] | String, **untyped options) -> ::CSV::Table[CSV::Row]
               | (String | IO path, ?::Hash[Symbol, untyped] options) -> ::Array[::Array[String?]]

  def <<: (::Array[untyped] | CSV::Row row) -> void

  def self.generate: (?String str, **untyped options) { (CSV csv) -> void } -> String

  def each: () -> Enumerator[untyped, Integer]
          | () { (untyped) -> void } -> Integer

  def headers: () -> (Array[String] | true | nil)
end

CSV::DEFAULT_OPTIONS: ::Hash[untyped, untyped]

CSV::VERSION: String

class CSV::Row < Object
  include Enumerable[Array[String]]
  extend Forwardable

  def initialize: (Array[untyped] headers, Array[untyped] fields, ?header_row: bool) -> void

  def <<: (untyped arg) -> untyped

  def ==: (untyped other) -> bool

  alias [] field

  def []=: (*untyped args) -> untyped

  def delete: (untyped header_or_index, ?untyped minimum_index) -> untyped

  def delete_if: () { (*untyped) -> untyped } -> untyped

  def dig: (untyped index_or_header, *untyped indexes) -> untyped

  def each: () -> Enumerator[Array[String], self]
          | () { (Array[String]) -> void } -> self

  alias each_pair each

  def empty?: (*untyped args) { (*untyped) -> untyped } -> bool

  def fetch: (untyped header, *untyped varargs) ?{ (*untyped) -> untyped } -> untyped

  def field: (untyped header_or_index, ?untyped minimum_index) -> untyped

  def field?: (untyped data) -> bool

  def field_row?: () -> bool

  def fields: (*untyped headers_and_or_indices) -> untyped

  def has_key?: (untyped header) -> bool

  alias header? has_key?

  def header_row?: () -> bool

  def headers: () -> untyped

  alias include? has_key?

  def index: (untyped header, ?untyped minimum_index) -> untyped

  def inspect: () -> String

  alias key? has_key?

  def length: (*untyped args) { (*untyped) -> untyped } -> untyped

  alias member? has_key?

  def push: (*untyped args) -> untyped

  def size: (*untyped args) { (*untyped) -> untyped } -> untyped

  def to_csv: (**untyped) -> untyped

  def to_h: () -> untyped

  alias to_hash to_h

  alias to_s to_csv

  alias values_at fields
end

class CSV::FieldInfo < Struct[untyped]
end

class CSV::MalformedCSVError < RuntimeError
end

class CSV::Table[out Elem] < Object
  include Enumerable[Elem]
  extend Forwardable

  def initialize: (untyped array_of_rows, ?headers: untyped) -> untyped

  def <<: (untyped row_or_array) -> untyped

  def ==: (untyped other) -> bool

  def []: (untyped index_or_header) -> untyped

  def []=: (untyped index_or_header, untyped value) -> untyped

  def by_col: () -> untyped

  def by_col!: () -> untyped

  def by_col_or_row: () -> untyped

  def by_col_or_row!: () -> untyped

  def by_row: () -> untyped

  def by_row!: () -> untyped

  def delete: (*untyped indexes_or_headers) -> untyped

  def delete_if: () { (*untyped) -> untyped } -> untyped

  def dig: (untyped index_or_header, *untyped index_or_headers) -> untyped

  def each: () -> Enumerator[Elem, self]
          | () { (Elem) -> void } -> self
          | () { (*untyped) -> void } -> self

  def empty?: (*untyped args) { (*untyped) -> untyped } -> untyped

  def headers: () -> untyped

  def inspect: () -> String

  def length: (*untyped args) { (*untyped) -> untyped } -> untyped

  def mode: () -> untyped

  def push: (*untyped rows) -> untyped

  def size: (*untyped args) { (*untyped) -> untyped } -> untyped

  def to_a: () -> untyped

  def to_csv: (?write_headers: boolish, **untyped) -> untyped

  alias to_s to_csv

  def values_at: (*untyped indices_or_headers) -> untyped
end

%a{annotate:rdoc:skip}
class Array[unchecked out Elem] < Object
  def to_csv: (**untyped options) -> String
end

%a{annotate:rdoc:skip}
class String
  def parse_csv: (**untyped options) -> ::Array[String?]?
end
