module Net
  type headers = Hash[String | Symbol, untyped]

  class HTTPBadResponse < StandardError
  end

  class HTTPHeaderSyntaxError < StandardError
  end

  class HTTP < Protocol
    VERSION: String

    Revision: untyped

    HTTPVersion: String

    HAVE_ZLIB: bool

    def self.version_1_2: () -> ::TrueClass

    def self.version_1_2?: () -> ::TrueClass

    def self.version_1_1?: () -> ::FalseClass

    alias self.is_version_1_1? self.version_1_1?

    alias self.is_version_1_2? self.version_1_2?

    def self.get_print: (URI::Generic uri, ?headers header) -> void
                      | (String host, String path, ?Integer port) -> void

    def self.get: (URI::Generic uri, ?headers header) -> String
                | (String host, String path, ?Integer port) -> String

    def self.get_response: (URI::Generic uri, ?headers header) ?{ (Net::HTTPResponse) -> void } -> Net::HTTPResponse
                         | (String host, String path, ?Integer port) -> Net::HTTPResponse

    def self.post: (URI::Generic url, String data, ?headers header) -> Net::HTTPResponse

    def self.post_form: (URI::Generic url, Hash[String, untyped] params) -> Net::HTTPResponse

    def self.default_port: () -> Integer

    def self.http_default_port: () -> Integer

    def self.https_default_port: () -> Integer

    def self.start: (String address, ?Integer? port, ?String | :ENV | nil p_addr, ?Integer? p_port, ?String? p_user, ?String? p_pass, ?Hash[Symbol, untyped]?, **untyped opt) -> Net::HTTP
                  | [T] (String address, ?Integer? port, ?String | :ENV | nil p_addr, ?Integer? p_port, ?String? p_user, ?String? p_pass, ?Hash[Symbol, untyped]?, **untyped opt) { (Net::HTTP) -> T } -> T

    alias self.newobj self.new

    def self.new: (String address, ?Integer? port, ?String | :ENV | nil p_addr, ?Integer? p_port, ?String? p_user, ?String? p_pass, ?untyped? p_no_proxy) -> Net::HTTP

    def inspect: () -> String

    def set_debug_output: (IO output) -> void

    attr_reader address: String

    attr_reader port: Integer

    attr_accessor local_host: String

    attr_accessor local_port: Integer

    attr_writer proxy_from_env: untyped

    attr_accessor proxy_address: String?

    attr_accessor proxy_port: Integer?

    attr_accessor proxy_user: String?

    attr_accessor proxy_pass: String?

    attr_accessor ipaddr: String?

    attr_accessor open_timeout: Float | Integer

    attr_accessor read_timeout: Float | Integer

    attr_accessor write_timeout: Float | Integer

    attr_accessor max_retries: Integer

    attr_accessor continue_timeout: Float | Integer | nil

    attr_accessor keep_alive_timeout: Float | Integer

    def started?: () -> bool

    alias active? started?

    attr_accessor close_on_empty_response: untyped

    def use_ssl?: () -> bool

    def use_ssl=: (boolish flag) -> void

    SSL_IVNAMES: Array[untyped]

    SSL_ATTRIBUTES: Array[Symbol]

    attr_accessor ca_file: untyped

    attr_accessor ca_path: untyped

    attr_accessor cert: untyped

    attr_accessor cert_store: untyped

    attr_accessor ciphers: untyped

    attr_accessor extra_chain_cert: untyped

    attr_accessor key: untyped

    attr_accessor ssl_timeout: untyped

    attr_accessor ssl_version: untyped

    attr_accessor min_version: untyped

    attr_accessor max_version: untyped

    attr_accessor verify_callback: untyped

    attr_accessor verify_depth: untyped

    attr_accessor verify_mode: untyped

    attr_accessor verify_hostname: untyped

    def peer_cert: () -> (nil | untyped)

    def start: [T] () { (Net::HTTP) -> T } -> T
             | () -> Net::HTTP

    def finish: () -> void

    def self.Proxy: (?interned p_addr, ?Integer? p_port, ?String? p_user, ?String? p_pass) -> untyped

    def self.proxy_class?: () -> bool

    attr_reader self.proxy_address: String?

    attr_reader self.proxy_port: Integer?

    attr_reader self.proxy_user: String?

    attr_reader self.proxy_pass: String?

    def proxy?: () -> bool

    def proxy_from_env?: () -> bool

    def proxy_uri: () -> (nil | URI::Generic)

    alias proxyaddr proxy_address

    alias proxyport proxy_port

    def get: (String path, ?headers initheader, ?bot dest) ?{ (String body_segment) -> void } -> Net::HTTPResponse

    def head: (String path, ?headers initheader) -> Net::HTTPResponse

    def post: (String path, String data, ?headers initheader, ?bot dest) ?{ (String body_segment) -> void } -> Net::HTTPResponse

    def patch: (String path, String data, ?headers initheader, ?bot dest) ?{ (String body_segment) -> void } -> Net::HTTPResponse

    def put: (String path, String data, ?headers initheader) -> Net::HTTPResponse

    def proppatch: (String path, String body, ?headers initheader) -> Net::HTTPResponse

    def lock: (String path, String body, ?headers initheader) -> Net::HTTPResponse

    def unlock: (String path, String body, ?headers initheader) -> Net::HTTPResponse

    def options: (String path, ?headers initheader) -> Net::HTTPResponse

    def propfind: (String path, ?untyped? body, ?headers initheader) -> Net::HTTPResponse

    def delete: (String path, ?headers initheader) -> Net::HTTPResponse

    def move: (String path, ?headers initheader) -> Net::HTTPResponse

    def copy: (String path, ?headers initheader) -> Net::HTTPResponse

    def mkcol: (String path, ?untyped? body, ?headers initheader) -> Net::HTTPResponse

    def trace: (String path, ?headers initheader) -> Net::HTTPResponse

    def request_get: (String path, ?headers initheader) ?{ (Net::HTTPResponse response) -> void } -> Net::HTTPResponse

    def request_head: (String path, ?headers initheader) ?{ (Net::HTTPResponse response) -> void } -> Net::HTTPResponse

    def request_post: (String path, String data, ?headers initheader) ?{ (Net::HTTPResponse response) -> void } -> Net::HTTPResponse

    def request_put: (String path, String data, ?headers initheader) ?{ (Net::HTTPResponse response) -> void } -> Net::HTTPResponse

    alias get2 request_get

    alias head2 request_head

    alias post2 request_post

    alias put2 request_put

    def send_request: (String name, String path, ?String? data, ?headers? header) -> Net::HTTPResponse

    def request: (Net::HTTPRequest req, ?String? body) ?{ (Net::HTTPResponse response) -> void } -> Net::HTTPResponse
  end

  class HTTPGenericRequest
    include Net::HTTPHeader

    def initialize: (String m, boolish reqbody, boolish resbody, URI::Generic | String uri_or_path, ?headers initheader) -> void

    attr_reader method: String

    attr_reader path: String

    attr_reader uri: URI::Generic

    attr_reader decode_content: bool

    def inspect: () -> String

    def []=: (untyped key, untyped val) -> void

    def request_body_permitted?: () -> bool

    def response_body_permitted?: () -> bool

    def body_exist?: () -> bool

    attr_accessor body: String?

    attr_accessor body_stream: untyped
  end

  module HTTPHeader : BasicObject
    def initialize_http_header: (Hash[untyped, untyped] initheader) -> void

    def size: () -> Integer

    alias length size

    %a{deprecated: Use `interned` instead}
    type key = interned

    def []: (interned key) -> (nil | String)

    def []=: (interned key, untyped val) -> void

    def add_field: (interned key, untyped val) -> void

    private

    def set_field: (interned key, untyped val) -> void

    def append_field_value: (untyped ary, untyped val) -> void

    public

    def get_fields: (interned key) -> (nil | Array[String])

    def fetch: (interned key) -> String
             | (interned key, untyped) -> untyped
             | (interned key) { (String) -> untyped } -> untyped

    def each_header: () { (String, String) -> untyped } -> Hash[String, Array[String]]
                   | () -> Enumerator[[ String, String ], Hash[String, Array[String]]]

    alias each each_header

    def each_name: () { (String) -> untyped } -> Hash[String, Array[String]]
                 | () -> Enumerator[String, Hash[String, Array[String]]]

    alias each_key each_name

    def each_capitalized_name: () { (String) -> untyped } -> Hash[String, Array[String]]
                             | () -> Enumerator[String, Hash[String, Array[String]]]

    def each_value: () { (String) -> untyped } -> Hash[String, Array[String]]
                  | () -> Enumerator[String, Hash[String, Array[String]]]

    def delete: (interned key) -> (Array[String] | nil)

    def key?: (interned key) -> bool

    def to_hash: () -> Hash[String, Array[String]]

    def each_capitalized: () { (String, String) -> untyped } -> Hash[String, Array[String]]
                        | () -> Enumerator[[ String, String ], Hash[String, Array[String]]]

    alias canonical_each each_capitalized

    private

    def capitalize: (interned name) -> String

    public

    def range: () -> (nil | Array[Range[Integer]])

    def set_range: (Range[Integer] | Numeric r, ?Integer? e) -> Range[Integer]

    alias range= set_range

    def content_length: () -> (nil | Integer)

    def content_length=: (Integer len) -> void

    def chunked?: () -> bool

    def content_range: () -> (Range[Integer] | nil)

    def range_length: () -> (nil | Integer)

    def content_type: () -> (nil | String)

    def main_type: () -> (nil | String)

    def sub_type: () -> (nil | String)

    def type_params: () -> Hash[untyped, untyped]

    def set_content_type: (interned `type`, ?Hash[untyped, untyped] params) -> void

    alias content_type= set_content_type

    def set_form_data: (Hash[untyped, untyped] params, ?String sep) -> void

    alias form_data= set_form_data

    def set_form: (Hash[untyped, untyped] params, ?String enctype, ?Hash[untyped, untyped] formopt) -> void

    def basic_auth: (String account, String password) -> void

    def proxy_basic_auth: (String account, String password) -> void

    private

    def basic_encode: (String account, String password) -> String

    public

    def connection_close?: () -> bool

    def connection_keep_alive?: () -> bool
  end

  class HTTPRequest < HTTPGenericRequest
    def initialize: (String path, ?headers initheader) -> void
                  | (URI::Generic uri, ?headers initheader) -> void
  end

  class HTTP::Get < HTTPRequest
    METHOD: String

    REQUEST_HAS_BODY: bool

    RESPONSE_HAS_BODY: bool
  end

  class HTTP::Head < HTTPRequest
    METHOD: String

    REQUEST_HAS_BODY: bool

    RESPONSE_HAS_BODY: bool
  end

  class HTTP::Post < HTTPRequest
    METHOD: String

    REQUEST_HAS_BODY: bool

    RESPONSE_HAS_BODY: bool
  end

  class HTTP::Put < HTTPRequest
    METHOD: String

    REQUEST_HAS_BODY: bool

    RESPONSE_HAS_BODY: bool
  end

  class HTTP::Delete < HTTPRequest
    METHOD: String

    REQUEST_HAS_BODY: bool

    RESPONSE_HAS_BODY: bool
  end

  class HTTP::Options < HTTPRequest
    METHOD: String

    REQUEST_HAS_BODY: bool

    RESPONSE_HAS_BODY: bool
  end

  class HTTP::Trace < HTTPRequest
    METHOD: String

    REQUEST_HAS_BODY: bool

    RESPONSE_HAS_BODY: bool
  end

  class HTTP::Patch < HTTPRequest
    METHOD: String

    REQUEST_HAS_BODY: bool

    RESPONSE_HAS_BODY: bool
  end

  class HTTP::Propfind < HTTPRequest
    METHOD: String

    REQUEST_HAS_BODY: bool

    RESPONSE_HAS_BODY: bool
  end

  class HTTP::Proppatch < HTTPRequest
    METHOD: String

    REQUEST_HAS_BODY: bool

    RESPONSE_HAS_BODY: bool
  end

  class HTTP::Mkcol < HTTPRequest
    METHOD: String

    REQUEST_HAS_BODY: bool

    RESPONSE_HAS_BODY: bool
  end

  class HTTP::Copy < HTTPRequest
    METHOD: String

    REQUEST_HAS_BODY: bool

    RESPONSE_HAS_BODY: bool
  end

  class HTTP::Move < HTTPRequest
    METHOD: String

    REQUEST_HAS_BODY: bool

    RESPONSE_HAS_BODY: bool
  end

  class HTTP::Lock < HTTPRequest
    METHOD: String

    REQUEST_HAS_BODY: bool

    RESPONSE_HAS_BODY: bool
  end

  class HTTP::Unlock < HTTPRequest
    METHOD: String

    REQUEST_HAS_BODY: bool

    RESPONSE_HAS_BODY: bool
  end

  class HTTPResponse
    def self.body_permitted?: () -> bool

    include Net::HTTPHeader

    attr_reader http_version: String

    attr_reader code: String

    attr_reader message: String

    alias msg message

    attr_reader uri: URI::Generic | nil

    attr_accessor decode_content: bool

    def inspect: () -> String

    def code_type: () -> untyped

    def error!: () -> untyped

    def error_type: () -> (Net::HTTPError | Net::HTTPServerException | Net::HTTPRetriableError | Net::HTTPFatalError)

    def value: () -> (nil | untyped)

    def uri=: (URI::Generic uri) -> void

    interface _Dest
      def <<: (String) -> void
    end

    def read_body: () -> String
                 | (_Dest dest) -> String
                 | () { (String) -> void } -> String

    def body: () -> String

    def body=: (untyped value) -> void

    alias entity body
  end

  class HTTPUnknownResponse < HTTPResponse
    HAS_BODY: bool

    EXCEPTION_TYPE: Net::HTTPError
  end

  class HTTPInformation < HTTPResponse
    HAS_BODY: bool

    EXCEPTION_TYPE: Net::HTTPError
  end

  class HTTPSuccess < HTTPResponse
    HAS_BODY: bool

    EXCEPTION_TYPE: Net::HTTPError
  end

  class HTTPRedirection < HTTPResponse
    HAS_BODY: bool

    EXCEPTION_TYPE: Net::HTTPRetriableError
  end

  class HTTPClientError < HTTPResponse
    HAS_BODY: bool

    EXCEPTION_TYPE: untyped
  end

  class HTTPServerError < HTTPResponse
    HAS_BODY: bool

    EXCEPTION_TYPE: Net::HTTPFatalError
  end

  class HTTPContinue < HTTPInformation
    HAS_BODY: bool
  end

  class HTTPSwitchProtocol < HTTPInformation
    HAS_BODY: bool
  end

  class HTTPProcessing < HTTPInformation
    HAS_BODY: bool
  end

  class HTTPEarlyHints < HTTPInformation
    HAS_BODY: bool
  end

  class HTTPOK < HTTPSuccess
    HAS_BODY: bool
  end

  class HTTPCreated < HTTPSuccess
    HAS_BODY: bool
  end

  class HTTPAccepted < HTTPSuccess
    HAS_BODY: bool
  end

  class HTTPNonAuthoritativeInformation < HTTPSuccess
    HAS_BODY: bool
  end

  class HTTPNoContent < HTTPSuccess
    HAS_BODY: bool
  end

  class HTTPResetContent < HTTPSuccess
    HAS_BODY: bool
  end

  class HTTPPartialContent < HTTPSuccess
    HAS_BODY: bool
  end

  class HTTPMultiStatus < HTTPSuccess
    HAS_BODY: bool
  end

  class HTTPAlreadyReported < HTTPSuccess
    HAS_BODY: bool
  end

  class HTTPIMUsed < HTTPSuccess
    HAS_BODY: bool
  end

  class HTTPMultipleChoices < HTTPRedirection
    HAS_BODY: bool
  end

  HTTPMultipleChoice: HTTPMultipleChoices

  class HTTPMovedPermanently < HTTPRedirection
    HAS_BODY: bool
  end

  class HTTPFound < HTTPRedirection
    HAS_BODY: bool
  end

  class HTTPSeeOther < HTTPRedirection
    HAS_BODY: bool
  end

  class HTTPNotModified < HTTPRedirection
    HAS_BODY: bool
  end

  class HTTPUseProxy < HTTPRedirection
    HAS_BODY: bool
  end

  class HTTPTemporaryRedirect < HTTPRedirection
    HAS_BODY: bool
  end

  class HTTPPermanentRedirect < HTTPRedirection
    HAS_BODY: bool
  end

  class HTTPBadRequest < HTTPClientError
    HAS_BODY: bool
  end

  class HTTPUnauthorized < HTTPClientError
    HAS_BODY: bool
  end

  class HTTPPaymentRequired < HTTPClientError
    HAS_BODY: bool
  end

  class HTTPForbidden < HTTPClientError
    HAS_BODY: bool
  end

  class HTTPNotFound < HTTPClientError
    HAS_BODY: bool
  end

  class HTTPMethodNotAllowed < HTTPClientError
    HAS_BODY: bool
  end

  class HTTPNotAcceptable < HTTPClientError
    HAS_BODY: bool
  end

  class HTTPProxyAuthenticationRequired < HTTPClientError
    HAS_BODY: bool
  end

  class HTTPRequestTimeout < HTTPClientError
    HAS_BODY: bool
  end

  class HTTPConflict < HTTPClientError
    HAS_BODY: bool
  end

  class HTTPGone < HTTPClientError
    HAS_BODY: bool
  end

  class HTTPLengthRequired < HTTPClientError
    HAS_BODY: bool
  end

  class HTTPPreconditionFailed < HTTPClientError
    HAS_BODY: bool
  end

  class HTTPPayloadTooLarge < HTTPClientError
    HAS_BODY: bool
  end

  class HTTPURITooLong < HTTPClientError
    HAS_BODY: bool
  end

  class HTTPUnsupportedMediaType < HTTPClientError
    HAS_BODY: bool
  end

  class HTTPRangeNotSatisfiable < HTTPClientError
    HAS_BODY: bool
  end

  class HTTPExpectationFailed < HTTPClientError
    HAS_BODY: bool
  end

  class HTTPMisdirectedRequest < HTTPClientError
    HAS_BODY: bool
  end

  class HTTPUnprocessableEntity < HTTPClientError
    HAS_BODY: bool
  end

  class HTTPLocked < HTTPClientError
    HAS_BODY: bool
  end

  class HTTPFailedDependency < HTTPClientError
    HAS_BODY: bool
  end

  class HTTPUpgradeRequired < HTTPClientError
    HAS_BODY: bool
  end

  class HTTPPreconditionRequired < HTTPClientError
    HAS_BODY: bool
  end

  class HTTPTooManyRequests < HTTPClientError
    HAS_BODY: bool
  end

  class HTTPRequestHeaderFieldsTooLarge < HTTPClientError
    HAS_BODY: bool
  end

  class HTTPUnavailableForLegalReasons < HTTPClientError
    HAS_BODY: bool
  end

  class HTTPInternalServerError < HTTPServerError
    HAS_BODY: bool
  end

  class HTTPNotImplemented < HTTPServerError
    HAS_BODY: bool
  end

  class HTTPBadGateway < HTTPServerError
    HAS_BODY: bool
  end

  class HTTPServiceUnavailable < HTTPServerError
    HAS_BODY: bool
  end

  class HTTPGatewayTimeout < HTTPServerError
    HAS_BODY: bool
  end

  class HTTPVersionNotSupported < HTTPServerError
    HAS_BODY: bool
  end

  class HTTPVariantAlsoNegotiates < HTTPServerError
    HAS_BODY: bool
  end

  class HTTPInsufficientStorage < HTTPServerError
    HAS_BODY: bool
  end

  class HTTPLoopDetected < HTTPServerError
    HAS_BODY: bool
  end

  class HTTPNotExtended < HTTPServerError
    HAS_BODY: bool
  end

  class HTTPNetworkAuthenticationRequired < HTTPServerError
    HAS_BODY: bool
  end

  class HTTPResponse
    CODE_CLASS_TO_OBJ: Hash[untyped, untyped]

    CODE_TO_OBJ: Hash[untyped, untyped]
  end

  HTTP::STATUS_CODES: Hash[Integer, String]

  module HTTPExceptions
    def initialize: (untyped msg, untyped res) -> untyped

    attr_reader response: untyped

    alias data response
  end

  class HTTPError < ProtocolError
    include Net::HTTPExceptions
  end

  class HTTPRetriableError < ProtoRetriableError
    include Net::HTTPExceptions
  end

  class HTTPServerException < ProtoServerError
    include Net::HTTPExceptions
  end

  class HTTPFatalError < ProtoFatalError
    include Net::HTTPExceptions
  end
end
