class CGI
  include CGI::Util

  extend CGI::Util

  def initialize: (?String tag_maker) ?{ (String name, String value) -> void } -> void
                | (Hash[Symbol, untyped] options_hash) ?{ (String name, String value) -> void } -> void

  def self.accept_charset: () -> encoding

  def self.accept_charset=: (encoding accept_charset) -> encoding

  def self.parse: (String query) -> Hash[String, Array[String]]

  attr_reader accept_charset: encoding

  alias header http_header

  def http_header: (?String options) -> String
                 | (?Hash[interned, untyped] header_hash) -> String

  def nph?: () -> untyped

  def out: (?String content_type_string) { () -> String } -> void
         | (Hash[interned, untyped] headers_hash) { () -> String } -> void

  def print: (*String options) -> void

  private

  def stdinput: () -> ::IO

  def stdoutput: () -> ::IO

  CR: String

  EOL: String

  HTTP_STATUS: Hash[String, String]

  LF: String

  MAX_MULTIPART_COUNT: Integer

  NEEDS_BINMODE: bool

  PATH_SEPARATOR: Hash[String, String]

  REVISION: String

  VERSION: String

  class Cookie < Array[String]
    def self.parse: (String raw_cookie) -> Hash[String, instance]

    def domain: () -> String?

    def domain=: (String domain) -> String

    def expires: () -> Time?

    def expires=: (Time time) -> Time

    def httponly: () -> bool

    def httponly=: (boolish val) -> bool

    def inspect: () -> String

    def name: () -> String

    def name=: (String name) -> String

    def path: () -> String?

    def path=: (String path) -> String

    def secure: () -> bool

    def secure=: [A] (boolish val) -> A

    def to_s: () -> String

    def value: () -> Array[String]

    def value=: (String val) -> String
              | (Array[String] val) -> Array[String]

    private

    def initialize: (String name_string, *String value) -> void
                  | (Hash[String, untyped] options_hash) -> void
  end

  class InvalidEncoding < Exception
  end

  module QueryExtension
    def []: (String key) -> String?

    def accept: () -> String?

    def accept_charset: () -> String?

    def accept_encoding: () -> String?

    def accept_language: () -> String?

    def auth_type: () -> String?

    def cache_control: () -> String?

    def content_length: () -> String?

    def content_type: () -> String?

    def cookies: () -> Hash[String, Cookie]

    def cookies=: (Hash[String, Cookie] cookies) -> Hash[String, Cookie]

    def create_body: (boolish is_large) -> (Tempfile | StringIO)

    def files: () -> Hash[String, Tempfile | StringIO]

    def from: () -> String?

    def gateway_interface: () -> String?

    def has_key?: (String key) -> bool

    def host: () -> String?

    alias include? has_key?

    alias key? has_key?

    def keys: () -> Array[String]

    def multipart?: () -> bool

    def negotiate: () -> String?

    def params: () -> Hash[String, Array[String] | Tempfile | StringIO]

    def params=: (Hash[String, Array[String] | Tempfile | StringIO] hash) -> Hash[String, Array[String] | Tempfile | StringIO]

    def path_info: () -> String?

    def path_translated: () -> String?

    def pragma: () -> String?

    def query_string: () -> String?

    def raw_cookie: () -> String?

    def raw_cookie2: () -> String?

    def referer: () -> String?

    def remote_addr: () -> String?

    def remote_host: () -> String?

    def remote_ident: () -> String?

    def remote_user: () -> String?

    def request_method: () -> String?

    def script_name: () -> String?

    def server_name: () -> String?

    def server_port: () -> String?

    def server_protocol: () -> String?

    def server_software: () -> String?

    def unescape_filename?: () -> bool

    def user_agent: () -> String?

    private

    def initialize_query: () -> void

    def read_from_cmdline: () -> String

    def read_multipart: (String boundary, Integer content_length) -> (Tempfile | StringIO)
  end

  module Util
    def pretty: (string string, ?String shift) -> String

    def rfc1123_date: (Time time) -> String

    RFC822_DAYS: Array[String]

    RFC822_MONTHS: Array[String]

    TABLE_FOR_ESCAPE_HTML__: Hash[String, String]
  end
end
