module RBS
  module Unnamed
    module Random_Formatter
      %a{annotate:rdoc:copy:Random::Formatter#base64}
      def base64: (?Integer? n) -> String

      %a{annotate:rdoc:copy:Random::Formatter#hex}
      def hex: (?Integer? n) -> String

      %a{annotate:rdoc:copy:Random::Formatter#random_bytes}
      def random_bytes: (?Integer? n) -> String

      %a{annotate:rdoc:copy:Random::Formatter#urlsafe_base64}
      def urlsafe_base64: (?Integer? n, ?boolish padding) -> String

      %a{annotate:rdoc:copy:Random::Formatter#uuid}
      def uuid: () -> String

      %a{annotate:rdoc:copy:Random::Formatter#uuid_v4}
      alias uuid_v4 uuid

      %a{annotate:rdoc:copy:Random::Formatter#uuid_v7}
      def uuid_v7: (?extra_timestamp_bits: Integer) -> String

      %a{annotate:rdoc:copy:Random::Formatter#alphanumeric}
      def alphanumeric: (?Numeric?, ?chars: Array[String]) -> String

      %a{annotate:rdoc:copy:Random::Formatter#gen_random}
      private def gen_random: (Integer n) -> String

      %a{annotate:rdoc:copy:Random::Formatter#choose}
      private def choose: (Array[String] source, Integer n) -> String
    end
  end
end
