%a{annotate:rdoc:skip}
class IO
  class ConsoleMode
    def echo=: (bool) -> bool
    def raw: (?min: int, ?time: int, ?intr: bool) -> self
    def raw!: (?min: int, ?time: int, ?intr: bool) -> self
  end

  def self.console: () -> File?
                  | (:close) -> nil
                  | (Symbol sym, *untyped args) -> untyped

  def self.console_size: () -> [ Integer, Integer ]

  def self.default_console_size: () -> [ Integer, Integer ]

  def beep: () -> self

  def check_winsize_changed: () { () -> void } -> self

  def clear_screen: () -> self

  def console_mode: () -> IO::ConsoleMode

  def console_mode=: (IO::ConsoleMode mode) -> IO::ConsoleMode

  def cooked: [T] () { (self) -> T } -> T

  def cooked!: () -> self

  def cursor: () -> [ Integer, Integer ]

  def cursor=: ([ Integer, Integer ]) -> [ Integer, Integer ]

  def cursor_down: (int) -> self

  def cursor_left: (int) -> self

  def cursor_right: (int) -> self

  def cursor_up: (int) -> self

  def echo=: (bool flag) -> bool

  def echo?: () -> bool

  def erase_line: (0 | 1 | 2 | nil) -> self

  def erase_screen: (0 | 1 | 2 | 3 | nil) -> self

  def getch: (?min: int, ?time: int, ?intr: bool) -> String

  def getpass: (?String) -> String

  def goto: (int, int) -> self

  def goto_column: (int) -> self

  def iflush: () -> self

  def ioflush: () -> self

  def noecho: [T] () { (self) -> T } -> T

  def oflush: () -> self

  def pressed?: (Integer | interned) -> bool

  def raw: [T] (?min: int, ?time: int, ?intr: bool) { (self) -> T } -> T

  def raw!: (?min: int, ?time: int, ?intr: bool) -> self

  def scroll_backward: (int) -> self

  def scroll_forward: (int) -> self

  def winsize: () -> [ Integer, Integer ]

  def winsize=: ([ Integer, Integer ]) -> [ Integer, Integer ]
              | ([ Integer, Integer, Integer, Integer ]) -> [ Integer, Integer, Integer, Integer ]
end
