module FileUtils
  VERSION: String

  type mode = Integer | String

  %a{deprecated: Use top-level `path` instead}
  type path = ::path

  type pathlist = path | Array[path]

  def self?.cd: (path dir, ?verbose: boolish) -> void
              | [X] (path dir, ?verbose: boolish) { (String) -> X } -> X

  alias self.chdir self.cd

  alias chdir cd

  def self?.chmod: (mode mode, pathlist list, ?noop: boolish, ?verbose: boolish) -> void

  def self?.chmod_R: (mode mode, pathlist list, ?noop: boolish, ?verbose: boolish, ?force: boolish) -> void

  def self?.chown: (String? user, String? group, pathlist list, ?noop: boolish, ?verbose: boolish) -> void

  def self?.chown_R: (String? user, String? group, pathlist list, ?noop: boolish, ?verbose: boolish, ?force: boolish) -> void

  def self.collect_method: (Symbol opt) -> Array[String]

  def self.commands: () -> Array[String]

  def self?.compare_file: (path a, path b) -> bool

  alias self.cmp self.compare_file

  alias cmp compare_file

  alias self.identical? self.compare_file

  alias identical? compare_file

  def self?.compare_stream: (IO a, IO b) -> bool

  def self?.copy_entry: (path src, path dest, ?boolish preserve, ?boolish dereference_root, ?boolish remove_destination) -> void

  def self?.copy_file: (path src, path dest, ?boolish preserve, ?boolish dereference) -> void

  def self?.copy_stream: (_Reader src, _Writer dest) -> void

  def self?.cp: (pathlist src, path dest, ?preserve: boolish, ?noop: boolish, ?verbose: boolish) -> void

  alias self.copy self.cp

  alias copy cp

  def self?.cp_lr: (pathlist src, path dest, ?noop: boolish, ?verbose: boolish, ?dereference_root: boolish, ?remove_destination: boolish) -> void

  def self?.cp_r: (pathlist src, path dest, ?preserve: boolish, ?noop: boolish, ?verbose: boolish, ?dereference_root: boolish, ?remove_destination: boolish) -> void

  def self.have_option?: (Symbol mid, Symbol opt) -> bool

  def self?.install: (path src, path dest, ?mode: mode?, ?owner: String?, ?group: String?, ?preserve: boolish, ?noop: boolish, ?verbose: boolish) -> void

  def self?.link_entry: (path src, path dest, ?boolish dereference_root, ?boolish remove_destination) -> void

  def self?.ln: (pathlist src, path dest, ?force: boolish, ?noop: boolish, ?verbose: boolish) -> void

  alias self.link self.ln

  alias link ln

  def self?.ln_s: (pathlist src, path dest, ?force: boolish, ?relative: boolish, ?target_directory: boolish, ?noop: boolish, ?verbose: boolish) -> void

  alias self.symlink self.ln_s

  alias symlink ln_s

  def self?.ln_sf: (pathlist src, path dest, ?noop: boolish, ?verbose: boolish) -> void

  def self?.ln_sr: (pathlist src, path dest, ?target_directory: boolish, ?noop: boolish, ?verbose: boolish) -> void

  def self?.mkdir: (pathlist list, ?mode: Integer?, ?noop: boolish, ?verbose: boolish) -> void

  def self?.mkdir_p: (pathlist list, ?mode: mode?, ?noop: boolish, ?verbose: boolish) -> void

  alias self.makedirs self.mkdir_p

  alias makedirs mkdir_p

  alias self.mkpath self.mkdir_p

  alias mkpath mkdir_p

  def self?.mv: (pathlist src, path dest, ?force: boolish, ?noop: boolish, ?verbose: boolish, ?secure: boolish) -> void

  alias self.move self.mv

  alias move mv

  def self.options: () -> Array[String]

  def self.options_of: (Symbol mid) -> Array[String]

  def self?.pwd: () -> String

  alias self.getwd self.pwd

  alias getwd pwd

  def self?.remove_dir: (path path, ?boolish force) -> void

  def self?.remove_entry: (path path, ?boolish force) -> void

  def self?.remove_entry_secure: (path path, ?boolish force) -> void

  def self?.remove_file: (path path, ?boolish force) -> void

  def self?.rm: (pathlist list, ?force: boolish, ?noop: boolish, ?verbose: boolish) -> void

  alias self.remove self.rm

  alias remove rm

  def self?.rm_f: (pathlist list, ?noop: boolish, ?verbose: boolish) -> void

  alias self.safe_unlink self.rm_f

  alias safe_unlink rm_f

  def self?.rm_r: (pathlist list, ?force: boolish, ?noop: boolish, ?verbose: boolish, ?secure: boolish) -> void

  def self?.rm_rf: (pathlist list, ?noop: boolish, ?verbose: boolish, ?secure: boolish) -> void

  alias self.rmtree self.rm_rf

  alias rmtree rm_rf

  def self?.rmdir: (pathlist list, ?parents: boolish, ?noop: boolish, ?verbose: boolish) -> void

  def self?.touch: (pathlist list, ?noop: boolish, ?verbose: boolish, ?mtime: (Time | Numeric)?, ?nocreate: boolish) -> void

  def self?.uptodate?: (path new, _Each[path] old_list) -> bool
end
