module Timeout
  def self?.timeout: [T] (Numeric? sec, ?singleton(Exception) klass, ?String message) { (Numeric sec) -> T } -> T
end

class Timeout::ExitException < Exception
end

class Timeout::Error < RuntimeError
  attr_reader thread: Thread?
end

Timeout::VERSION: String
