module PTY
  def self.check: (Integer pid, ?boolish raise) -> Process::Status?

  alias self.getpty self.spawn

  def self.open: () -> [ IO, File ]
               | [A] () { ([ IO, File ]) -> A } -> A

  def self.spawn: (*String command) -> [ IO, IO, Integer ]
                | (*String command) { ([ IO, IO, Integer ]) -> void } -> void
end
