module Mutex_m
  def self.append_features: (Module cl) -> untyped

  def self.define_aliases: (Module cl) -> untyped

  def self.extend_object: (Object obj) -> untyped

  def mu_extended: () -> untyped

  def mu_lock: () -> Thread::Mutex

  def mu_locked?: () -> bool

  def mu_synchronize: [T] () { () -> T } -> T

  def mu_try_lock: () -> bool

  def mu_unlock: () -> Thread::Mutex

  def sleep: (?Numeric timeout) -> Integer?

  alias locked? mu_locked?

  alias lock mu_lock

  alias unlock mu_unlock

  alias try_lock mu_try_lock

  alias synchronize mu_synchronize

  private

  def initialize: (*untyped args) -> untyped

  def mu_initialize: () -> untyped
end

Mutex_m::VERSION: String
