module Shellwords
  def self?.shellescape: (String str) -> String

  def self?.shelljoin: (Array[String] array) -> String

  def self?.shellsplit: (String line) -> Array[String]

  alias self.escape self.shellescape

  alias self.join self.shelljoin

  alias self.shellwords self.shellsplit

  alias self.split self.shellsplit

  alias shellwords shellsplit
end

%a{annotate:rdoc:skip}
class Array[unchecked out Elem]
  def shelljoin: () -> String
end

%a{annotate:rdoc:skip}
class String
  def shellescape: () -> String

  def shellsplit: () -> Array[String]
end
