class PrettyPrint
  interface _Output
    def <<: (String) -> void
  end

  def self.format: (?untyped output, ?Integer maxwidth, ?String newline, ?^(Integer) -> Integer genspace) { (PrettyPrint) -> untyped } -> _Output

  def self.singleline_format: (?untyped output, ?Integer? maxwidth, ?String? newline, ?^(Integer) -> Integer? genspace) { (PrettyPrint::SingleLine) -> untyped } -> _Output

  def initialize: (?untyped output, ?Integer maxwidth, ?String newline, ?^(Integer) -> Integer genspace) -> void

  attr_reader output: _Output

  attr_reader maxwidth: Integer

  attr_reader newline: String

  attr_reader genspace: Proc

  attr_reader indent: Integer

  attr_reader group_queue: PrettyPrint::GroupQueue

  def current_group: () -> PrettyPrint::Group

  def break_outmost_groups: () -> untyped

  def text: (String obj, ?Integer width) -> void

  def fill_breakable: (?String sep, ?Integer width) -> void

  def breakable: (?String sep, ?Integer width) -> void

  def group: (?::Integer indent, ?::String open_obj, ?::String close_obj, ?Integer open_width, ?Integer close_width) { () -> untyped } -> Integer

  def group_sub: () { () -> untyped } -> untyped

  def nest: (Integer indent) { () -> untyped } -> void

  def flush: () -> Integer

  class Text
    def initialize: () -> void

    attr_reader width: Integer

    def output: (untyped `out`, untyped output_width) -> untyped

    def add: (untyped obj, Integer width) -> void
  end

  class Breakable
    def initialize: (String sep, Integer width, PrettyPrint q) -> void

    attr_reader obj: String

    attr_reader width: Integer

    attr_reader indent: Integer

    def output: (untyped `out`, Integer output_width) -> untyped
  end

  class Group
    def initialize: (untyped depth) -> void

    attr_reader depth: untyped

    attr_reader breakables: Array[PrettyPrint::Breakable]

    def break: () -> bool

    def break?: () -> bool

    def first?: () -> bool
  end

  class GroupQueue
    def initialize: (*untyped groups) -> void

    def enq: (untyped group) -> void

    def deq: () -> (PrettyPrint::Group | nil)

    def delete: (PrettyPrint::Group group) -> void
  end

  class SingleLine
    def initialize: (String | untyped output, ?Integer? maxwidth, ?String? newline) -> void

    def text: (String obj, ?Integer? width) -> void

    def breakable: (?String sep, ?Integer? width) -> void

    def nest: (untyped indent) { () -> untyped } -> void

    def group: (?Integer? indent, ?String open_obj, ?String close_obj, ?Integer? open_width, ?Integer? close_width) { () -> untyped } -> untyped

    def flush: () -> nil

    def first?: () -> bool
  end
end
