%a{annotate:rdoc:skip}
module Zlib
  class Deflate < Zlib::ZStream
    type compression_level = Integer

    def self.deflate: (string string, ?compression_level level) -> String

    def <<: (string string) -> self

    def deflate: (string string, ?Integer flush) -> String
               | (string string, ?Integer flush) { (String chunk) -> nil } -> nil

    def flush: (?Integer flush) -> String
             | (?Integer flush) { (String chunk) -> nil } -> nil

    def params: (compression_level level, Integer strategy) -> void

    def set_dictionary: (String dictionary) -> String

    private

    def initialize: (?compression_level level, ?Integer window_bits, ?Integer mem_level, ?Integer strategy) -> void

    def initialize_copy: (self other) -> self
  end
end
