%a{annotate:rdoc:skip}
module Zlib
  class GzipFile
    def self.wrap: (IO io, *untyped) { (instance gz) -> void } -> void

    def close: () -> void

    def closed?: () -> void

    def comment: () -> String?

    def crc: () -> Integer

    def finish: () -> IO

    def level: () -> Integer

    def mtime: () -> Time

    def orig_name: () -> String?

    def os_code: () -> Integer

    def sync: () -> bool

    def sync=: (boolish) -> untyped

    def to_io: () -> IO
  end
end
