%a{annotate:rdoc:skip}
module Zlib
  class GzipWriter < Zlib::GzipFile
    def self.open: (String filename) { (instance gz) -> void } -> instance

    def <<: (_ToS obj) -> self

    def comment=: (String arg0) -> void

    def flush: (?Integer flush) -> String

    def mtime=: (path | IO file_name) -> Time

    def orig_name=: (String arg0) -> void

    def pos: () -> Integer

    def print: (*untyped arg0) -> NilClass

    def printf: (String format_string, *untyped arg0) -> NilClass

    def putc: (Numeric | String arg0) -> untyped

    def puts: (*untyped arg0) -> NilClass

    def tell: () -> Integer

    def write: (*_ToS string) -> Integer

    private

    def initialize: (_Writer io, Integer level, Integer strategy, **untyped opts) -> void
  end
end
