%a{annotate:rdoc:skip}
module Zlib
  class GzipReader < Zlib::GzipFile
    include Enumerable[String]

    def self.wrap: (IO io) -> instance
                 | (IO io) { (instance gz) -> void } -> void

    def self.open: (path filename) -> instance
                 | (path filename) { (instance gz) -> void } -> void

    def self.zcat: (IO io, **untyped) -> String
                 | (IO io, **untyped) { (String chunk) -> void } -> nil

    def each: (*untyped) { (String) -> void } -> void

    def each_byte: () { (String) -> void } -> void

    def each_char: () { (String) -> void } -> void

    def each_line: (*untyped) { (String) -> void } -> void

    def eof: () -> bool

    def eof?: () -> bool

    def external_encoding: () -> Encoding

    def getbyte: () -> Integer?

    def getc: () -> String?

    def gets: (?String sep, ?Integer limit) -> String?

    def lineno: () -> Integer

    def lineno=: (Integer arg0) -> Integer

    def pos: () -> Integer

    def read: (?int? length, ?string outbuf) -> String?

    def readbyte: () -> Integer

    def readchar: () -> String

    def readline: (?String sep, ?Integer limit) -> String

    def readlines: (?String sep, ?Integer limit) -> ::Array[String]

    def readpartial: (int maxlen, ?string outbuf) -> String

    def rewind: () -> Integer

    def tell: () -> Integer

    def ungetbyte: (String | Integer arg0) -> NilClass

    def ungetc: (String arg0) -> NilClass

    def unused: () -> String?

    private

    def initialize: (_Reader io, **untyped opts) -> void
  end
end
