%a{annotate:rdoc:skip}
module Zlib
  class Inflate < Zlib::ZStream
    def self.inflate: (string string) -> String

    def <<: (_ToS obj) -> self

    def add_dictionary: (String arg0) -> void

    def inflate: (string string, ?buffer: String) -> String
               | (string string, ?buffer: String) { (String chunk) -> nil } -> nil

    def set_dictionary: (String p1) -> String

    def sync: (String string) -> bool

    def sync_point?: () -> bool

    private

    def initialize: (?Integer window_bits) -> void
  end
end
