module Zlib
  def self.adler32: () -> Integer
                  | (String) -> Integer
                  | (String, Integer) -> Integer

  def self.adler32_combine: (Integer, Integer, Integer) -> Integer

  def self.crc32: () -> Integer
                | (String) -> Integer
                | (String, Integer) -> Integer

  def self.crc32_combine: (Integer, Integer, Integer) -> Integer

  def self.crc_table: () -> Array[Integer]

  def self.deflate: (String) -> String
                  | (String, Integer) -> String

  def self.gunzip: (String) -> String

  def self.gzip: (String) -> String
               | (String, level: Integer) -> String
               | (String, strategy: Integer) -> String
               | (String, level: Integer, strategy: Integer) -> String

  def self.inflate: (String) -> String

  def self.zlib_version: () -> String
end

Zlib::ASCII: Integer

Zlib::BEST_COMPRESSION: Integer

Zlib::BEST_SPEED: Integer

Zlib::BINARY: Integer

Zlib::DEFAULT_COMPRESSION: Integer

Zlib::DEFAULT_STRATEGY: Integer

Zlib::DEF_MEM_LEVEL: Integer

Zlib::FILTERED: Integer

Zlib::FINISH: Integer

Zlib::FIXED: Integer

Zlib::FULL_FLUSH: Integer

Zlib::HUFFMAN_ONLY: Integer

Zlib::MAX_MEM_LEVEL: Integer

Zlib::MAX_WBITS: Integer

Zlib::NO_COMPRESSION: Integer

Zlib::NO_FLUSH: Integer

Zlib::OS_AMIGA: Integer

Zlib::OS_ATARI: Integer

Zlib::OS_CODE: Integer

Zlib::OS_CPM: Integer

Zlib::OS_MACOS: Integer

Zlib::OS_MSDOS: Integer

Zlib::OS_OS2: Integer

Zlib::OS_QDOS: Integer

Zlib::OS_RISCOS: Integer

Zlib::OS_TOPS20: Integer

Zlib::OS_UNIX: Integer

Zlib::OS_UNKNOWN: Integer

Zlib::OS_VMCMS: Integer

Zlib::OS_VMS: Integer

Zlib::OS_WIN32: Integer

Zlib::OS_ZSYSTEM: Integer

Zlib::RLE: Integer

Zlib::SYNC_FLUSH: Integer

Zlib::TEXT: Integer

Zlib::UNKNOWN: Integer

Zlib::VERSION: String

Zlib::ZLIB_VERSION: String
