%a{annotate:rdoc:skip}
module Zlib
  class ZStream
    def adler: () -> Integer

    def avail_in: () -> Integer

    def avail_out: () -> Integer

    def avail_out=: (Integer p1) -> void

    def close: () -> void

    def closed?: () -> bool

    def data_type: () -> String

    def end: () -> void

    def ended?: () -> bool

    def finish: () -> String
              | () { (String chunk) -> void } -> void

    def finished?: () -> bool

    def flush_next_in: () -> String

    def flush_next_out: () -> String?

    def reset: () -> void

    def stream_end?: () -> bool

    def total_in: () -> Integer

    def total_out: () -> Integer
  end
end
