class BasicObject
  def !: () -> bool

  def !=: (untyped other) -> bool

  def ==: (untyped other) -> bool

  def __id__: () -> Integer

  def __send__: (interned name, *untyped, **untyped) ?{ (?) -> untyped } -> untyped

  alias equal? ==

  def instance_eval: (string code, ?string filename, ?int lineno) -> untyped
                   | [U] () { (self) [self: self] -> U } -> U

  def instance_exec: [U] (*untyped, **untyped) { (?) [self: self] -> U } -> U

  def initialize: () -> void

  private

  def method_missing: (Symbol, *untyped, **untyped) ?{ (?) -> untyped } -> untyped

  def singleton_method_added: (Symbol name) -> nil

  def singleton_method_removed: (Symbol name) -> nil

  def singleton_method_undefined: (Symbol name) -> nil
end
