class Binding
  def clone: () -> self

  def eval: (string src, ?string filename, ?int lineno) -> untyped

  def local_variable_defined?: (interned varname) -> bool

  def local_variable_get: (interned varname) -> untyped

  def local_variable_set: [U] (interned varname, U obj) -> U

  def local_variables: () -> Array[Symbol]

  def receiver: () -> untyped

  def source_location: () -> [String, Integer]
end
