interface _ToC
  def to_c: () -> Complex
end

interface _ToR
  def to_r: () -> Rational
end

interface _ToF
  def to_f: () -> Float
end

interface _ToI
  def to_i: () -> Integer
end

interface _ToInt
  def to_int: () -> Integer
end

interface _ToS
  def to_s: () -> String
end

interface _ToStr
  def to_str: () -> String
end

interface _ToSym
  def to_sym: () -> Symbol
end

interface _ToH[K, V]
  def to_h: () -> Hash[K, V]
end

interface _ToHash[K, V]
  def to_hash: () -> Hash[K, V]
end

interface _ToA[T]
  def to_a: () -> Array[T]
end

interface _ToAry[T]
  def to_ary: () -> Array[T]
end

interface _ToProc
  def to_proc: () -> Proc
end

interface _ToPath
  def to_path: () -> String
end

interface _ToIO
  def to_io: () -> IO
end

interface _Inspect
  def inspect: () -> String
end

interface _Each[out E, out R = void]
  def each: () { (E) -> void } -> R
end

interface _EachEntry[out E]
  def each_entry: () { (E) -> void } -> self
end

interface _Reader
  def read: (?int? length, ?string outbuf) -> String?
end

interface _ReaderPartial
  def readpartial: (int maxlen, ?string outbuf) -> String
end

interface _Writer
  def write: (*_ToS data) -> Integer
end

interface _Rewindable
  def rewind: () -> Integer
end

interface _Range[T]
  def begin: () -> T?

  def end: () -> T?

  def exclude_end?: () -> bool
end

interface _Exception
  def exception: () -> Exception
               | (String arg0) -> Exception
end

type int = Integer | _ToInt

type float = Float | _ToF

type range[T] = Range[T] | _Range[T]

type string = String | _ToStr

type array[T] = Array[T] | _ToAry[T]

type hash[K, V] = Hash[K, V] | _ToHash[K, V]

type io = IO | _ToIO

type path = string | _ToPath

type encoding = Encoding | string

type real = Integer | Float | Rational

type interned = Symbol | string

type boolish = top
