%a{annotate:rdoc:source:from=object.c}
class Class < Module
  def initialize: (?Class superclass) ?{ (Class newclass) -> void } -> void

  def allocate: () -> untyped

  def attached_object: () -> untyped

  def inherited: (Class arg0) -> untyped

  def new: () -> untyped

  def subclasses: () -> Array[Class]

  def superclass: () -> Class?
end
