class Complex < Numeric
  def self.polar: (Numeric, ?Numeric) -> Complex

  def self.rect: (Numeric, ?Numeric) -> Complex

  alias self.rectangular self.rect

  def *: (Numeric) -> Complex

  def **: (Numeric) -> Complex

  def +: (Numeric) -> Complex

  def -: (Numeric) -> Complex

  def -@: () -> Complex

  def /: (Numeric) -> Complex

  def <: (Numeric) -> bot

  def <=: (Numeric) -> bot

  def <=>: (untyped) -> Integer?

  def ==: (untyped) -> bool

  def >: (Numeric) -> bot

  def >=: (Numeric) -> bot

  def abs: () -> Numeric

  def abs2: () -> Numeric

  def angle: () -> Float

  alias arg angle

  def ceil: (*untyped) -> bot

  def coerce: (Numeric) -> [ Complex, Complex ]

  def conj: () -> self

  def conjugate: () -> self

  def denominator: () -> Integer

  def div: (Numeric) -> bot

  def divmod: (Numeric) -> bot

  def fdiv: (Numeric) -> Complex

  def finite?: () -> bool

  def floor: (?Integer) -> bot

  def hash: () -> Integer

  %a{annotate:rdoc:copy:Numeric#i}
  def i: () -> bot

  def imag: () -> Numeric

  def imaginary: () -> Numeric

  def infinite?: () -> Integer?

  def inspect: () -> String

  alias magnitude abs

  def modulo: (Numeric) -> bot

  def negative?: () -> bot

  def numerator: () -> Complex

  alias phase angle

  def polar: () -> [ Numeric, Float ]

  def positive?: () -> bot

  def quo: (Numeric) -> Complex

  def rationalize: (?Numeric eps) -> Rational

  def real: () -> Numeric

  def real?: () -> false

  def rect: () -> [ Numeric, Numeric ]

  alias rectangular rect

  def reminder: (Numeric) -> bot

  def round: (*untyped) -> bot

  def step: (*untyped) ?{ (*untyped) -> untyped } -> bot

  def to_c: () -> Complex

  def to_f: () -> Float

  def to_i: () -> Integer

  def to_r: () -> Rational

  def to_s: () -> String

  def truncate: (?Integer) -> bot
end

Complex::I: Complex
