module Comparable : _WithSpaceshipOperator
  def <: (untyped other) -> bool

  def <=: (untyped other) -> bool

  def ==: (untyped other) -> bool

  def >: (untyped other) -> bool

  def >=: (untyped other) -> bool

  def between?: (untyped min, untyped max) -> bool

  def clamp: [A, B] (A min, B max) -> (self | A | B)
           | [A] (Range[A]) -> (self | A)
end

interface Comparable::_WithSpaceshipOperator
  def <=>: (untyped other) -> Integer?
end
