class Data
  def self.define: [KLASS < _DataClass] (*Symbol) ?{ (KLASS) [self: KLASS] -> void } -> KLASS

  interface _DataClass
    %a{annotate:rdoc:copy:Data.new}
    def new: (*untyped) -> Data
           | (**untyped) -> Data

    %a{annotate:rdoc:copy:Data.[]}
    def []: (*untyped) -> Data
          | (**untyped) -> Data

    %a{annotate:rdoc:copy:Data.members}
    def members: () -> Array[Symbol]
  end

  %a{annotate:rdoc:skip}
  def self.new: () -> bot

  def self.allocate: () -> bot

  def ==: (untyped) -> bool

  def deconstruct: () -> Array[untyped]

  def deconstruct_keys: (?Array[Symbol]?) -> Hash[Symbol, untyped]

  def eql?: (untyped) -> bool

  def hash: () -> Integer

  def inspect: () -> String

  def members: () -> Array[Symbol]

  def to_h: () -> Hash[Symbol, untyped]

  alias to_s inspect

  def with: (**untyped) -> self
end
