class Dir
  include Enumerable[String]

  def initialize: (path dir, ?encoding: encoding?) -> void

  def self.[]: (*path patterns, ?base: path?, ?sort: bool) -> Array[String]

  def self.chdir: (?path dir) -> 0
                | [U] (?path dir) { (String dir) -> U } -> U

  def self.children: (path dirname, ?encoding: encoding?) -> Array[String]

  def self.chroot: (path root) -> 0

  def self.delete: (path dirname) -> 0

  def self.each_child: (path dirname, ?encoding: encoding?) -> Enumerator[String, nil]
                     | (path dirname, ?encoding: encoding?) { (String filename) -> void } -> nil

  def self.empty?: (path path_name) -> bool

  def self.entries: (path dirname, ?encoding: encoding?) -> Array[String]

  def self.exist?: (path | io file_name) -> bool

  def self.fchdir: (int) -> Integer
                 | [T] (int) { () -> T } -> T

  alias self.foreach self.each_child

  def self.for_fd: (int) -> Dir

  def self.getwd: () -> String

  def self.glob: (array[path] | path pattern, ?int flags, ?base: path?, ?sort: bool) -> Array[String]
               | (array[path] | path pattern, ?int flags, ?base: path?, ?sort: bool) { (String pathname) -> void } -> nil

  def self.home: (?string? user) -> String

  def self.mkdir: (path dirname, ?int permissions) -> 0

  def self.open: (path dirname, ?encoding: encoding?) -> instance
               | [U] (path dirname, ?encoding: encoding?) { (instance) -> U } -> U

  alias self.pwd self.getwd

  alias self.rmdir self.delete

  alias self.unlink self.delete

  def chdir: () -> Integer
           | [T] () { () -> T } -> T

  def children: () -> Array[String]

  def close: () -> nil

  def each: () { (String) -> void } -> self
          | () -> Enumerator[String, self]

  def each_child: () { (String) -> void } -> self
                | () -> Enumerator[String, self]

  def fileno: () -> Integer

  def inspect: () -> String

  def path: () -> String?

  def pos: () -> Integer

  def pos=: [U < _ToInt] (U pos) -> U

  def read: () -> String?

  def rewind: () -> self

  def seek: (int pos) -> self

  alias tell pos

  alias to_path path
end
