class ArgumentError < StandardError
end

class ClosedQueueError < StopIteration
end

class EncodingError < StandardError
end

class EOFError < IOError
end

class FloatDomainError < RangeError
end

class FrozenError[T] < RuntimeError
  def initialize: (?string? msg, ?receiver: T?) -> void

  def receiver: () -> T?
end

class IndexError < StandardError
end

class Interrupt < SignalException
  def initialize: (?string) -> void
end

class IOError < StandardError
end

class KeyError[K, R] < IndexError
  def initialize: (?string msg, ?receiver: R?, ?key: K?) -> void

  def key: () -> K?

  def receiver: () -> R?
end

class LoadError < ScriptError
  def path: () -> String?
end

class LocalJumpError < StandardError
  def exit_value: () -> untyped

  def reason: () -> Symbol
end

class NameError[T] < StandardError
  def initialize: (?string msg, ?String? name, ?receiver: T?) -> void

  def local_variables: () -> ::Array[Symbol]

  def name: () -> String?

  def receiver: () -> T?
end

class NoMatchingPatternError < StandardError
end

class NoMatchingPatternKeyError[M, K] < NoMatchingPatternError
  def initialize: (?string message, matchee: M, key: K) -> void

  def matchee: () -> M

  def key: () -> K
end

class NoMemoryError < Exception
end

class NoMethodError[T] < NameError[T]
  def initialize: (?string? msg, ?String? name, ?Array[untyped] args, ?boolish `private`, ?receiver: T?) -> void

  def args: () -> Array[untyped]

  def private_call?: () -> bool
end

class NotImplementedError < ScriptError
end

class RangeError < StandardError
end

class RegexpError < StandardError
end

class RuntimeError < StandardError
end

class ScriptError < Exception
end

class SecurityError < Exception
end

class SignalException < Exception
  def initialize: (?string sig_name) -> void
                | (int sig_number, ?string sig_name) -> void

  def signm: () -> String

  def signo: () -> Integer
end

class StandardError < Exception
end

class StopIteration < IndexError
  def result: () -> untyped
end

class SyntaxError < ScriptError
  def initialize: (?string msg) -> void

  def path: () -> String?
end

class SystemCallError < StandardError
  def initialize: (string msg, Integer errno) -> void

  def self.===: (untyped other) -> bool

  def errno: () -> Integer
end

class SystemExit < Exception
  def initialize: () -> void
                | (string msg) -> void
                | (true | false | int status, ?string msg) -> void

  def status: () -> Integer

  def success?: () -> bool
end

class SystemStackError < Exception
end

class ThreadError < StandardError
end

class TypeError < StandardError
end

class UncaughtThrowError < ArgumentError
  def initialize: (untyped tag, untyped value) -> void

  def tag: () -> untyped

  def to_s: () -> String

  def value: () -> untyped
end

class ZeroDivisionError < StandardError
end
