class Exception
  def self.to_tty?: () -> bool

  def self.exception: (?string | _ToS msg) -> instance

  def ==: (untyped obj) -> bool

  def backtrace: () -> Array[String]?

  def backtrace_locations: () -> Array[Thread::Backtrace::Location]?

  def cause: () -> Exception?

  def detailed_message: (?highlight: bool?, **untyped ignored) -> String

  def exception: (?self) -> self
               | (string | _ToS message) -> self

  def initialize: (?string | _ToS message) -> void

  def inspect: () -> String

  def message: () -> String

  def set_backtrace: (String | Array[String]) -> Array[String]
                   | (Array[Thread::Backtrace::Location]) -> Array[Thread::Backtrace::Location]
                   | (nil) -> nil

  def to_s: () -> String

  def full_message: (?highlight: bool?, ?order: (:top | :bottom | string)?) -> String
end
