class FalseClass
  def !: () -> true

  def &: (untyped obj) -> false

  def ===: (false) -> true
         | (untyped obj) -> bool

  def ^: (false | nil) -> false
       | (untyped obj) -> bool

  alias inspect to_s

  def to_s: () -> "false"

  def |: (nil | false) -> false
       | (untyped obj) -> bool
end
