module FileTest
  def self?.blockdev?: (path | io file_name) -> bool

  def self?.chardev?: (path | io file_name) -> bool

  def self?.directory?: (path | io file_name) -> bool

  alias empty? zero?

  alias self.empty? self.zero?

  def self?.executable?: (path file_name) -> bool

  def self?.executable_real?: (path file_name) -> bool

  def self?.exist?: (path | io file_name) -> bool

  def self?.file?: (path | io file) -> bool

  def self?.grpowned?: (path | io file_name) -> bool

  def self?.identical?: (path | io file_1, path | io file_2) -> bool

  def self?.owned?: (path | io file_name) -> bool

  def self?.pipe?: (path | io file_name) -> bool

  def self?.readable?: (path file_name) -> bool

  def self?.readable_real?: (path file_name) -> bool

  def self?.setgid?: (path | io file_name) -> bool

  def self?.setuid?: (path | io file_name) -> bool

  def self?.size: (path | io file_name) -> Integer

  def self?.size?: (path | io file_name) -> Integer?

  def self?.socket?: (path | io file_name) -> bool

  def self?.sticky?: (path | io file_name) -> bool

  def self?.symlink?: (path file_name) -> bool

  def self?.world_readable?: (path | io file_name) -> Integer?

  def self?.world_writable?: (path | io file_name) -> Integer?

  def self?.writable?: (path file_name) -> bool

  def self?.writable_real?: (path file_name) -> bool

  def self?.zero?: (path | io file_name) -> bool
end
