class File < IO
  def initialize: (path | int file_name, ?string | int mode, ?int perm) -> void

  def self.absolute_path: (path file_name, ?path dir_string) -> String

  def self.absolute_path?: (path file_name) -> bool

  def self.atime: (path | IO file_name) -> Time

  def self.basename: (path file_name, ?string suffix) -> String

  def self.birthtime: (path | IO file_name) -> Time

  def self.blockdev?: (path | IO file_name) -> bool

  def self.chardev?: (path | IO file_name) -> bool

  def self.chmod: (int mode, *path file_name) -> Integer

  def self.chown: (int? owner, int? group, *path file_name) -> Integer

  def self.ctime: (path | IO file_name) -> Time

  alias self.delete self.unlink

  def self.directory?: (path | IO path) -> bool

  def self.dirname: (path file_name, ?Integer level) -> String

  alias self.empty? self.zero?

  def self.executable?: (path file_name) -> bool

  def self.executable_real?: (path file_name) -> bool

  def self.exist?: (path | IO file_name) -> bool

  def self.expand_path: (path file_name, ?path dir_string) -> String

  def self.extname: (path path) -> String

  def self.file?: (path | IO file) -> bool

  def self.fnmatch: (string pattern, path path, ?int flags) -> bool

  alias self.fnmatch? self.fnmatch

  def self.ftype: (path file_name) -> String

  def self.grpowned?: (path | IO file_name) -> bool

  def self.identical?: (path | IO file_1, path | IO file_2) -> bool

  def self.join: (*path) -> String

  def self.lchmod: (int mode, *path file_name) -> Integer

  def self.lchown: (int? owner, int? group, *path file_name) -> Integer

  def self.link: (path old_name, path new_name) -> 0

  def self.lstat: (path file_name) -> File::Stat

  def self.lutime: (Time | Numeric atime, Time | Numeric mtime, *path file_name) -> Integer

  def self.mkfifo: (path file_name, ?int mode) -> 0

  def self.mtime: (path | IO file_name) -> Time

  def self.open: (path | int file_name, ?string | int mode, ?int perm) -> instance
               | [T] (path | int file_name, ?string | int mode, ?int perm) { (File) -> T } -> T

  def self.owned?: (path | IO file_name) -> bool

  def self.path: (path path) -> String

  def self.pipe?: (path | IO file_name) -> bool

  def self.readable?: (path file_name) -> bool

  def self.readable_real?: (path file_name) -> bool

  def self.readlink: (path link_name) -> String

  def self.realdirpath: (path pathname, ?path dir_string) -> String

  def self.realpath: (path pathname, ?path dir_string) -> String

  def self.rename: (path old_name, path new_name) -> 0

  def self.setgid?: (path | IO file_name) -> bool

  def self.setuid?: (path | IO file_name) -> bool

  def self.size: (path | IO file_name) -> Integer

  def self.size?: (path | IO file_name) -> Integer?

  def self.socket?: (path | IO file_name) -> bool

  def self.split: (path file_name) -> [ String, String ]

  def self.stat: (path file_name) -> File::Stat

  def self.sticky?: (path | IO file_name) -> bool

  def self.symlink: (path old_name, path new_name) -> 0

  def self.symlink?: (path file_name) -> bool

  def self.truncate: (path file_name, int length) -> 0

  def self.umask: (?int umask) -> Integer

  def self.unlink: (*path file_name) -> Integer

  def self.utime: (Time | Numeric atime, Time | Numeric mtime, *path file_name) -> Integer

  def self.world_readable?: (path | IO file_name) -> Integer?

  def self.world_writable?: (path | IO file_name) -> Integer?

  def self.writable?: (path file_name) -> bool

  def self.writable_real?: (path file_name) -> bool

  def self.zero?: (path | IO file_name) -> bool

  def atime: () -> Time

  def birthtime: () -> Time

  def chmod: (int mode) -> (0 | nil)

  def chown: (int? owner, int? group) -> (0 | nil)

  def ctime: () -> Time

  def flock: (int locking_constant) -> (0 | false)

  def lstat: () -> (File::Stat | nil)

  def mtime: () -> Time

  def path: () -> String

  def size: () -> Integer

  alias to_path path

  def truncate: (int length) -> 0
end

File::ALT_SEPARATOR: String?

File::PATH_SEPARATOR: String

File::SEPARATOR: String

File::Separator: String

module File::Constants
end

File::Constants::APPEND: Integer

File::Constants::BINARY: Integer

File::Constants::CREAT: Integer

File::Constants::DIRECT: Integer

File::Constants::DSYNC: Integer

File::Constants::EXCL: Integer

File::Constants::FNM_CASEFOLD: Integer

File::Constants::FNM_DOTMATCH: Integer

File::Constants::FNM_EXTGLOB: Integer

File::Constants::FNM_NOESCAPE: Integer

File::Constants::FNM_PATHNAME: Integer

File::Constants::FNM_SHORTNAME: Integer

File::Constants::FNM_SYSCASE: Integer

File::Constants::LOCK_EX: Integer

File::Constants::LOCK_NB: Integer

File::Constants::LOCK_SH: Integer

File::Constants::LOCK_UN: Integer

File::Constants::NOATIME: Integer

File::Constants::NOCTTY: Integer

File::Constants::NOFOLLOW: Integer

File::Constants::NONBLOCK: Integer

File::Constants::NULL: String

File::Constants::RDONLY: Integer

File::Constants::RDWR: Integer

File::Constants::RSYNC: Integer

File::Constants::SHARE_DELETE: Integer

File::Constants::SYNC: Integer

File::Constants::TMPFILE: Integer

File::Constants::TRUNC: Integer

File::Constants::WRONLY: Integer

class File::Stat < Object
  include Comparable

  def initialize: (String file) -> void

  def <=>: (File::Stat other) -> Integer
         | (untyped) -> nil

  def atime: () -> Time

  def birthtime: () -> Time

  def blksize: () -> Integer?

  def blockdev?: () -> bool

  def blocks: () -> Integer?

  def chardev?: () -> bool

  def ctime: () -> Time

  def dev: () -> Integer

  def dev_major: () -> Integer

  def dev_minor: () -> Integer

  def directory?: () -> bool

  def executable?: () -> bool

  def executable_real?: () -> bool

  def file?: () -> bool

  def ftype: () -> String

  def gid: () -> Integer

  def grpowned?: () -> bool

  def ino: () -> Integer

  def inspect: () -> String

  def mode: () -> Integer

  def mtime: () -> Time

  def nlink: () -> Integer

  def owned?: () -> bool

  def pipe?: () -> bool

  def rdev: () -> Integer?

  def rdev_major: () -> Integer

  def rdev_minor: () -> Integer

  def readable?: () -> bool

  def readable_real?: () -> bool

  def setgid?: () -> bool

  def setuid?: () -> bool

  def size: () -> Integer

  def size?: () -> Integer?

  def socket?: () -> bool

  def sticky?: () -> bool

  def symlink?: () -> bool

  def uid: () -> Integer

  def world_readable?: () -> Integer?

  def world_writable?: () -> Integer?

  def writable?: () -> bool

  def writable_real?: () -> bool

  def zero?: () -> bool
end
