class Float < Numeric
  def %: (Integer) -> Float
       | (Float) -> Float
       | (Rational) -> Float
       | (Numeric) -> Numeric

  def *: (Complex) -> Complex
       | (Numeric) -> Float

  def **: (Complex) -> Complex
        | (Numeric) -> Float

  def +: (Complex) -> Complex
       | (Numeric) -> Float

  def -: (Complex) -> Complex
       | (Numeric) -> Float

  def -@: () -> Float

  def /: (Complex) -> Complex
       | (Numeric) -> Float

  def <: (Numeric) -> bool

  def <=: (Numeric) -> bool

  def <=>: (Numeric) -> Integer?

  def ==: (untyped) -> bool

  def ===: (untyped) -> bool

  def >: (Numeric) -> bool

  def >=: (Numeric) -> bool

  def abs: () -> Float

  def angle: ...

  alias arg angle

  def ceil: () -> Integer
          | (int digits) -> (Integer | Float)

  def coerce: (Numeric) -> [ Float, Float ]

  def denominator: () -> Integer

  def divmod: (Integer | Float | Rational) -> [ Integer, Float ]
            | (Numeric) -> [ Numeric, Numeric ]

  def eql?: (untyped) -> bool

  def fdiv: (Complex) -> Complex
          | (Numeric) -> Float

  def finite?: () -> bool

  def floor: () -> Integer
           | (int digits) -> (Integer | Numeric)

  def hash: () -> Integer

  def infinite?: () -> Integer?

  alias inspect to_s

  alias magnitude abs

  def modulo: (Numeric) -> Float

  def nan?: () -> bool

  def negative?: () -> bool

  def next_float: () -> Float

  def numerator: () -> Integer

  alias phase angle

  def polar: () -> [ Float, Integer | Float ]

  def positive?: () -> bool

  def prev_float: () -> Float

  def quo: (Complex) -> Complex
         | (Numeric) -> Float

  def rationalize: (?Numeric eps) -> Rational

  def rect: () -> [ Float, Numeric ]

  def remainder: (Numeric) -> Float

  def round: (?half: :up | :down | :even) -> Integer
           | (int digits, ?half: :up | :down | :even) -> (Integer | Float)

  def to_f: () -> Float

  def to_i: () -> Integer

  alias to_int to_i

  def to_r: () -> Rational

  def to_s: () -> String

  def truncate: () -> Integer
              | (Integer ndigits) -> (Integer | Float)

  def zero?: () -> bool
end

Float::DIG: Integer

Float::EPSILON: Float

Float::INFINITY: Float

Float::Infinity: Float

Float::MANT_DIG: Integer

Float::MAX: Float

Float::MAX_10_EXP: Integer

Float::MAX_EXP: Integer

Float::MIN: Float

Float::MIN_10_EXP: Integer

Float::MIN_EXP: Integer

Float::NAN: Float

Float::RADIX: Integer

Float::ROUNDS: Integer
