module GC
  module Profiler
    def self.clear: () -> nil

    def self.disable: () -> nil

    def self.enable: () -> nil

    def self.enabled?: () -> bool

    def self.raw_data: () -> Array[Hash[Symbol, untyped]]?

    def self.report: (?_Reporter io) -> nil

    interface _Reporter
      def write: (String msg) -> void
    end

    def self.result: () -> String

    def self.total_time: () -> Float
  end

  INTERNAL_CONSTANTS: Hash[Symbol, untyped]

  OPTS: Array[String]

  def self.config: () -> Hash[Symbol, untyped]
                 | (Hash[Symbol, untyped]) -> Hash[Symbol, untyped]

  def self.count: () -> Integer

  def self.disable: () -> bool

  def self.enable: () -> bool

  def self.start: (?immediate_sweep: boolish, ?immediate_mark: boolish, ?full_mark: boolish) -> nil

  def self.stat: (?Hash[Symbol, untyped]? hash) -> Hash[Symbol, untyped]
               | (Symbol key) -> Integer

  def self.measure_total_time=: [T] (T enable) -> T

  def self.measure_total_time: () -> bool

  def self.auto_compact=: [T] (T enable) -> T

  def self.auto_compact: () -> bool

  def self.stat_heap: (?Integer? heap_name, ?Hash[Symbol, untyped]? hash) -> Hash[Symbol, untyped]
                    | (Integer heap_name, Symbol key) -> Integer

  def self.latest_compact_info: () -> compact_info

  def self.stress: () -> (Integer | bool)

  def self.stress=: (Integer flag) -> Integer
                  | (bool flag) -> bool

  def self.total_time: () -> Integer

  def self.compact: () -> compact_info

  type compact_info = Hash[:considered | :moved | :moved_up | :moved_down, Hash[Symbol, Integer]]

  def self.verify_compaction_references: (?toward: :empty | untyped, ?double_heap: boolish, ?expand_heap: boolish) -> compact_info

  def self.verify_internal_consistency: () -> nil

  def self.latest_gc_info: (?Hash[Symbol, untyped]? hash) -> Hash[Symbol, untyped]
                         | (Symbol key) -> untyped

  def garbage_collect: (?immediate_sweep: boolish immediate_sweep, ?immediate_mark: boolish immediate_mark, ?full_mark: boolish full_mark) -> nil
end
