class Integer < Numeric
  def self.sqrt: (int n) -> Integer

  def self.try_convert: (int) -> Integer
                      | (untyped) -> Integer?

  def %: (Float) -> Float
       | (Rational) -> Rational
       | (Integer) -> Integer
       | (Numeric) -> Numeric

  def &: (Integer) -> Integer

  def *: (Float) -> Float
       | (Rational) -> Rational
       | (Complex) -> Complex
       | (Integer) -> Integer

  def **: (Integer) -> Numeric
        | (Float) -> Numeric
        | (Rational) -> Numeric
        | (Complex) -> Complex

  def +: (Integer) -> Integer
       | (Float) -> Float
       | (Rational) -> Rational
       | (Complex) -> Complex

  def -: (Integer) -> Integer
       | (Float) -> Float
       | (Rational) -> Rational
       | (Complex) -> Complex

  def -@: () -> Integer

  def /: (Integer) -> Integer
       | (Float) -> Float
       | (Rational) -> Rational
       | (Complex) -> Complex

  def <: (Numeric) -> bool

  def <<: (int) -> Integer

  def <=: (Numeric) -> bool

  def <=>: (Integer | Rational) -> Integer
         | (untyped) -> Integer?

  def ==: (untyped) -> bool

  def ===: (untyped) -> bool

  def >: (Numeric) -> bool

  def >=: (Numeric) -> bool

  def >>: (int) -> Integer

  def []: (int) -> Integer
        | (int i, int len) -> Integer
        | (Range[int]) -> Integer

  def ^: (Integer) -> Integer

  def abs: () -> Integer

  def allbits?: (int mask) -> bool

  def anybits?: (int mask) -> bool

  alias arg angle

  def bit_length: () -> Integer

  def ceil: () -> Integer
          | (int digits) -> (Integer | Float)

  def ceildiv: (Numeric other) -> Integer

  def chr: (?encoding) -> String

  def coerce: (Numeric) -> [ Numeric, Numeric ]

  def denominator: () -> Integer

  def digits: (?int base) -> ::Array[Integer]

  def div: (Numeric) -> Integer

  def divmod: (Integer) -> [ Integer, Integer ]
            | (Float) -> [ Integer, Float ]
            | (Rational) -> [ Integer, Rational ]
            | (Numeric) -> [ Numeric, Numeric ]

  def downto: (Numeric limit) { (Integer) -> void } -> Integer
            | (Numeric limit) -> ::Enumerator[Integer, self]

  def even?: () -> bool

  def fdiv: (Numeric) -> Float

  def floor: (?int digits) -> Integer

  def gcd: (Integer) -> Integer

  def gcdlcm: (Integer) -> [ Integer, Integer ]

  alias inspect to_s

  def integer?: () -> true

  def lcm: (Integer) -> Integer

  def magnitude: () -> Integer

  alias modulo %

  def negative?: () -> bool

  def next: () -> Integer

  def nobits?: (int mask) -> bool

  def numerator: () -> Integer

  def odd?: () -> bool

  def ord: () -> Integer

  def polar: () -> [ Integer, Integer | Float ]

  def positive?: () -> bool

  def pow: (Integer other) -> (Integer | Rational)
         | (Integer other, Integer modulo) -> Integer
         | (Float) -> (Float | Complex)
         | (Rational) -> (Float | Rational | Complex)
         | (Complex) -> Complex

  def pred: () -> Integer

  def quo: (Integer) -> Rational
         | (Float) -> Float
         | (Rational) -> Rational
         | (Complex) -> Complex
         | (Numeric) -> Numeric

  def rationalize: (?Numeric eps) -> Rational

  def rect: () -> [ Integer, Numeric ]

  def remainder: (Integer) -> Integer
               | (Float) -> Float
               | (Rational) -> Rational
               | (Numeric) -> Numeric

  def round: (?half: :up | :down | :even) -> Integer
           | (int digits, ?half: :up | :down | :even) -> (Integer | Float)

  def size: () -> Integer

  def succ: () -> Integer

  def times: () { (Integer) -> void } -> self
           | () -> ::Enumerator[Integer, self]

  def to_f: () -> Float

  def to_i: () -> Integer

  alias to_int to_i

  def to_r: () -> Rational

  def to_s: () -> String
          | (2) -> String
          | (3) -> String
          | (4) -> String
          | (5) -> String
          | (6) -> String
          | (7) -> String
          | (8) -> String
          | (9) -> String
          | (10) -> String
          | (11) -> String
          | (12) -> String
          | (13) -> String
          | (14) -> String
          | (15) -> String
          | (16) -> String
          | (17) -> String
          | (18) -> String
          | (19) -> String
          | (20) -> String
          | (21) -> String
          | (22) -> String
          | (23) -> String
          | (24) -> String
          | (25) -> String
          | (26) -> String
          | (27) -> String
          | (28) -> String
          | (29) -> String
          | (30) -> String
          | (31) -> String
          | (32) -> String
          | (33) -> String
          | (34) -> String
          | (35) -> String
          | (36) -> String
          | (int base) -> String

  def truncate: () -> Integer
              | (int ndigits) -> Integer

  def upto: (Numeric limit) { (Integer) -> void } -> Integer
          | (Numeric limit) -> ::Enumerator[Integer, self]

  def zero?: () -> bool

  def |: (Integer) -> Integer

  def ~: () -> Integer
end
