module Marshal
  MAJOR_VERSION: Integer

  MINOR_VERSION: Integer

  def self?.dump: [W < _Writer] (untyped obj, W port, ?int? limit) -> W
                | (untyped obj, ?Integer limit) -> String

  def self.load: (string | _Source source, ?freeze: boolish) -> untyped
               | [A] (string | _Source source, _Proc[A] proc, ?freeze: boolish) -> A

  interface _Proc[T]
    def call: (untyped loaded) -> T
  end

  interface _Source
    def getbyte: () -> (String | int)

    def read: (Integer) -> string
  end

  alias self.restore self.load
end
