class MatchData
  type capture = String | Symbol | int

  def initialize_copy: (MatchData instance) -> self

  def ==: (MatchData other) -> bool
        | (untyped) -> false

  def []: (capture backref, ?nil) -> String?
        | (int start, int length) -> Array[String?]
        | (range[int?] range) -> Array[String?]

  def begin: (capture backref) -> Integer?

  def bytebegin: (capture backref) -> Integer?

  def byteend: (capture backref) -> Integer?

  def byteoffset: (capture backref) -> ([Integer, Integer] | [nil, nil])

  def captures: () -> Array[String?]

  alias deconstruct captures

  def deconstruct_keys: (Array[Symbol]? array_of_names) -> Hash[Symbol, String?]

  def end: (capture backref) -> Integer?

  alias eql? ==

  def hash: () -> Integer

  def inspect: () -> String

  alias length size

  def named_captures: () -> Hash[String, String?]
                    | (symbolize_names: true) -> Hash[Symbol, String?]
                    | (symbolize_names: boolish) -> Hash[String | Symbol, String?]

  def names: () -> Array[String]

  def match: (capture backref) -> String?

  def match_length: (capture backref) -> Integer?

  def offset: (capture backref) -> ([Integer, Integer] | [nil, nil])

  def post_match: () -> String

  def pre_match: () -> String

  def regexp: () -> Regexp

  def size: () -> Integer

  def string: () -> String

  def to_a: () -> Array[String?]

  def to_s: () -> String

  def values_at: (*capture | range[int?] backrefs) -> Array[String?]
end
