module Math
  E: Float

  PI: Float

  class DomainError < StandardError
  end

  type double = Numeric & _ToF

  def self.acos: (double x) -> Float

  def self.acosh: (double x) -> Float

  def self.asin: (double x) -> Float

  def self.asinh: (double x) -> Float

  def self.atan: (double x) -> Float

  def self.atan2: (double y, double x) -> Float

  def self.atanh: (double x) -> Float

  def self.cbrt: (double x) -> Float

  def self.cos: (double x) -> Float

  def self.cosh: (double x) -> Float

  def self.erf: (double x) -> Float

  def self.erfc: (double x) -> Float

  def self.exp: (double x) -> Float

  def self.expm1: (double x) -> Float

  def self.frexp: (double x) -> [Float, Integer]

  def self.gamma: (double x) -> Float

  def self.hypot: (double x, double y) -> Float

  def self.ldexp: (double fraction, int exponent) -> Float

  def self.lgamma: (double x) -> [Float, -1 | 1]

  def self.log: (double x, ?double base) -> Float

  def self.log10: (double x) -> Float

  def self.log1p: (double x) -> Float

  def self.log2: (double x) -> Float

  def self.sin: (double x) -> Float

  def self.sinh: (double x) -> Float

  def self.sqrt: (double x) -> Float

  def self.tan: (double x) -> Float

  def self.tanh: (double x) -> Float
end
