class Method
  type param_types = Array[[:req | :opt | :rest | :keyreq | :key | :keyrest | :block, Symbol] | [:rest | :keyrest | :nokey]]

  def ==: (untyped other) -> bool

  alias eql? ==

  def hash: () -> Integer

  def inspect: () -> String

  alias to_s inspect

  def to_proc: () -> Proc

  def call: (?) -> untyped

  def <<: (Proc::_Callable g) -> Proc

  alias === call

  def >>: (Proc::_Callable g) -> Proc

  alias [] call

  def arity: () -> Integer

  def clone: () -> self

  def curry: (?int? arity) -> Proc

  def name: () -> Symbol

  def original_name: () -> Symbol

  def owner: () -> (Class | Module)

  def parameters: () -> param_types

  def receiver: () -> untyped

  def source_location: () -> [String, Integer]?

  def super_method: () -> Method?

  def unbind: () -> UnboundMethod
end
