class Module < Object
  def self.constants: () -> ::Array[Integer]

  def self.nesting: () -> ::Array[Module]

  def self.used_modules: () -> ::Array[Module]

  def self.used_refinements: () -> Array[Refinement]

  def <: (Module other) -> bool?

  def <=: (Module other) -> bool?

  def <=>: (untyped other) -> Integer?

  def ==: (untyped other) -> bool

  def ===: (untyped other) -> bool

  def >: (Module other) -> bool?

  def >=: (Module other) -> bool?

  def alias_method: (interned new_name, interned old_name) -> ::Symbol

  def ancestors: () -> ::Array[Module]

  def append_features: (Module arg0) -> self

  def attr_accessor: (*interned arg0) -> Array[Symbol]

  def attr_reader: (*interned arg0) -> Array[Symbol]

  def attr_writer: (*interned arg0) -> Array[Symbol]

  def autoload: (interned _module, String filename) -> NilClass

  def autoload?: (interned name, ?boolish inherit) -> String?

  def class_eval: (String arg0, ?String filename, ?Integer lineno) -> untyped
                | [U] () { (self m) [self: self] -> U } -> U

  def class_exec: [U] (*untyped, **untyped) { (?) [self: self] -> U } -> U

  def class_variable_defined?: (interned arg0) -> bool

  def class_variable_get: (interned arg0) -> untyped

  def class_variable_set: (interned arg0, untyped arg1) -> untyped

  def class_variables: (?boolish inherit) -> ::Array[Symbol]

  def const_added: (Symbol) -> void

  def const_defined?: (interned name, ?boolish inherit) -> bool

  def const_get: (interned name, ?boolish inherit) -> untyped

  def const_missing: (Symbol arg0) -> untyped

  def const_set: (interned arg0, untyped arg1) -> untyped

  def const_source_location: (interned name, ?boolish inherit) -> ([ String, Integer ] | [ ] | nil)

  def constants: (?boolish inherit) -> ::Array[Symbol]

  def define_method: (interned symbol, ^(?) [self: top] -> untyped | Method | UnboundMethod method) -> Symbol
                   | (interned symbol) { (?) [self: top] -> untyped } -> Symbol

  def deprecate_constant: (*interned) -> self

  def equal?: (untyped other) -> bool

  def extend_object: (untyped arg0) -> untyped

  def extended: (Module othermod) -> untyped

  def freeze: () -> self

  def include: (Module, *Module arg0) -> self

  def include?: (Module arg0) -> bool

  def included: (Module othermod) -> untyped

  def included_modules: () -> ::Array[Module]

  def initialize: () -> void
                | () { (Module arg0) -> untyped } -> void

  def instance_method: (interned arg0) -> UnboundMethod

  def instance_methods: (?boolish include_super) -> ::Array[Symbol]

  def method_added: (Symbol meth) -> untyped

  def method_defined?: (interned name, ?boolish inherit) -> bool

  def method_removed: (Symbol method_name) -> untyped

  def module_eval: (String arg0, ?String filename, ?Integer lineno) -> untyped
                 | [U] () { (self m) [self: self] -> U } -> U

  def module_exec: [U] (*untyped, **untyped) { (?) [self: self] -> U } -> U

  def module_function: () -> nil
                     | (Symbol method_name) -> Symbol
                     | (Symbol, Symbol, *Symbol method_name) -> Array[Symbol]
                     | (string method_name) -> string
                     | (interned, interned, *interned method_name) -> Array[interned]

  def name: %a{implicitly-returns-nil} () -> String

  def prepend: (Module, *Module arg0) -> self

  def prepend_features: (Module arg0) -> self

  def prepended: (Module othermod) -> untyped

  def private: () -> nil
             | (Symbol method_name) -> Symbol
             | (Symbol, Symbol, *Symbol method_name) -> Array[Symbol]
             | (string method_name) -> string
             | (interned, interned, *interned method_name) -> Array[interned]
             | (Array[interned]) -> Array[interned]

  def private_class_method: (*interned arg0) -> self
                          | (Array[interned] arg0) -> self

  def private_constant: (*interned arg0) -> self

  def private_instance_methods: (?boolish include_super) -> ::Array[Symbol]

  def private_method_defined?: (interned name, ?boolish inherit) -> bool

  def protected: () -> nil
               | (Symbol method_name) -> Symbol
               | (Symbol, Symbol, *Symbol method_name) -> Array[Symbol]
               | (string method_name) -> string
               | (interned, interned, *interned method_name) -> Array[interned]
               | (Array[interned]) -> Array[interned]

  def protected_instance_methods: (?boolish include_super) -> ::Array[Symbol]

  def protected_method_defined?: (interned name, ?boolish inherit) -> bool

  def public: () -> nil
            | (Symbol method_name) -> Symbol
            | (Symbol, Symbol, *Symbol method_name) -> Array[Symbol]
            | (string method_name) -> string
            | (interned, interned, *interned method_name) -> Array[interned]
            | (Array[interned]) -> Array[interned]

  def public_class_method: (*interned arg0) -> self
                         | (Array[interned] arg0) -> self

  def public_constant: (*interned arg0) -> self

  def public_instance_method: (interned arg0) -> UnboundMethod

  def public_instance_methods: (?boolish include_super) -> ::Array[Symbol]

  def public_method_defined?: (interned name, ?boolish inherit) -> bool

  def refine: (Module mod) { () [self: Refinement] -> void } -> Refinement

  def refinements: () -> Array[Refinement]

  def remove_class_variable: (interned arg0) -> untyped

  def remove_const: (interned arg0) -> untyped

  def remove_method: (*interned arg0) -> self

  def set_temporary_name: (string?) -> self

  def singleton_class?: () -> bool

  def to_s: () -> String

  def undef_method: (*interned arg0) -> self

  def undefined_instance_methods: () -> Array[Symbol]

  def using: (Module arg0) -> self

  def inspect: () -> String

  def attr: %a{deprecated} (interned, bool) -> Array[Symbol]
          | (*interned arg0) -> Array[Symbol]

  %a{deprecated: Use `interned`}
  type id = interned
end
