class NilClass
  def !: () -> true

  def &: (untyped obj) -> false

  def ===: (nil) -> true
         | (untyped obj) -> bool

  def =~: (untyped obj) -> nil

  def ^: (false | nil) -> false
       | (untyped obj) -> bool

  def inspect: () -> "nil"

  def nil?: () -> true

  def rationalize: (?untyped eps) -> Rational

  def to_a: () -> []

  def to_c: () -> Complex

  def to_f: () -> Float

  def to_h: () -> {}

  def to_i: () -> 0

  def to_r: () -> Rational

  def to_s: () -> ""

  def |: (nil | false) -> false
       | (untyped obj) -> bool
end
