class Numeric
  include Comparable

  def %: (Numeric) -> Numeric

  def +: (Numeric) -> Numeric

  def +@: () -> self

  def -: (Numeric) -> Numeric

  def -@: () -> self

  def <=>: (Numeric other) -> Integer

  def abs: () -> Numeric

  def abs2: () -> self

  def angle: () -> (0 | Float)

  alias arg angle

  def ceil: () -> Integer
          | (Integer digits) -> (Integer | Numeric)

  def coerce: (Numeric) -> [ Numeric, Numeric ]

  def conjugate: () -> self

  alias conj conjugate

  def denominator: () -> Integer

  def div: (Numeric) -> Integer

  def divmod: (Numeric) -> [ Numeric, Numeric ]

  def eql?: (untyped) -> bool

  def fdiv: (Numeric) -> Numeric

  def finite?: () -> bool

  def floor: () -> Integer
           | (Integer digits) -> Numeric

  def i: () -> Complex

  def imaginary: () -> 0

  alias imag imaginary

  def infinite?: () -> Integer?

  def integer?: () -> bool

  alias magnitude abs

  def modulo: (Numeric) -> Numeric

  def negative?: () -> bool

  def nonzero?: () -> self?

  def numerator: () -> Numeric

  alias phase angle

  def polar: () -> [ Numeric, Numeric ]

  def positive?: () -> bool

  def quo: (Numeric) -> Numeric

  def real: () -> self

  def real?: () -> true

  def rect: () -> [ Numeric, Numeric ]

  alias rectangular rect

  def remainder: (Numeric) -> Numeric

  def round: () -> Integer
           | (Integer digits) -> Numeric

  def step: (?Numeric limit, ?Numeric step) { (Numeric) -> void } -> self
          | (?Numeric limit, ?Numeric step) -> Enumerator::ArithmeticSequence
          | (?by: Numeric, ?to: Numeric) { (Numeric) -> void } -> self
          | (?by: Numeric, ?to: Numeric) -> Enumerator::ArithmeticSequence

  def to_c: () -> Complex

  def to_int: () -> Integer

  def truncate: () -> Integer
              | (Integer ndigits) -> (Integer | Numeric)

  def zero?: () -> bool

  def clone: (?freeze: true?) -> self
end
