class Pathname
  def self.getwd: () -> Pathname

  def self.glob: (String | Array[String] pattern, ?Integer flags) -> Array[Pathname]
               | (String | Array[String] pattern, ?Integer flags) { (Pathname) -> untyped } -> nil

  def self.pwd: () -> Pathname

  def +: (Pathname | String | _ToStr other) -> Pathname

  alias / +

  def <=>: (Pathname other) -> Integer
         | (untyped other) -> nil

  def ==: (untyped) -> bool

  def ===: (untyped) -> bool

  def absolute?: () -> bool

  def ascend: () { (Pathname) -> untyped } -> nil
            | () -> Enumerator[Pathname, nil]

  def atime: () -> Time

  def basename: (?String | _ToStr suffix) -> Pathname

  def binread: (?Integer length, ?Integer offset) -> String

  def binwrite: (String, ?Integer offset, ?mode: Integer | String, ?flags: Integer, ?external_encoding: encoding, ?internal_encoding: encoding, ?encoding: encoding, ?textmode: boolish, ?binmode: boolish, ?autoclose: boolish, ?invalid: :replace ?, ?undef: :replace ?, ?replace: String, ?fallback: Hash[String, String] | Proc | Method, ?xml: :text | :attr, ?universal_newline: true, ?cr_newline: true, ?crlf_newline: true) -> Integer

  def birthtime: () -> Time

  def blockdev?: () -> bool

  def chardev?: () -> bool

  def children: (?boolish with_directory) -> Array[Pathname]

  def chmod: (Integer mode_int) -> Integer

  def chown: (Integer owner, Integer group) -> Integer

  def cleanpath: (?boolish consider_symlink) -> Pathname

  def ctime: () -> Time

  def delete: () -> Integer

  def descend: () { (Pathname) -> untyped } -> nil
             | () -> Enumerator[Pathname, nil]

  def directory?: () -> bool

  def dirname: () -> Pathname

  def each_child: (?boolish with_directory) { (Pathname) -> void } -> Array[Pathname]
                | (?boolish with_directory) -> Enumerator[Pathname, Array[Pathname]]

  def each_entry: () { (Pathname) -> untyped } -> nil

  def each_filename: () { (String) -> untyped } -> nil
                   | () -> Enumerator[String, nil]

  def each_line: (?String sep, ?Integer limit, ?mode: Integer | String, ?flags: Integer, ?external_encoding: encoding, ?internal_encoding: encoding, ?encoding: encoding, ?textmode: boolish, ?binmode: boolish, ?autoclose: boolish, ?chomp: boolish) { (String) -> untyped } -> nil
               | (Integer limit, ?mode: Integer | String, ?flags: Integer, ?external_encoding: encoding, ?internal_encoding: encoding, ?encoding: encoding, ?textmode: boolish, ?binmode: boolish, ?autoclose: boolish, ?chomp: boolish) { (String) -> untyped } -> nil
               | (?String sep, ?Integer limit, ?mode: Integer | String, ?flags: Integer, ?external_encoding: encoding, ?internal_encoding: encoding, ?encoding: encoding, ?textmode: boolish, ?binmode: boolish, ?autoclose: boolish, ?chomp: boolish) -> Enumerator[String, nil]
               | (Integer limit, ?mode: Integer | String, ?flags: Integer, ?external_encoding: encoding, ?internal_encoding: encoding, ?encoding: encoding, ?textmode: boolish, ?binmode: boolish, ?autoclose: boolish, ?chomp: boolish) -> Enumerator[String, nil]

  def empty?: () -> bool

  def entries: () -> Array[Pathname]

  def eql?: (untyped) -> bool

  def executable?: () -> bool

  def executable_real?: () -> bool

  def exist?: () -> bool

  def expand_path: (?String dir) -> Pathname

  def extname: () -> String

  def file?: () -> bool

  def fnmatch: (String pattern, ?Integer flags) -> bool

  alias fnmatch? fnmatch

  def freeze: () -> Pathname

  def ftype: () -> String

  def glob: (String | Array[String] pattern, ?Integer flags) -> Array[Pathname]
          | (String | Array[String] pattern, ?Integer flags) { (Pathname) -> untyped } -> nil

  def grpowned?: () -> bool

  def hash: () -> Integer

  def inspect: () -> String

  def join: (*String | _ToStr | Pathname args) -> Pathname

  def lchmod: (Integer mode) -> Integer

  def lchown: (Integer owner, Integer group) -> Integer

  def lstat: () -> ::File::Stat

  def lutime: (Time | Numeric atime, Time | Numeric mtime) -> Integer

  def make_link: (String | Pathname | _ToStr old) -> Integer

  def make_symlink: (String | Pathname | _ToStr old) -> Integer

  def mkdir: (?Integer perm) -> Integer

  def mkpath: () -> self

  def mountpoint?: () -> bool

  def mtime: () -> Time

  def open: (?string | int mode, ?int perm) -> File
          | [T] (?string | int mode, ?int perm) { (File) -> T } -> T

  def opendir: () -> Dir
             | [U] () { (Dir) -> U } -> U

  def owned?: () -> bool

  def parent: () -> Pathname

  def pipe?: () -> bool

  def read: (?Integer length, ?Integer offset, ?mode: Integer | String, ?flags: Integer, ?external_encoding: encoding, ?internal_encoding: encoding, ?encoding: encoding, ?textmode: boolish, ?binmode: boolish, ?autoclose: boolish) -> String

  def readable?: () -> bool

  def readable_real?: () -> bool

  def readlines: (?String sep, ?Integer limit, ?mode: Integer | String, ?flags: Integer, ?external_encoding: encoding, ?internal_encoding: encoding, ?encoding: encoding, ?textmode: boolish, ?binmode: boolish, ?autoclose: boolish, ?chomp: boolish) -> Array[String]
               | (Integer limit, ?mode: Integer | String, ?flags: Integer, ?external_encoding: encoding, ?internal_encoding: encoding, ?encoding: encoding, ?textmode: boolish, ?binmode: boolish, ?autoclose: boolish, ?chomp: boolish) -> Array[String]

  def readlink: () -> untyped

  def realdirpath: (?string | Pathname base_dir) -> Pathname

  def realpath: (?string | Pathname base_dir) -> Pathname

  def relative?: () -> bool

  def relative_path_from: (Pathname | string base_directory) -> Pathname

  def rename: (Pathname | string new_name) -> 0

  def rmdir: () -> 0

  def root?: () -> bool

  def setgid?: () -> bool

  def setuid?: () -> bool

  def size: () -> Integer

  def size?: () -> Integer?

  def socket?: () -> untyped

  def split: () -> [ Pathname, Pathname ]

  def stat: () -> File::Stat

  def sticky?: () -> untyped

  def sub: (Regexp | string pattern, string | Hash[String, String] replacement) -> Pathname
         | (Regexp | string pattern) { (String match) -> string } -> Pathname

  def sub_ext: (string replacement) -> Pathname

  def symlink?: () -> untyped

  def sysopen: (?String mode, ?Integer perm) -> Integer

  def taint: () -> Pathname

  def to_path: () -> String

  alias to_s to_path

  def truncate: (Integer length) -> 0

  def unlink: () -> Integer

  def untaint: () -> Pathname

  def utime: (Integer | Time atime, Integer | Time mtime) -> Integer

  def world_readable?: () -> (Integer | nil)

  def world_writable?: () -> (Integer | nil)

  def writable?: () -> bool

  def writable_real?: () -> bool

  def write: (String content, ?Integer offset, ?mode: Integer | String, ?flags: Integer, ?external_encoding: encoding, ?internal_encoding: encoding, ?encoding: encoding, ?textmode: boolish, ?binmode: boolish, ?autoclose: boolish) -> Integer

  def zero?: () -> bool

  private

  def add_trailing_separator: (untyped path) -> untyped

  def chop_basename: (untyped path) -> untyped

  def cleanpath_aggressive: () -> untyped

  def cleanpath_conservative: () -> untyped

  def del_trailing_separator: (untyped path) -> untyped

  def has_trailing_separator?: (untyped path) -> untyped

  def initialize: (string | Pathname) -> void

  def plus: (untyped path1, untyped path2) -> untyped

  def prepend_prefix: (untyped prefix, untyped relpath) -> untyped

  def split_names: (untyped path) -> untyped

  SAME_PATHS: Proc

  SEPARATOR_LIST: String

  SEPARATOR_PAT: Regexp

  TO_PATH: Symbol
end

%a{annotate:rdoc:skip}
module Kernel
  private

  def self?.Pathname: (string | Pathname) -> Pathname
end
