class Proc
  interface _Callable
    def call: (?) -> untyped
  end

  def self.new: () { (?) -> untyped } -> instance

  def clone: () -> self

  alias === call

  alias yield call

  def <<: (_Callable callable) -> Proc

  def >>: (_Callable callable) -> Proc

  def ==: (untyped other) -> bool

  alias eql? ==

  def arity: () -> Integer

  def binding: () -> Binding

  def call: (?) -> untyped

  alias [] call

  def curry: (?int? arity) -> Proc

  def hash: () -> Integer

  def lambda?: () -> bool

  def parameters: (?lambda: boolish) -> Method::param_types

  def source_location: () -> [String, Integer]?

  def to_proc: () -> self

  def to_s: () -> String

  alias inspect to_s
end
