class Random < RBS::Unnamed::Random_Base
  def initialize: (?Integer seed) -> void

  def self.bytes: (Integer size) -> String

  def ==: (untyped arg0) -> bool

  def self.new_seed: () -> Integer

  def self.rand: (?0) -> Float
               | (Integer | ::Range[Integer] max) -> Integer
               | (Float | ::Range[Float] max) -> Float
               | [T < Numeric] (::Range[T]) -> T

  def self.seed: () -> ::Integer

  def self.srand: (?Integer number) -> Integer

  def self.urandom: (Integer) -> String

  def seed: () -> Integer

  private

  def initialize_copy: (self object) -> self

  def left: () -> untyped

  def marshal_dump: () -> untyped

  def marshal_load: (untyped) -> untyped

  def state: () -> untyped
end

class Random::Base < RBS::Unnamed::Random_Base
end

module Random::Formatter
  include RBS::Unnamed::Random_Formatter
end
