class Rational < Numeric
  def %: (Integer) -> Rational
       | (Float) -> Float
       | (Rational) -> Rational
       | (Numeric) -> Numeric

  def *: (Integer) -> Rational
       | (Rational) -> Rational
       | [T < Numeric](T) -> T

  def **: (Complex) -> Complex
        | (Numeric) -> Numeric

  def +: (Float) -> Float
       | (Complex) -> Complex
       | (Numeric) -> Rational

  def -: (Float) -> Float
       | (Complex) -> Complex
       | (Numeric) -> Rational

  def -@: () -> Rational

  def /: (Float) -> Float
       | (Complex) -> Complex
       | (Numeric) -> Rational

  def <=>: (Integer | Rational) -> Integer
         | (untyped) -> Integer?

  def ==: (untyped) -> bool

  def abs: () -> Rational

  def ceil: () -> Integer
          | (Integer digits) -> (Integer | Rational)

  def coerce: (Numeric) -> [ Numeric, Numeric ]

  def denominator: () -> Integer

  def divmod: (Integer | Float | Rational) -> [ Integer, Rational ]
            | (Numeric) -> [ Numeric, Numeric ]

  def fdiv: (Numeric) -> Float

  def floor: () -> Integer
           | (Integer digits) -> (Integer | Rational)

  def hash: () -> Integer

  def inspect: () -> String

  alias magnitude abs

  def modulo: (Float) -> Float
            | (Numeric) -> Rational

  def negative?: () -> bool

  def numerator: () -> Integer

  def polar: () -> [ Rational, Integer | Float ]

  def positive?: () -> bool

  def quo: (Float) -> Float
         | (Complex) -> Complex
         | (Numeric) -> Rational

  def rationalize: (?Numeric eps) -> Rational

  def rect: () -> [ Rational, Numeric ]

  def remainder: (Float) -> Float
               | (Numeric) -> Rational

  def round: (?half: :up | :down | :even) -> Integer
           | (Integer digits, ?half: :up | :down | :even) -> (Integer | Rational)

  def to_f: () -> Float

  def to_i: () -> Integer

  def to_r: () -> Rational

  def to_s: () -> String

  def truncate: () -> Integer
              | (Integer ndigits) -> (Integer | Rational)
end
