module RbConfig
  CONFIG: Hash[String, String]

  DESTDIR: String

  MAKEFILE_CONFIG: Hash[String, String]

  TOPDIR: String

  def self.expand: (String val, ?Hash[String, String] config) -> String

  def self.fire_update!: (String key, String val, ?Hash[String, String] mkconf, ?Hash[String, String] conf) -> Array[String]?

  def self.ruby: () -> String
end
