class Regexp
  interface _ToRegexp
    def to_regexp: () -> Regexp
  end

  class TimeoutError < RegexpError
  end

  EXTENDED: Integer

  FIXEDENCODING: Integer

  IGNORECASE: Integer

  MULTILINE: Integer

  NOENCODING: Integer

  alias self.compile self.new

  def self.escape: (interned str) -> String

  def self.last_match: () -> MatchData?
                     | (MatchData::capture capture) -> String?

  def self.linear_time?: (Regexp regex, ?nil, ?timeout: untyped) -> bool
                       | (string regex, ?int | string | bool | nil options, ?timeout: untyped) -> bool

  alias self.quote self.escape

  def self.try_convert: (Regexp | _ToRegexp regexp_like) -> Regexp
                      | (untyped other) -> Regexp?

  def self.timeout: () -> Float?

  def self.timeout=: [T < _ToF] (T timeout) -> T

  def self.union: (*Regexp | _ToRegexp | string patterns) -> Regexp
                | (array[Regexp | _ToRegexp | string] patterns) -> Regexp
                | (Symbol | [Symbol] symbol_pattern) -> Regexp

  def initialize: (Regexp regexp, ?timeout: _ToF?) -> void
                | (string pattern, ?int | string | bool | nil options, ?timeout: _ToF?) -> void

  def initialize_copy: (self object) -> self

  def ==: (untyped other) -> bool

  def ===: (untyped other) -> bool

  def =~: (interned? string) -> Integer?
        | (nil) -> nil

  def casefold?: () -> bool

  def encoding: () -> Encoding

  alias eql? ==

  def fixed_encoding?: () -> bool

  def hash: () -> Integer

  def inspect: () -> String

  def match: (interned? str, ?int offset) -> MatchData?
           | [T] (interned? str, ?int offset) { (MatchData matchdata) -> T } -> T?
           | (nil, ?int offset) ?{ (MatchData matchdata) -> void } -> nil

  def match?: (interned str, ?int offset) -> bool
            | (nil, ?int offset) -> false

  def named_captures: () -> Hash[String, Array[Integer]]

  def names: () -> Array[String]

  def options: () -> Integer

  def source: () -> String

  def to_s: () -> String

  %a{pure}
  def timeout: () -> Float?

  def ~: () -> Integer?
end
