module Ruby
  COPYRIGHT: ::String

  DESCRIPTION: ::String

  ENGINE: ::String

  ENGINE_VERSION: ::String

  PATCHLEVEL: ::Integer

  PLATFORM: ::String

  RELEASE_DATE: ::String

  REVISION: ::String

  VERSION: ::String
end
