class RubyVM < Object
end

RubyVM::DEFAULT_PARAMS: Hash[Symbol, Integer]

RubyVM::INSTRUCTION_NAMES: Array[String]

RubyVM::OPTS: Array[String]

class RubyVM::InstructionSequence < Object
  def absolute_path: () -> String?

  def base_label: () -> String

  def disasm: () -> String

  def disassemble: () -> String

  def each_child: () -> RubyVM::InstructionSequence

  def eval: () -> untyped

  def first_lineno: () -> Integer

  def inspect: () -> String

  def label: () -> String

  def path: () -> String

  def script_lines: () -> Array[String]?

  def to_a: () -> Array[untyped]

  def to_binary: () -> String

  def trace_points: () -> Array[untyped]
end

module RubyVM::AbstractSyntaxTree
  def self.parse: (String string, ?keep_script_lines: bool, ?error_tolerant: bool, ?keep_tokens: bool) -> Node

  def self.parse_file: (path string, ?keep_script_lines: bool, ?error_tolerant: bool, ?keep_tokens: bool) -> Node

  def self.of: (Proc | Method | UnboundMethod body, ?keep_script_lines: bool, ?error_tolerant: bool, ?keep_tokens: bool) -> Node?

  def self.node_id_for_backtrace_location: (Thread::Backtrace::Location backtrace_location) -> Integer

  class Node
    def type: () -> Symbol

    def first_lineno: () -> Integer

    def first_column: () -> Integer

    def last_lineno: () -> Integer

    def last_column: () -> Integer

    def locations: () -> Array[Location]

    def tokens: () -> Array[[Integer, Symbol, String, [Integer, Integer, Integer, Integer]]]?

    def all_tokens: () -> Array[[Integer, Symbol, String, [Integer, Integer, Integer, Integer]]]?

    def children: () -> Array[untyped]
  end

  class Location
    def first_column: () -> Integer

    def first_lineno: () -> Integer

    def inspect: () -> String

    def last_lineno: () -> Integer

    def last_column: () -> Integer
  end
end

module RubyVM::YJIT
  def self.code_gc: () -> void

  def self.dump_exit_locations: (untyped filename) -> void

  def self.enable: (?stats: false | true | :quiet) -> void

  def self.enabled?: () -> bool

  def self.format_number: (untyped pad, untyped number) -> untyped

  def self.format_number_pct: (untyped pad, untyped number, untyped total) -> untyped

  def self.reset_stats!: () -> void

  def self.runtime_stats: (?context: bool) -> Hash[untyped, untyped]?

  def self.stats_enabled?: () -> bool

  def self.stats_string: () -> String
end

module RubyVM::RJIT
end
