module Signal
  def self?.list: () -> Hash[String, Integer]

  def self?.signame: (int signo) -> String?

  def self?.trap: (Integer | interned signal) { (Integer) -> void } -> trap_command
                | (Integer | interned signal, trap_command command) -> trap_command

  type trap_command = string | bool | nil | _TrapCommand

  interface _TrapCommand
    def call: (Integer signo) -> void
  end
end
