class String
  include Comparable

  type selector = string

  def self.try_convert: (String object) -> String # technically will return `object` unchanged.
                      | (_ToStr object) -> String
                      | (untyped object) -> String?

  def initialize: (?string source, ?encoding: encoding, ?capacity: int) -> void

  alias initialize_copy replace

  def %: (array[untyped] positional_args) -> String
       | (hash[Symbol, untyped] named_args) -> String
       | (untyped arg) -> String

  def *: (int amount) -> String

  def +: (string other_string) -> String

  def +@: () -> self

  def -@: () -> self

  def <<: (string | Integer str_or_codepoint) -> self

  def <=>: (string) -> (-1 | 0 | 1)
         | (untyped) -> (-1 | 0 | 1)?

  def ==: (untyped other) -> bool

  alias === ==

  def =~: (Regexp regex) -> Integer?
        | [T] (_MatchAgainst[self, T] object) -> T

  interface _MatchAgainst[O, T]
    def =~: (O string) -> T
  end

  def []: (int start, ?int length) -> String?
        | (range[int?] range) -> String?
        | (Regexp regexp, ?MatchData::capture backref) -> String?
        | (String substring) -> String?

  def []=: [T < _ToStr] (int index, T replacement) -> T
         | [T < _ToStr] (int start, int length, T replacement) -> T
         | [T < _ToStr] (range[int?] range, T replacement) -> T
         | [T < _ToStr] (Regexp regexp, T replacement) -> T
         | [T < _ToStr] (Regexp regexp, MatchData::capture backref, T replacement) -> T
         | [T < _ToStr] (String substring, T replacement) -> T

  def append_as_bytes: (String) -> String

  def ascii_only?: () -> bool

  def b: () -> String

  def byteindex: (Regexp | string pattern, ?int offset) -> Integer?

  def byterindex: (Regexp | string pattern, ?int offset) -> Integer?

  def bytes: () -> Array[Integer]
           | () { (Integer byte) -> void } -> self

  def bytesize: () -> Integer

  def byteslice: (int start, ?int length) -> String?
               | (range[int?] range) -> String?

  def bytesplice: (Integer start, int length, string str) -> String
                | (int start, int length, string str, int str_start, int str_length) -> String
                | (range[int?] range, string str, ?range[int?] str_range) -> String

  def capitalize: () -> String
                | (:ascii | :lithuanian | :turkic) -> String
                | (:lithuanian, :turkic) -> String
                | (:turkic, :lithuanian) -> String

  def capitalize!: () -> self?
                 | (:ascii | :lithuanian | :turkic) -> self?
                 | (:lithuanian, :turkic) -> self?
                 | (:turkic, :lithuanian) -> self?

  def casecmp: (string other) -> (-1 | 0 | 1)
             | (untyped) -> (-1 | 0 | 1)?

  def casecmp?: (string other) -> bool
              | (untyped) -> bool?

  def center: (int width, ?string pad_string) -> String

  def chars: () -> Array[String]
           | () { (String char) -> void } -> self

  def chomp: (?string? separator) -> String

  def chomp!: (nil) -> nil
            | (?string? separator) -> self?

  def chop: () -> String

  def chop!: () -> self?

  def chr: () -> String

  def clear: () -> self

  def codepoints: () -> Array[Integer]
                | () { (Integer codepoint) -> void } -> self

  def concat: (*string | Integer string_or_codepoints) -> self

  def count: (selector selector_0, *selector more_selectors) -> Integer

  %a{deprecated}
  def crypt: (string salt_str) -> String

  alias dedup -@

  def delete: (selector selector_0, *selector more_selectors) -> String

  def delete!: (selector selector_0, *selector more_selectors) -> self?

  def delete_prefix: (string prefix) -> String

  def delete_prefix!: (string prefix) -> self?

  def delete_suffix: (string suffix) -> String

  def delete_suffix!: (string suffix) -> self?

  def downcase: () -> String
              | (:ascii | :fold | :lithuanian | :turkic) -> String
              | (:lithuanian, :turkic) -> String
              | (:turkic, :lithuanian) -> String

  def downcase!: () -> self?
               | (:ascii | :fold | :lithuanian | :turkic) -> self?
               | (:lithuanian, :turkic) -> self?
               | (:turkic, :lithuanian) -> self?

  def dump: () -> String

  def each_byte: () -> Enumerator[Integer, self]
               | () { (Integer byte) -> void } -> self

  def each_char: () -> Enumerator[String, self]
               | () { (String char) -> void } -> self

  def each_codepoint: () -> Enumerator[Integer, self]
                    | () { (Integer codepoint) -> void } -> self

  def each_grapheme_cluster: () -> Enumerator[String, self]
                           | () { (String grapheme_cluter) -> void } -> self

  def each_line: (?string? separator, ?chomp: boolish) -> Enumerator[String, self]
               | (?string? separator, ?chomp: boolish) { (String line) -> void } -> self

  def empty?: () -> bool

  def encode: (
    ?encoding source_encoding,
    ?encoding? from_encoding,
    ?invalid: :replace ?,
    ?undef: :replace ?,
    ?replace: string?,
    ?xml: (:text | :attr)?,
    ?newline: (:universal | :crlf | :cr | :lf)?,
    ?universal_newline: boolish,
    ?cr_newline: boolish,
    ?crlf_newline: boolish,
    ?lf_newline: boolish,
    ?fallback: ^(String) -> string? | Method | _EncodeFallbackAref
  ) -> self

  interface _EncodeFallbackAref
    def []: (String) -> string?
  end

  def encode!: (
    ?encoding source_encoding,
    ?encoding? from_encoding,
    ?invalid: :replace ?,
    ?undef: :replace ?,
    ?replace: string?,
    ?xml: (:text | :attr)?,
    ?newline: (:universal | :crlf | :cr | :lf)?,
    ?universal_newline: boolish,
    ?cr_newline: boolish,
    ?crlf_newline: boolish,
    ?lf_newline: boolish,
    ?fallback: ^(String) -> string? | Method | _EncodeFallbackAref
  ) -> self

  def encoding: () -> Encoding

  def end_with?: (*string suffixes) -> bool

  def eql?: (untyped other) -> bool

  def force_encoding: (encoding enc) -> self

  def freeze: () -> self

  def getbyte: (int index) -> Integer?

  def grapheme_clusters: () -> Array[String]
                       | () { (String grapheme_cluter) -> void } -> self

  def gsub: (Regexp | string pattern, string | hash[String, _ToS] replacement) -> String
          | (Regexp | string pattern) -> Enumerator[String, String]
          | (Regexp | string pattern) { (String match) -> _ToS } -> String

  def gsub!: (Regexp | string pattern, string | hash[String, _ToS] replacement) -> self?
           | (Regexp | string pattern) -> Enumerator[String, self?]
           | (Regexp | string pattern) { (String match) -> _ToS } -> self?

  def hash: () -> Integer

  def hex: () -> Integer

  def include?: (string other_string) -> bool

  def index: (Regexp | string pattern, ?int offset) -> Integer?

  def insert: (int index, string other_str) -> self

  def inspect: () -> String

  def intern: () -> Symbol

  def length: () -> Integer

  def lines: (?string? separator, ?chomp: boolish) -> Array[String]
           | (?string? separator, ?chomp: boolish) { (String line) -> void } -> self

  def ljust: (int size, ?string pad_string) -> String

  def lstrip: (*selector) -> String

  def lstrip!: (*selector) -> self?

  def match: (Regexp | string pattern, ?int offset) -> MatchData?
           | [T] (Regexp | string pattern, ?int offset) { (MatchData matchdata) -> T } -> T?

  def match?: (Regexp | string pattern, ?int offset) -> bool

  alias next succ

  alias next! succ!

  def oct: () -> Integer

  def ord: () -> Integer

  def partition: (Regexp | string pattern) -> [String, String, String]

  def prepend: (*string other_strings) -> self

  def replace: (string other_string) -> self

  def reverse: () -> String

  def reverse!: () -> self

  def rindex: (Regexp | string pattern, ?int offset) -> Integer?

  def rjust: (int size, ?string pad_string) -> String

  def rpartition: (Regexp | string pattern) -> [String, String, String]

  def rstrip: (*selector) -> String

  def rstrip!: (*selector) -> self?

  def scan: (Regexp pattern) -> Array[String | Array[String?]]
          | (Regexp pattern) { (String | Array[String?] matches) -> void } -> self
          | (string pattern) -> Array[String]
          | (string pattern) { (String match) -> void } -> self

  def scrub: (?string? replacement) -> String
           | (?nil) { (String bytes) -> string } -> String

  def scrub!: (?string? replacement) -> self
            | (?nil) { (String bytes) -> string } -> self

  def setbyte: [T < _ToInt] (int index, T byte) -> T

  alias size length

  alias slice []

  def slice!: (int index, ?int length) -> String?
            | (range[int?] range) -> String?
            | (String substring) -> String?
            | (Regexp regexp, ?MatchData::capture backref) -> String?

  def split: (?Regexp | string | nil pattern, ?int limit) -> Array[String]
           | (?Regexp | string | nil pattern, ?int limit) { (String substring) -> void } -> self

  def squeeze: (*selector selectors) -> String

  def squeeze!: (*selector selectors) -> self?

  def start_with?: (*Regexp | string prefixes) -> bool

  def strip: (*selector) -> String

  def strip!: (*selector) -> self?

  def sub: (Regexp | string pattern, string | hash[String, _ToS] replacement) -> String
         | (Regexp | string pattern) { (String match) -> _ToS } -> String

  def sub!: (Regexp | string pattern, string | hash[String, _ToS] replacement) -> self?
          | (Regexp | string pattern) { (String match) -> _ToS } -> self?

  def succ: () -> String

  def succ!: () -> self

  def sum: (?int bits) -> Integer

  def swapcase: () -> String
              | (:ascii | :lithuanian | :turkic) -> String
              | (:lithuanian, :turkic) -> String
              | (:turkic, :lithuanian) -> String

  def swapcase!: () -> self?
               | (:ascii | :lithuanian | :turkic) -> self?
               | (:lithuanian, :turkic) -> self?
               | (:turkic, :lithuanian) -> self?

  def to_c: () -> Complex

  def to_f: () -> Float

  def to_i: (?int radix) -> Integer

  def to_r: () -> Rational

  def to_s: () -> String

  alias to_str to_s

  alias to_sym intern

  def tr: (selector source, string relpacement) -> String

  def tr!: (selector source, string relpacement) -> self?

  def tr_s: (selector source, string replacement) -> String

  def tr_s!: (selector source, string replacement) -> self?

  def undump: () -> String

  def unicode_normalize: (?:nfc | :nfd | :nfkc | :nfkd form) -> self

  def unicode_normalize!: (?:nfc | :nfd | :nfkc | :nfkd form) -> self

  def unicode_normalized?: (?:nfc | :nfd | :nfkc | :nfkd) -> bool

  def unpack: (string template, ?offset: int) -> Array[Integer | Float | String | nil]
            | (string template, ?offset: int) { (Integer | Float | String | nil value) -> void } -> nil

  def unpack1: (string template, ?offset: int) -> (Integer | Float | String)?

  def upcase: () -> String
            | (:ascii | :lithuanian | :turkic) -> String
            | (:lithuanian, :turkic) -> String
            | (:turkic, :lithuanian) -> String

  def upcase!: () -> self?
             | (:ascii | :lithuanian | :turkic) -> self?
             | (:lithuanian, :turkic) -> self?
             | (:turkic, :lithuanian) -> self?

  def upto: (string other_string, ?boolish exclusive) -> Enumerator[String, self]
          | (string other_string, ?boolish exclusive) { (String s) -> void } -> self

  def valid_encoding?: () -> bool
end

%a{deprecated}
interface _ArefFromStringToString
  def []: (String) -> String
end

%a{deprecated}
type String::encode_fallback = Hash[String, String] | Proc | Method | String::_ArefFromStringToString

interface String::_ArefFromStringToString
  def []: (String) -> String
end
