class Symbol
  include Comparable

  def self.all_symbols: () -> Array[Symbol]

  def <=>: (Symbol object) -> (-1 | 0 | 1)
         | (untyped) -> (-1 | 0 | 1)?

  def ==: (untyped object) -> bool

  alias === ==

  def =~: (Regexp regex) -> Integer?
        | [T] (String::_MatchAgainst[String, T] object) -> T

  def []: (int start, ?int length) -> String?
        | (range[int?] range) -> String?
        | (Regexp regexp, ?MatchData::capture backref) -> String?
        | (String substring) -> String?

  def capitalize: () -> Symbol
                | (:ascii | :lithuanian | :turkic) -> Symbol
                | (:lithuanian, :turkic) -> Symbol
                | (:turkic, :lithuanian) -> Symbol

  def casecmp: (untyped object) -> (-1 | 0 | 1)?

  def casecmp?: (untyped object) -> bool?

  def downcase: () -> Symbol
              | (:ascii | :fold | :lithuanian | :turkic) -> Symbol
              | (:lithuanian, :turkic) -> Symbol
              | (:turkic, :lithuanian) -> Symbol

  def empty?: () -> bool

  def encoding: () -> Encoding

  def end_with?: (*string suffixes) -> bool

  alias id2name to_s

  def inspect: () -> String

  alias intern to_sym

  def length: () -> Integer

  def match: (Regexp | string pattern, ?int offset) -> MatchData?
           | [T] (Regexp | string pattern, ?int offset) { (MatchData matchdata) -> T } -> T?

  def match?: (Regexp | string pattern, ?int offset) -> bool

  def next: () -> Symbol

  def name: () -> String

  alias size length

  alias slice []

  def start_with?: (*Regexp | string prefixes) -> bool

  alias succ next

  def swapcase: () -> Symbol
              | (:ascii | :lithuanian | :turkic) -> Symbol
              | (:lithuanian, :turkic) -> Symbol
              | (:turkic, :lithuanian) -> Symbol

  def to_proc: () -> Proc

  def to_s: () -> String

  def to_sym: () -> self

  def upcase: () -> Symbol
            | (:ascii | :lithuanian | :turkic) -> Symbol
            | (:lithuanian, :turkic) -> Symbol
            | (:turkic, :lithuanian) -> Symbol
end
