class Time < Object
  interface _Timeout
    def divmod: (1) -> [int, _TimeoutNSecs]
  end

  interface _TimeoutNSecs
    def *: (1_000_000_000) -> int
  end

  include Comparable

  def self.at: (Time, ?in: String | Integer | nil) -> Time
             | (Numeric, ?in: String | Integer | nil) -> Time
             | (Integer sec_i, Numeric msec, subsec_unit msec, ?in: String | Integer | nil) -> Time

  type subsec_unit = :msec | :millisecond | :usec | :microsecond | :nsec | :nanosecond

  def self.gm: (Integer year, ?Integer | String month, ?Integer day, ?Integer hour, ?Integer min, ?Numeric sec, ?Numeric usec_with_frac) -> Time

  def self.local: (Integer year, ?Integer | String month, ?Integer day, ?Integer hour, ?Integer min, ?Numeric sec, ?Numeric usec_with_frac) -> Time

  def self.now: (?in: String | Integer | nil) -> Time

  def self.utc: (Integer year, ?Integer | String month, ?Integer day, ?Integer hour, ?Integer min, ?Numeric sec, ?Numeric usec_with_frac) -> Time

  def +: (Numeric arg0) -> Time

  def -: (Time arg0) -> Float
       | (Numeric arg0) -> Time

  def <: (Time arg0) -> bool

  def <=: (Time arg0) -> bool

  def <=>: (Time other) -> Integer
         | (untyped other) -> Integer?

  def >: (Time arg0) -> bool

  def >=: (Time arg0) -> bool

  def asctime: () -> String

  def ctime: () -> String

  def day: () -> Integer

  def deconstruct_keys: (Array[Symbol]?) -> Hash[Symbol, Integer]

  def dst?: () -> bool

  def eql?: (untyped arg0) -> bool

  def friday?: () -> bool

  def getgm: () -> Time

  def getlocal: (?Integer utc_offset) -> Time

  def getutc: () -> Time

  def gmt?: () -> bool

  def gmt_offset: () -> Integer

  def gmtime: () -> Time

  def hash: () -> Integer

  def hour: () -> Integer

  def initialize: (?Integer year, ?Integer? month, ?Integer? day, ?Integer? hour, ?Integer? min, ?Numeric? sec, ?String | Integer | nil) -> void
                | (?Integer year, ?Integer? month, ?Integer? day, ?Integer? hour, ?Integer? min, ?Numeric? sec, in: String | Integer | nil) -> void
                | (String, ?in: string | int | nil, ?precision: int) -> void

  def inspect: () -> String

  def isdst: () -> bool

  alias iso8601 xmlschema

  def localtime: (?String utc_offset) -> Time

  def mday: () -> Integer

  def min: () -> Integer

  def mon: () -> Integer

  def monday?: () -> bool

  def nsec: () -> Integer

  def round: (?int ndigits) -> Time

  def saturday?: () -> bool

  def sec: () -> Integer

  def strftime: (String arg0) -> String

  def subsec: () -> (0 | Rational)

  def sunday?: () -> bool

  def thursday?: () -> bool

  def to_a: () -> [ Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, bool, String? ]

  def to_f: () -> Float

  def to_i: () -> Integer

  def to_r: () -> Rational

  def to_s: () -> String

  def tuesday?: () -> bool

  def tv_nsec: () -> Integer

  def tv_sec: () -> Integer

  def tv_usec: () -> Integer

  def usec: () -> Integer

  def utc: () -> Time

  def utc?: () -> bool

  def utc_offset: () -> Integer

  def wday: () -> Integer

  def wednesday?: () -> bool

  def xmlschema: (?Integer fraction_digits) -> String

  def yday: () -> Integer

  def year: () -> Integer

  def zone: () -> String?

  def self.mktime: (Integer year, ?Integer | String month, ?Integer day, ?Integer hour, ?Integer min, ?Numeric sec, ?Numeric usec_with_frac) -> Time

  def gmtoff: () -> Integer

  def month: () -> Integer

  def floor: (?int ndigits) -> Time

  def ceil: (?int ndigits) -> Time
end

Time::RFC2822_DAY_NAME: Array[String]

Time::RFC2822_MONTH_NAME: Array[String]
