class TracePoint
  def self.new: (*_ToSym events) { (instance tp) -> void } -> instance

  def self.allow_reentry: [T] () { (nil) -> T } -> T

  def self.stat: () -> untyped

  def self.trace: (*_ToSym events) { (instance tp) -> void } -> instance

  def binding: () -> Binding?

  def callee_id: () -> Symbol?

  def defined_class: () -> (Class | Module)?

  def disable: () -> bool
             | [T] () { () -> T } -> T

  def enable: (?target: Method | UnboundMethod | RubyVM::InstructionSequence | Proc | nil, ?target_line: int?, ?target_thread: Thread | :default | nil) -> bool
            | [T] (?target: Method | UnboundMethod | RubyVM::InstructionSequence | Proc | nil, ?target_line: int?, ?target_thread: Thread | :default | nil) { () -> T } -> T

  def enabled?: () -> bool

  def event: () -> ::Symbol

  def inspect: () -> String

  def lineno: () -> Integer

  def method_id: () -> Symbol?

  def path: () -> String

  def parameters: () -> Method::param_types?

  def raised_exception: () -> Exception

  def return_value: () -> untyped

  def self: () -> untyped

  def eval_script: () -> String?

  def instruction_sequence: () -> RubyVM::InstructionSequence
end
