class TrueClass
  def !: () -> false

  def &: (false | nil) -> false
       | (untyped obj) -> bool

  def ===: (true) -> true
         | (untyped obj) -> bool

  def ^: (false | nil) -> true
       | (untyped obj) -> bool

  alias inspect to_s

  def to_s: () -> "true"

  def |: (untyped obj) -> true
end
