class UnboundMethod
  def ==: (untyped other) -> bool

  alias eql? ==

  def hash: () -> Integer

  def clone: () -> self

  def arity: () -> Integer

  def bind: (untyped obj) -> Method

  def inspect: () -> String

  alias to_s inspect

  def name: () -> Symbol

  def owner: () -> (Class | Module)

  def parameters: () -> Method::param_types

  def source_location: () -> [String, Integer]?

  def super_method: () -> UnboundMethod?

  def original_name: () -> Symbol

  def bind_call: (untyped recv, *untyped, **untyped) ?{ (?) -> untyped } -> untyped
end
