module Warning
  type category = :deprecated | :experimental | :performance

  def self.[]: (category) -> bool

  def self.[]=: [T] (category, T flag) -> T

  def self.categories: () -> Array[Symbol]

  def self?.warn: (String message, ?category: category?) -> nil
end
