class PP < PrettyPrint
  interface _PrettyPrint
    def pretty_print: (untyped q) -> untyped

    def pretty_print_cycle: (untyped q) -> untyped

    def is_a?: (Module) -> bool
  end

  interface _LeftShift
    def <<: (untyped obj) -> self
  end

  interface _PPMethodsRequired
    def text: (String obj, ?Integer width) -> void

    def breakable: (?String sep, ?Integer width) -> void

    def group: (?Integer indent, ?String open_obj, ?String close_obj, ?Integer open_width, ?Integer close_width) { () -> untyped } -> void
  end

  module PPMethods : _PPMethodsRequired
    def guard_inspect_key: () { () -> untyped } -> void

    def check_inspect_key: (_PrettyPrint id) -> bool

    def push_inspect_key: (_PrettyPrint id) -> void

    def pop_inspect_key: (_PrettyPrint id) -> void

    def pp: (_PrettyPrint obj) -> untyped

    def object_group: (untyped obj) { () -> untyped } -> Integer

    def object_address_group: (untyped obj) { () -> untyped } -> Integer

    def comma_breakable: () -> void

    def seplist: (untyped list, ?(^() -> void)? sep, ?interned iter_method) { (*untyped, **untyped) -> void } -> void

    def pp_object: (untyped obj) -> untyped

    def pp_hash: (untyped obj) -> untyped
  end
  include PPMethods

  class SingleLine < ::PrettyPrint::SingleLine
    include PPMethods
  end

  module ObjectMixin : BasicObject
    def pretty_print: (PP q) -> untyped

    def pretty_print_cycle: (PP q) -> untyped

    def pretty_print_instance_variables: () -> Array[Symbol]

    def pretty_print_inspect: () -> untyped
  end

  def self.width_for: (untyped out) -> Integer

  def self.pp: (_PrettyPrint obj, ?_LeftShift out, ?Integer width) -> untyped

  def self.singleline_pp: (_PrettyPrint obj, ?_LeftShift out) -> untyped
  def self.mcall: (untyped obj, Module mod, interned meth, *untyped args) ?{ (*untyped, **untyped) -> untyped } -> untyped

  attr_accessor self.sharing_detection: bool?
end

%a{annotate:rdoc:skip}
class RubyVM::AbstractSyntaxTree::Node
  def pretty_print_children: (PP q, ?Array[untyped] names) -> void
end

%a{annotate:rdoc:skip}
class Object
  include PP::ObjectMixin
end

%a{annotate:rdoc:skip}
module Kernel
  def pretty_inspect: () -> String
end
