%a{annotate:rdoc:skip}
class IO
  class Buffer
    include Comparable

    def self.for: (String) -> Buffer

    def self.map: (File file, ?Integer? size, ?Integer offset, ?Integer flags) -> Buffer

    def self.string: (int) { (Buffer) -> void } -> String

    def <=>: (Buffer) -> Integer

    def clear: (?Integer value, ?Integer offset, ?Integer length) -> self

    def copy: (Buffer source, ?Integer offset, ?Integer length, ?Integer source_offset) -> Integer

    def empty?: () -> bool

    def external?: () -> bool

    def free: () -> self

    def get_string: (?Integer offset, ?Integer length, ?Encoding encoding) -> String

    def get_value: (int_get_type, Integer offset) -> Integer
                 | (float_get_type, Integer offset) -> Float

    type int_get_type = :U8 | :S8
                      | :u16 | :U16 | :s16 | :S16
                      | :u32 | :U32 | :s32 | :S32
                      | :u64 | :U64 | :s64 | :S64

    type float_get_type = :f32 | :F32 | :f64 | :F64

    def hexdump: () -> String

    def inspect: () -> String

    def internal?: () -> bool

    def locked: [A] () { (IO::Buffer) -> A } -> A

    def locked?: () -> bool

    def mapped?: () -> bool

    def null?: () -> bool

    def pread: (untyped, untyped, untyped) -> untyped

    def pwrite: (untyped, untyped, untyped) -> untyped

    def read: (untyped, untyped) -> untyped

    def readonly?: () -> bool

    def resize: (Integer) -> self

    def set_string: (*untyped) -> untyped

    def set_value: (int_get_type | float_get_type, Integer offset, Float | Integer value) -> Integer

    def size: () -> Integer

    def slice: (Integer offset, Integer length) -> Buffer

    def to_s: () -> String

    def transfer: () -> Buffer

    def valid?: () -> bool

    def write: (untyped, untyped) -> untyped

    private

    def initialize: (?Integer size, ?Integer flags) -> void

    BIG_ENDIAN: Integer

    DEFAULT_SIZE: Integer

    EXTERNAL: Integer

    HOST_ENDIAN: Integer

    INTERNAL: Integer

    LITTLE_ENDIAN: Integer

    LOCKED: Integer

    MAPPED: Integer

    NETWORK_ENDIAN: Integer

    PAGE_SIZE: Integer

    PRIVATE: Integer

    READONLY: Integer

    class LockedError < RuntimeError
    end

    class AllocationError < RuntimeError
    end

    class AccessError < RuntimeError
    end

    class InvalidatedError < RuntimeError
    end

    class MaskError < ArgumentError
    end
  end
end
