%a{annotate:rdoc:skip}
class IO
  def wait: (Integer events, ?Time::_Timeout timeout) -> (Integer | false | nil)
          | (?Time::_Timeout? timeout, *wait_mode mode) -> (self | true | false)

  type wait_mode = :read | :r | :readable | :write | :w | :writable | :read_write | :rw | :readable_writable

  def wait_readable: (?Time::_Timeout? timeout) -> boolish

  def wait_writable: (?Time::_Timeout? timeout) -> boolish
end
