module Singleton
  def self.__init__: (Class klass) -> Class

  def self.instance: () -> instance

  def _dump: (?Integer depth) -> String

  def clone: () -> bot

  def dup: () -> bot

  module SingletonClassMethods
  end
end

Singleton::VERSION: String
