%a{annotate:rdoc:skip}
module RDoc
  class CodeObject
    attr_reader comment: Comment | String

    def initialize: () -> void

    def comment=: (Comment | String | nil) -> (Comment | String | nil)
  end
end
