%a{annotate:rdoc:skip}
module RDoc
  class Comment
    attr_reader format: String

    attr_accessor location: String

    alias file location

    def initialize: (?String? text, ?RDoc::Context? location, ?String? language) -> void

    def format=: (String format) -> void

    def normalized?: () -> bool

    def normalize: () -> self

    def parse: () -> Markup::Document
  end
end
