%a{annotate:rdoc:skip}
module RDoc
  class Context < CodeObject
    include Comparable

    TYPES: ::Array["class" | "instance"]

    TOMDOC_TITLES: ::Array[nil | "Public" | "Internal" | "Deprecated"]

    type class_types = singleton(RDoc::NormalClass) | singleton(RDoc::SingleClass)

    def initialize: () -> void

    def add_alias: (RDoc::Alias an_alias) -> RDoc::Alias

    def add_attribute: (RDoc::Attr attribute) -> RDoc::Attr

    def add_class: (class_types class_type, ::String given_name, ?::String superclass) -> (RDoc::NormalClass | RDoc::SingleClass)

    def add_constant: (RDoc::Constant constant) -> RDoc::Constant

    def add_include: (RDoc::Include `include`) -> RDoc::Include

    def add_extend: (RDoc::Extend ext) -> RDoc::Extend

    def add_method: (RDoc::AnyMethod method) -> RDoc::AnyMethod

    def add_module: (singleton(RDoc::NormalModule) class_type, String name) -> RDoc::NormalModule

    def attributes: () -> Array[Attr]

    def constants: () -> Array[Constant]

    def find_module_named: (untyped name) -> (untyped | self)

    def full_name: () -> "(unknown)"

    def method_list: () -> Array[AnyMethod]

    def to_s: () -> ::String

    def top_level: () -> RDoc::TopLevel
  end
end
