%a{annotate:rdoc:skip}
module RDoc
  class Parser
    def self?.parse_files_matching: (Regexp path) -> void

    def initialize: (RDoc::TopLevel top_level, String filename, String content, Hash[untyped, untyped] options, RDoc::Stats stats) -> void

    def scan: () -> RDoc::TopLevel
  end
end
