module RDoc
  module TokenStream
    def add_token: (Hash[untyped, untyped] token) -> void

    def collect_tokens: (Symbol) -> void

    alias start_collecting_tokens collect_tokens
  end

  class ClassModule < Context
    def initialize: (String name, ?String superclass) -> void

    def add_comment: (RDoc::Comment comment, RDoc::Context location) -> void
  end

  class NormalClass < ClassModule
    def initialize: (String name, ?String superclass) -> void
  end

  class SingleClass < ClassModule
    def initialize: (String name, ?String superclass) -> void
  end

  class NormalModule < ClassModule
  end

  class MethodAttr < CodeObject
    include Comparable

    attr_reader is_alias_for: MethodAttr?

    attr_reader arglists: String

    attr_accessor name: String

    attr_accessor visibility: untyped

    attr_accessor singleton: bool

    attr_reader text: String

    attr_accessor call_seq: String

    def initialize: (String text, String name, ?singleton: bool) -> void

    def pretty_name: () -> ::String

    def type: () -> ("class" | "instance")

    def path: () -> ::String

    def to_s: () -> ::String
  end

  class AnyMethod < MethodAttr
    include TokenStream

    attr_accessor call_seq: ::String

    attr_accessor params: ::String

    attr_accessor line: Integer

    def arglists: () -> String?

    def callseq: () -> String?

    def initialize: (String? text, String name, ?singleton: bool) -> void
  end

  class Attr < MethodAttr
    attr_accessor rw: "RW" | "R" | "W"

    def initialize: (String? text, String name, String rw, RDoc::Comment? comment, ?singleton: bool) -> void
  end

  class Constant < CodeObject
    attr_writer is_alias_for: String

    attr_accessor name: String

    attr_accessor value: String

    attr_accessor visibility: String

    def initialize: (String name, String value, RDoc::Comment? comment) -> void
  end

  class Mixin < CodeObject
    attr_accessor name: String

    def initialize: (String name, RDoc::Comment? comment) -> void
  end

  class Include < Mixin
  end

  class Extend < Mixin
  end

  class Alias < CodeObject
    attr_accessor name: String

    attr_accessor old_name: String

    attr_reader singleton: bool

    def initialize: (String? text, String name, String old_name, RDoc::Comment? comment, ?singleton: bool) -> void
  end

  class Stats
  end
end
