%a{annotate:rdoc:skip}
module RDoc
  class Store
    def initialize: (Options, ?path: String? , ?type: Symbol?) -> void

    def find_class_or_module: (String) -> ClassModule?

    def load_all: () -> void
  end
end
