%a{annotate:rdoc:skip}
module RDoc
  class TopLevel < Context
    MARSHAL_VERSION: 0

    attr_accessor relative_name: String

    def initialize: (String absolute_name, ?String relative_name) -> void

    def ==: (untyped other) -> bool

    alias eql? ==

    def add_alias: (RDoc::Alias an_alias) -> RDoc::Alias

    def add_constant: (RDoc::Constant constant) -> RDoc::Constant

    def add_include: (RDoc::Include `include`) -> RDoc::Include

    def add_method: (RDoc::AnyMethod method) -> RDoc::AnyMethod

    def find_class_or_module: (::String name) -> RDoc::Context

    def find_module_named: (String name) -> RDoc::Context

    def full_name: () -> String

    def to_s: () -> ::String
  end
end
