%a{annotate:rdoc:skip}
module TSort[Node]
  interface _Sortable[Node]
    def tsort_each_node: () { (Node) -> void } -> void

    def tsort_each_child: (Node) { (Node) -> void } -> void
  end

  interface _EachNode[Node]
    def call: () { (Node) -> void } -> void
  end

  interface _EachChild[Node]
    def call: (Node) { (Node) -> void } -> void
  end
end
