%a{annotate:rdoc:skip}
module URI
  def self.open: (String name, ?String mode, ?Integer perm, ?untyped options) -> ((StringIO & OpenURI::Meta) | (Tempfile & OpenURI::Meta))
               | [T] (String name, ?String mode, ?Integer perm, ?untyped options) { (StringIO | Tempfile) -> T } -> T
end

module OpenURI
  class HTTPError < StandardError
    def initialize: (String message, (StringIO & OpenURI::Meta) io) -> void

    attr_reader io: StringIO & OpenURI::Meta
  end

  class HTTPRedirect < HTTPError
    def initialize: (String message, (StringIO & OpenURI::Meta) io, URI uri) -> void

    attr_reader uri: URI
  end

  class TooManyRedirects < HTTPError
  end

  module Meta
    attr_accessor status: [ String, String ]

    attr_accessor base_uri: URI::Generic

    attr_reader meta: Hash[String, String]

    def last_modified: () -> Time?

    def content_type: () -> String

    def charet: () -> String?

    def content_encoding: () -> Array[String]
  end

  module OpenRead
    def open: (*untyped) -> IO
            | [T] (*untyped) { (IO) -> T } -> T

    def read: (untyped options) -> String
  end
end

%a{annotate:rdoc:skip}
module URI
  %a{annotate:rdoc:skip}
  class HTTP
    include OpenURI::OpenRead
  end

  %a{annotate:rdoc:skip}
  class FTP
    include OpenURI::OpenRead
  end
end
