class Logger
  interface _WriteCloser
    def write: (_ToS) -> untyped

    def close: () -> untyped
  end
  type logdev = _WriteCloser | String

  include Logger::Severity

  def <<: (untyped msg) -> (untyped | nil)

  def add: (Integer severity, ?untyped message, ?untyped progname) ?{ () -> untyped } -> true

  def close: () -> untyped

  def datetime_format: () -> String?

  def datetime_format=: (String datetime_format) -> String
                      | (nil datetime_format) -> nil

  def debug: (?untyped progname) ?{ () -> untyped } -> true

  def debug!: () -> Integer

  def debug?: () -> bool

  def error: (?untyped progname) ?{ () -> untyped } -> true

  def error!: () -> Integer

  def error?: () -> bool

  def fatal: (?untyped progname) ?{ () -> untyped } -> true

  def fatal!: () -> Integer

  def fatal?: () -> bool

  def formatter: () -> (_Formatter | nil)

  def formatter=: (_Formatter) -> _Formatter
                | (nil) -> nil

  def info: (?untyped progname) ?{ () -> untyped } -> true

  def info!: () -> Integer

  def info?: () -> bool

  def level: () -> Integer

  def level=: (Integer | interned severity) -> Integer

  alias log add

  def progname: () -> untyped

  def progname=: (untyped) -> untyped

  def reopen: () -> self
            | (logdev?) -> self

  alias sev_threshold level

  alias sev_threshold= level=

  def unknown: (?untyped progname) ?{ () -> untyped } -> true

  def warn: (?untyped progname) ?{ () -> untyped } -> true

  def warn!: () -> Integer

  def warn?: () -> bool

  private

  def format_message: (String severity, Time datetime, untyped progname, untyped msg) -> _ToS

  def format_severity: (Integer severity) -> String

  def initialize: (logdev? logdev, ?Numeric | String shift_age, ?Integer shift_size, ?shift_period_suffix: String, ?binmode: boolish, ?datetime_format: String, ?formatter: _Formatter, ?progname: String, ?level: Integer | interned) -> void
end

Logger::ProgName: String

Logger::SEV_LABEL: Array[String]

Logger::VERSION: String
