%a{annotate:rdoc:skip}
class Pathname
  def find: (?ignore_error: boolish) { (Pathname) -> untyped } -> nil
          | (?ignore_error: boolish) -> Enumerator[Pathname, nil]

  def rmtree: () -> self
end
