#!/usr/bin/env python3
"""
Automated pattern detection in codebase.
Usage: python pattern-detector.py --directory ./src
"""

import re
import argparse
from pathlib import Path
from collections import defaultdict
from typing import Dict, List

# Pattern signatures to search for
PATTERN_SIGNATURES = {
    'Factory Pattern': [
        r'(factory|create\w+|build\w+)\s*\(',
        r'class.*Factory',
    ],
    'Singleton Pattern': [
        r'getInstance|getinstance',
        r'private\s+static\s+\w+\s+instance',
        r'static\s+\w+\s*=\s*null',
    ],
    'Observer Pattern': [
        r'(addEventListener|subscribe|on)\s*\(',
        r'(emit|publish|notify)\s*\(',
        r'class.*Observer',
    ],
    'Strategy Pattern': [
        r'(strategy|algorithm)\s*(interface|class)',
        r'class.*Strategy',
    ],
    'Repository Pattern': [
        r'class.*Repository',
        r'interface.*Repository',
    ],
    'Decorator Pattern': [
        r'@\w+\s*\(',  # Decorator syntax
        r'class.*Decorator',
    ],
    'Adapter Pattern': [
        r'class.*Adapter',
        r'interface.*Adapter',
    ],
    'Builder Pattern': [
        r'class.*Builder',
        r'\.with\w+\(',  # Fluent API pattern
    ],
    'Command Pattern': [
        r'class.*Command',
        r'execute\s*\(\s*\)',
    ],
}

def detect_patterns(directory: Path, file_extensions: List[str] = None) -> Dict[str, List[str]]:
    """Detect design patterns in codebase."""
    if file_extensions is None:
        file_extensions = ['.ts', '.js', '.tsx', '.jsx', '.py', '.java', '.go', '.rs']

    results = defaultdict(list)

    # Search for pattern signatures
    for pattern_name, signatures in PATTERN_SIGNATURES.items():
        found_files = set()

        for ext in file_extensions:
            for file_path in directory.rglob(f'*{ext}'):
                try:
                    content = file_path.read_text()

                    # Check if any signature matches
                    for signature in signatures:
                        if re.search(signature, content, re.IGNORECASE):
                            rel_path = file_path.relative_to(directory)
                            found_files.add(str(rel_path))
                            break

                except Exception:
                    continue

        if found_files:
            results[pattern_name] = sorted(list(found_files))

    return results

def main():
    parser = argparse.ArgumentParser(description='Detect design patterns in codebase')
    parser.add_argument('--directory', default='.', help='Directory to analyze')
    parser.add_argument('--extensions', help='Comma-separated file extensions (e.g., .ts,.js)')
    args = parser.parse_args()

    directory = Path(args.directory).resolve()

    if not directory.exists():
        print(f"Error: Directory '{directory}' does not exist")
        return 1

    extensions = None
    if args.extensions:
        extensions = [ext.strip() if ext.startswith('.') else f'.{ext.strip()}'
                     for ext in args.extensions.split(',')]

    print(f"# Pattern Detection Report")
    print(f"Project: {directory.name}")
    print(f"Path: {directory}")
    print()

    patterns = detect_patterns(directory, extensions)

    if patterns:
        print(f"## Patterns Found: {len(patterns)}")
        print()

        for pattern_name, files in sorted(patterns.items()):
            print(f"### {pattern_name}")
            print(f"**Occurrences**: {len(files)}")
            print()
            print("**Files:**")
            for file in files[:10]:  # Show first 10
                print(f"- `{file}`")
            if len(files) > 10:
                print(f"- ... and {len(files) - 10} more")
            print()
    else:
        print("## No Patterns Detected")
        print("Common design patterns not found in the codebase.")
        print()

    print("---")
    print("Generated by research-agent/analyzing-patterns")

if __name__ == '__main__':
    main()
